/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// The Tabs & Flexible Layout prototype's central state: a tree of panels
// (splits) each holding an ordered list of tabs, plus the tab registry
// itself. Lives in a plain module-level `$state` (same pattern as
// `tablePersistence` in @podman-desktop/ui-svelte) so it survives component
// remounts as the user navigates between routes.
import type { LeafPanelNode, OpenMode, PanelNode, SplitDirection, SplitPanelNode } from '@podman-desktop/ui-svelte';
import { get } from 'svelte/store';

import { currentScreen, usesPermanentPageTab } from '/@/stores/prototype';

import type { SubView, WorkspaceResourceType, WorkspaceTab } from './layout-types';
import { tabKey } from './layout-types';
import { getPageTabTitle, goToAppPageRoute, PAGE_TAB_ID, rememberAppPage } from './page-tab.svelte';

// Whether this profile has ever opened a tab, persisted across restarts so the empty global tab
// bar's first-run hint (see GlobalTabBar.svelte) is shown exactly until someone opens their
// first tab, then never again - not re-shown every time the workspace happens to be empty again.
const EVER_OPENED_TAB_KEY = 'podman-desktop.workspace.ever-opened-tab.v1';
function readEverOpenedTabFlag(): boolean {
  try {
    return localStorage.getItem(EVER_OPENED_TAB_KEY) === '1';
  } catch {
    return true; // fail open: don't nag if storage isn't available for some reason
  }
}
let everOpenedTab = $state(readEverOpenedTabFlag());

export function hasEverOpenedTab(): boolean {
  return everOpenedTab;
}

function markTabEverOpened(): void {
  if (everOpenedTab) return;
  everOpenedTab = true;
  try {
    localStorage.setItem(EVER_OPENED_TAB_KEY, '1');
  } catch {
    // Non-fatal: worst case the first-run hint reappears next launch.
  }
}

export interface OpenTabInput {
  resourceType: WorkspaceResourceType;
  resourceId: string;
  subView?: SubView;
  title: string;
  subtitle?: string;
  iconClass?: string;
  agentCreated?: boolean;
}

let idCounter = 0;
function genId(prefix: string): string {
  idCounter += 1;
  return `${prefix}-${Date.now().toString(36)}-${idCounter}`;
}

function createLeaf(): LeafPanelNode {
  return { kind: 'leaf', id: genId('panel'), tabIds: [], activeTabId: undefined };
}

const initialLeaf = createLeaf();

interface LayoutState {
  tree: PanelNode;
  tabs: Record<string, WorkspaceTab>;
  focusedPanelId: string;
  maximizedPanelId: string | undefined;
}

export const layoutState: LayoutState = $state({
  tree: initialLeaf,
  tabs: {},
  focusedPanelId: initialLeaf.id,
  maximizedPanelId: undefined,
});

// ---- pure tree lookups (read-only traversal; mutations happen on the caller's captured references since layoutState.tree is deeply reactive) ----

export function findLeaf(node: PanelNode, id: string): LeafPanelNode | undefined {
  if (node.kind === 'leaf') return node.id === id ? node : undefined;
  for (const child of node.children) {
    const found = findLeaf(child, id);
    if (found) return found;
  }
  return undefined;
}

export function findLeafContainingTab(node: PanelNode, tabId: string): LeafPanelNode | undefined {
  if (node.kind === 'leaf') return node.tabIds.includes(tabId) ? node : undefined;
  for (const child of node.children) {
    const found = findLeafContainingTab(child, tabId);
    if (found) return found;
  }
  return undefined;
}

export function findFirstLeaf(node: PanelNode): LeafPanelNode {
  return node.kind === 'leaf' ? node : findFirstLeaf(node.children[0]);
}

/** Last leaf in tree order (rightmost / bottommost section) — hosts the shared settings gear. */
export function findLastLeaf(node: PanelNode): LeafPanelNode {
  return node.kind === 'leaf' ? node : findLastLeaf(node.children[node.children.length - 1]);
}

export function getLastLeafId(): string {
  return findLastLeaf(layoutState.tree).id;
}

function findParent(node: PanelNode, childId: string): SplitPanelNode | undefined {
  if (node.kind === 'leaf') return undefined;
  for (const child of node.children) {
    if (child.id === childId) return node;
    const found = findParent(child, childId);
    if (found) return found;
  }
  return undefined;
}

export function countLeaves(node: PanelNode): number {
  return node.kind === 'leaf' ? 1 : node.children.reduce((sum, child) => sum + countLeaves(child), 0);
}

export function getTabsForPanel(panelId: string): WorkspaceTab[] {
  const leaf = findLeaf(layoutState.tree, panelId);
  if (!leaf) return [];
  return leaf.tabIds.map(id => layoutState.tabs[id]).filter((t): t is WorkspaceTab => !!t);
}

export function findExistingTabByKey(key: string): WorkspaceTab | undefined {
  return Object.values(layoutState.tabs).find(t => t.key === key);
}

/** Any open tab (regardless of subView) pointing at this resource - used to avoid stomping on a tab the user already has open on a different sub-view. */
export function findAnyTabForResource(
  resourceType: WorkspaceTab['resourceType'],
  resourceId: string,
): WorkspaceTab | undefined {
  return Object.values(layoutState.tabs).find(t => t.resourceType === resourceType && t.resourceId === resourceId);
}

// ---- mutation helpers ----

function removeTabFromLeaf(leaf: LeafPanelNode, tabId: string): void {
  const idx = leaf.tabIds.indexOf(tabId);
  if (idx === -1) return;
  leaf.tabIds.splice(idx, 1);
  if (leaf.activeTabId === tabId) {
    leaf.activeTabId = leaf.tabIds[Math.max(0, idx - 1)] ?? leaf.tabIds[0];
  }
}

/** Removes an empty leaf from the tree, collapsing its parent split if it drops to a single remaining child. */
function pruneEmptyLeaf(leafId: string): void {
  if (layoutState.tree.kind === 'leaf') return; // never prune the last remaining panel
  const parent = findParent(layoutState.tree, leafId);
  if (!parent) return;
  const idx = parent.children.findIndex(c => c.id === leafId);
  if (idx === -1) return;
  parent.children.splice(idx, 1);
  parent.sizes.splice(idx, 1);

  if (layoutState.maximizedPanelId === leafId) layoutState.maximizedPanelId = undefined;
  if (layoutState.focusedPanelId === leafId) {
    layoutState.focusedPanelId = findFirstLeaf(layoutState.tree).id;
  }

  if (parent.children.length === 1) {
    const onlyChild = parent.children[0];
    const grandParent = findParent(layoutState.tree, parent.id);
    if (grandParent) {
      const parentIdx = grandParent.children.findIndex(c => c.id === parent.id);
      grandParent.children[parentIdx] = onlyChild;
    } else {
      layoutState.tree = onlyChild;
    }
  }
}

/** Remove page-tab id from every leaf except the home leaf (first section). */
function stripPageTabFromOtherLeaves(node: PanelNode, homeLeafId: string): void {
  if (node.kind === 'leaf') {
    if (node.id === homeLeafId) return;
    const idx = node.tabIds.indexOf(PAGE_TAB_ID);
    if (idx !== -1) {
      node.tabIds.splice(idx, 1);
      if (node.activeTabId === PAGE_TAB_ID) {
        node.activeTabId = node.tabIds[0];
      }
    }
    return;
  }
  for (const child of node.children) {
    stripPageTabFromOtherLeaves(child, homeLeafId);
  }
}

/** Drop the permanent page tab everywhere (Version 2 compact-nav). */
function removePageTabFromLayout(): void {
  function walk(node: PanelNode): void {
    if (node.kind === 'leaf') {
      const idx = node.tabIds.indexOf(PAGE_TAB_ID);
      if (idx !== -1) {
        node.tabIds.splice(idx, 1);
        if (node.activeTabId === PAGE_TAB_ID) {
          node.activeTabId = node.tabIds[0];
        }
      }
      return;
    }
    for (const child of node.children) {
      walk(child);
    }
  }
  walk(layoutState.tree);
  delete layoutState.tabs[PAGE_TAB_ID];
}

/**
 * Permanent first-section tab: current list/dashboard page (Containers, …).
 * Present as the first tab of the first leaf in Version 1; omitted in Version 2
 * (compact-nav) where lists live in the side panel.
 */
export function ensurePageTab(): void {
  if (!usesPermanentPageTab(get(currentScreen))) {
    removePageTabFromLayout();
    return;
  }

  const title = getPageTabTitle();
  const existing = layoutState.tabs[PAGE_TAB_ID];
  if (!existing) {
    layoutState.tabs[PAGE_TAB_ID] = {
      id: PAGE_TAB_ID,
      key: PAGE_TAB_ID,
      title,
      permanent: true,
      pinned: true,
      resourceType: 'app-page',
      resourceId: 'app-page',
      iconClass: 'fas fa-house',
    };
  } else if (existing.title !== title || !existing.permanent || !existing.pinned) {
    existing.title = title;
    existing.permanent = true;
    existing.pinned = true;
  }

  const first = findFirstLeaf(layoutState.tree);
  stripPageTabFromOtherLeaves(layoutState.tree, first.id);

  const idx = first.tabIds.indexOf(PAGE_TAB_ID);
  if (idx === -1) {
    first.tabIds.unshift(PAGE_TAB_ID);
  } else if (idx > 0) {
    first.tabIds.splice(idx, 1);
    first.tabIds.unshift(PAGE_TAB_ID);
  }
  if (!first.activeTabId || !first.tabIds.includes(first.activeTabId)) {
    first.activeTabId = PAGE_TAB_ID;
  }
}

/** Focus the permanent page tab in the first section (and navigate to its list route if needed). */
export function activatePageTab(): void {
  if (!usesPermanentPageTab(get(currentScreen))) {
    // Version 2: no page tab — keep resource tabs (or empty state) and only sync the route.
    goToAppPageRoute();
    return;
  }
  ensurePageTab();
  const leaf = findLeafContainingTab(layoutState.tree, PAGE_TAB_ID) ?? findFirstLeaf(layoutState.tree);
  leaf.activeTabId = PAGE_TAB_ID;
  layoutState.focusedPanelId = leaf.id;
  goToAppPageRoute();
}

/**
 * Main-nav navigation for the tabs prototype: remember the list/dashboard page,
 * focus the permanent primary tab (Version 1), and route there.
 */
export function navigateToAppPage(url: string, name?: string): void {
  rememberAppPage(url, name);
  activatePageTab();
}

export function resourceTabCount(): number {
  return Object.keys(layoutState.tabs).filter(id => id !== PAGE_TAB_ID).length;
}

function closeTabInternal(panelId: string, tabId: string): void {
  if (tabId === PAGE_TAB_ID) return;
  const leaf = findLeaf(layoutState.tree, panelId);
  if (!leaf) return;
  removeTabFromLeaf(leaf, tabId);
  delete layoutState.tabs[tabId];
  if (leaf.tabIds.length === 0) pruneEmptyLeaf(leaf.id);

  // Version 1: no resource tabs left → show the permanent page tab (list content).
  // Version 2: leave the shell empty (lists live in the compact sidebar).
  if (resourceTabCount() === 0 && usesPermanentPageTab(get(currentScreen))) {
    activatePageTab();
  }
}

/** Wraps `targetLeafId` in a new split (if needed) with a fresh sibling leaf, and returns that new leaf. */
function splitLeaf(targetLeafId: string, direction: SplitDirection, position: 'before' | 'after'): LeafPanelNode {
  const newLeaf = createLeaf();
  const parent = findParent(layoutState.tree, targetLeafId);

  if (parent?.direction === direction) {
    const idx = parent.children.findIndex(c => c.id === targetLeafId);
    const insertAt = position === 'after' ? idx + 1 : idx;
    parent.children.splice(insertAt, 0, newLeaf);
    const avg = parent.sizes[idx] ?? 100 / parent.children.length;
    parent.sizes.splice(insertAt, 0, avg);
    return newLeaf;
  }

  // need a brand-new split wrapping the target leaf
  const targetNode = parent ? parent.children[parent.children.findIndex(c => c.id === targetLeafId)] : layoutState.tree;
  const newSplit: SplitPanelNode = {
    kind: 'split',
    id: genId('split'),
    direction,
    children: position === 'after' ? [targetNode, newLeaf] : [newLeaf, targetNode],
    sizes: [50, 50],
  };

  if (parent) {
    const idx = parent.children.findIndex(c => c.id === targetLeafId);
    parent.children[idx] = newSplit;
  } else {
    layoutState.tree = newSplit;
  }
  return newLeaf;
}

// ---- public API ----

export function openTab(input: OpenTabInput, mode: OpenMode = 'replace', targetPanelId?: string): string {
  const key = tabKey(input.resourceType, input.resourceId, input.subView);
  const existing = findExistingTabByKey(key);

  // Default into the home section (permanent page tab) so list clicks keep Containers
  // in the same strip. Explicit targetPanelId (palette / per-panel +) still wins.
  const homeLeaf = findFirstLeaf(layoutState.tree);
  const baseLeaf = targetPanelId ? (findLeaf(layoutState.tree, targetPanelId) ?? homeLeaf) : homeLeaf;

  // Split modes always create a new section. If the tab already exists, move it there
  // instead of only focusing it in place (presets need a reliable side-by-side layout).
  if (existing && (mode === 'splitRight' || mode === 'splitDown')) {
    ensurePageTab();
    const sourceLeaf = findLeafContainingTab(layoutState.tree, existing.id);
    const destinationLeaf = splitLeaf(baseLeaf.id, mode === 'splitRight' ? 'row' : 'column', 'after');
    if (sourceLeaf && sourceLeaf.id !== destinationLeaf.id) {
      removeTabFromLeaf(sourceLeaf, existing.id);
      if (sourceLeaf.tabIds.length === 0) {
        pruneEmptyLeaf(sourceLeaf.id);
      }
    }
    destinationLeaf.tabIds.push(existing.id);
    destinationLeaf.activeTabId = existing.id;
    layoutState.focusedPanelId = destinationLeaf.id;
    ensurePageTab();
    return existing.id;
  }

  if (existing) {
    ensurePageTab();
    const leaf = findLeafContainingTab(layoutState.tree, existing.id);
    if (leaf) {
      leaf.activeTabId = existing.id;
      layoutState.focusedPanelId = leaf.id;
    }
    return existing.id;
  }

  markTabEverOpened();
  ensurePageTab();
  const id = genId('tab');
  const tab: WorkspaceTab = {
    id,
    key,
    title: input.title,
    subtitle: input.subtitle,
    iconClass: input.iconClass,
    resourceType: input.resourceType,
    resourceId: input.resourceId,
    subView: input.subView,
    agentCreated: input.agentCreated,
  };
  layoutState.tabs[id] = tab;

  let destinationLeaf: LeafPanelNode;
  switch (mode) {
    case 'splitRight':
    case 'splitDown':
      // Home leaf always has the page tab, so this always creates a real sibling section.
      destinationLeaf = splitLeaf(baseLeaf.id, mode === 'splitRight' ? 'row' : 'column', 'after');
      break;
    case 'replace': {
      // Leave the permanent page tab (and other pinned tabs) in place.
      for (const existingTabId of [...baseLeaf.tabIds]) {
        if (existingTabId === PAGE_TAB_ID) continue;
        const existingTab = layoutState.tabs[existingTabId];
        if (existingTab && !existingTab.pinned && !existingTab.permanent) {
          removeTabFromLeaf(baseLeaf, existingTabId);
          delete layoutState.tabs[existingTabId];
        }
      }
      destinationLeaf = baseLeaf;
      break;
    }
    case 'newTab':
    default:
      destinationLeaf = baseLeaf;
      break;
  }

  destinationLeaf.tabIds.push(id);
  destinationLeaf.activeTabId = id;
  layoutState.focusedPanelId = destinationLeaf.id;
  ensurePageTab();
  return id;
}

export function selectTab(panelId: string, tabId: string): void {
  const leaf = findLeaf(layoutState.tree, panelId);
  if (!leaf) return;
  leaf.activeTabId = tabId;
  layoutState.focusedPanelId = panelId;
  if (tabId === PAGE_TAB_ID) {
    goToAppPageRoute();
  }
}

export function closeTab(panelId: string, tabId: string): void {
  closeTabInternal(panelId, tabId);
}

/** Convenience for callers (e.g. the stale-tab placeholder) that only know the tab id. */
export function closeTabById(tabId: string): void {
  const leaf = findLeafContainingTab(layoutState.tree, tabId);
  if (leaf) closeTabInternal(leaf.id, tabId);
}

export function closeOthers(panelId: string, tabId: string): void {
  const leaf = findLeaf(layoutState.tree, panelId);
  if (!leaf) return;
  for (const otherId of [...leaf.tabIds]) {
    if (otherId === tabId) continue;
    const otherTab = layoutState.tabs[otherId];
    if (otherTab?.pinned) continue;
    closeTabInternal(panelId, otherId);
  }
}

export function closeAllInPanel(panelId: string): void {
  const leaf = findLeaf(layoutState.tree, panelId);
  if (!leaf) return;
  for (const tabId of [...leaf.tabIds]) {
    const tab = layoutState.tabs[tabId];
    if (tab?.pinned) continue;
    closeTabInternal(panelId, tabId);
  }
}

export function pinToggle(_panelId: string, tabId: string): void {
  if (tabId === PAGE_TAB_ID) return;
  const tab = layoutState.tabs[tabId];
  if (tab) tab.pinned = !tab.pinned;
}

export function reorderTab(panelId: string, tabId: string, beforeTabId: string | undefined): void {
  if (tabId === PAGE_TAB_ID) return;
  const leaf = findLeaf(layoutState.tree, panelId);
  if (!leaf) return;
  const from = leaf.tabIds.indexOf(tabId);
  if (from === -1) return;
  leaf.tabIds.splice(from, 1);
  const to = beforeTabId ? leaf.tabIds.indexOf(beforeTabId) : leaf.tabIds.length;
  leaf.tabIds.splice(to === -1 ? leaf.tabIds.length : to, 0, tabId);
}

export function moveTabFromOtherPanel(
  targetPanelId: string,
  sourcePanelId: string,
  tabId: string,
  beforeTabId: string | undefined,
): void {
  if (tabId === PAGE_TAB_ID) return;
  const sourceLeaf = findLeaf(layoutState.tree, sourcePanelId);
  const targetLeaf = findLeaf(layoutState.tree, targetPanelId);
  if (!sourceLeaf || !targetLeaf || sourceLeaf.id === targetLeaf.id) return;
  removeTabFromLeaf(sourceLeaf, tabId);
  const to = beforeTabId ? targetLeaf.tabIds.indexOf(beforeTabId) : targetLeaf.tabIds.length;
  targetLeaf.tabIds.splice(to === -1 ? targetLeaf.tabIds.length : to, 0, tabId);
  targetLeaf.activeTabId = tabId;
  layoutState.focusedPanelId = targetLeaf.id;
  if (sourceLeaf.tabIds.length === 0) pruneEmptyLeaf(sourceLeaf.id);
}

export function splitRight(panelId: string, tabId: string): void {
  if (tabId === PAGE_TAB_ID) return;
  moveTabToNewLeaf(panelId, tabId, splitLeaf(panelId, 'row', 'after'));
}

export function splitDown(panelId: string, tabId: string): void {
  if (tabId === PAGE_TAB_ID) return;
  moveTabToNewLeaf(panelId, tabId, splitLeaf(panelId, 'column', 'after'));
}

export function moveToNewPanel(panelId: string, tabId: string): void {
  if (tabId === PAGE_TAB_ID) return;
  const root = layoutState.tree;
  const direction: SplitDirection = root.kind === 'split' ? root.direction : 'row';
  moveTabToNewLeaf(panelId, tabId, splitLeaf(panelId, direction, 'after'));
}

function moveTabToNewLeaf(sourcePanelId: string, tabId: string, newLeaf: LeafPanelNode): void {
  const sourceLeaf = findLeaf(layoutState.tree, sourcePanelId);
  if (!sourceLeaf) return;
  removeTabFromLeaf(sourceLeaf, tabId);
  newLeaf.tabIds.push(tabId);
  newLeaf.activeTabId = tabId;
  layoutState.focusedPanelId = newLeaf.id;
  if (sourceLeaf.tabIds.length === 0) pruneEmptyLeaf(sourceLeaf.id);
}

export function focusPanel(panelId: string): void {
  layoutState.focusedPanelId = panelId;
}

export function toggleMaximize(panelId: string): void {
  layoutState.maximizedPanelId = layoutState.maximizedPanelId === panelId ? undefined : panelId;
}

export function resizeSplit(splitId: string, sizes: number[]): void {
  const node = findSplitById(layoutState.tree, splitId);
  if (node) node.sizes = sizes;
}

function findSplitById(node: PanelNode, id: string): SplitPanelNode | undefined {
  if (node.kind === 'leaf') return undefined;
  if (node.id === id) return node;
  for (const child of node.children) {
    const found = findSplitById(child, id);
    if (found) return found;
  }
  return undefined;
}

/** Closes the active tab in the currently focused panel (Cmd/Ctrl+W). */
export function closeActiveTab(): void {
  const leaf = findLeaf(layoutState.tree, layoutState.focusedPanelId);
  if (!leaf?.activeTabId) return;
  const tab = layoutState.tabs[leaf.activeTabId];
  if (tab?.pinned) return;
  closeTabInternal(leaf.id, leaf.activeTabId);
}

/** Switches to the next/previous tab in the currently focused panel (Ctrl/Cmd+Tab and
 * Ctrl/Cmd+Shift+Tab), matching Cursor/VS Code's tab-cycling keybinding - previously the only
 * way to switch tabs at all was to click one directly. */
export function cycleActiveTab(direction: 1 | -1): void {
  const leaf = findLeaf(layoutState.tree, layoutState.focusedPanelId);
  if (!leaf || leaf.tabIds.length < 2) return;
  const currentIndex = leaf.activeTabId ? leaf.tabIds.indexOf(leaf.activeTabId) : -1;
  const nextIndex = (currentIndex + direction + leaf.tabIds.length) % leaf.tabIds.length;
  leaf.activeTabId = leaf.tabIds[nextIndex];
}

export function markTabStale(tabId: string, stale: boolean): void {
  const tab = layoutState.tabs[tabId];
  if (tab) tab.stale = stale;
}

/** True when at least one closable resource tab is open (ignores the permanent page tab). */
export function hasAnyTabs(): boolean {
  return resourceTabCount() > 0;
}

/** True when this panel has tabs that "Close section" can remove (not only the page tab). */
export function hasClosableTabsInPanel(panelId: string): boolean {
  return getTabsForPanel(panelId).some(tab => tab.id !== PAGE_TAB_ID && !tab.permanent);
}

/** Total number of open tabs across every panel - used for the persistent global tab bar. */
export function tabCount(): number {
  return Object.keys(layoutState.tabs).length;
}

// ---- global (cross-panel) helpers for the single persistent tab bar that's mounted once at
// the app root (see GlobalTabBar.svelte) and shown on every page, not just /workspace. It
// renders every open tab as one flat, ordered list regardless of which panel/split holds it -
// splits still exist for side-by-side viewing inside the workspace itself, but browsing the
// rest of the app only ever needs "here's everything I have open, take me back to any of it". ----

/** All open tabs, panel-by-panel in tree order, so the flat bar's ordering matches the layout. */
export function getAllTabsOrdered(): WorkspaceTab[] {
  const leaves: LeafPanelNode[] = [];
  function collectLeaves(node: PanelNode): void {
    if (node.kind === 'leaf') {
      leaves.push(node);
    } else {
      for (const child of node.children) collectLeaves(child);
    }
  }
  collectLeaves(layoutState.tree);

  const ordered: WorkspaceTab[] = [];
  for (const leaf of leaves) {
    for (const tabId of leaf.tabIds) {
      const tab = layoutState.tabs[tabId];
      if (tab) ordered.push(tab);
    }
  }
  return ordered;
}

/** The tab currently on screen in the focused panel - the one thing to highlight in the flat bar. */
export function activeTabIdOfFocusedPanel(): string | undefined {
  return findLeaf(layoutState.tree, layoutState.focusedPanelId)?.activeTabId;
}

export interface HiddenWhileMaximized {
  otherPanelCount: number;
  otherTabs: WorkspaceTab[];
}

/** While a panel is maximized (see toggleMaximize), every other panel disappears from view
 * entirely (WorkspaceLayout only renders the maximized leaf) - with nothing on screen hinting
 * they still exist, it's easy to forget a whole side-by-side comparison is sitting behind the
 * maximized panel. Returns undefined when nothing is maximized, or when maximizing didn't
 * actually hide anything (e.g. it's the only panel left). */
export function getHiddenWhileMaximized(): HiddenWhileMaximized | undefined {
  const maximizedId = layoutState.maximizedPanelId;
  if (!maximizedId) return undefined;

  const otherLeaves: LeafPanelNode[] = [];
  function collectOtherLeaves(node: PanelNode): void {
    if (node.kind === 'leaf') {
      if (node.id !== maximizedId) otherLeaves.push(node);
    } else {
      for (const child of node.children) collectOtherLeaves(child);
    }
  }
  collectOtherLeaves(layoutState.tree);
  if (otherLeaves.length === 0) return undefined;

  const otherTabs = otherLeaves.flatMap(leaf =>
    leaf.tabIds.map(id => layoutState.tabs[id]).filter((t): t is WorkspaceTab => !!t),
  );
  return { otherPanelCount: otherLeaves.length, otherTabs };
}

/** If the workspace is currently a plain two-way split (side by side or stacked, not nested
 * further) with exactly one tab showing in each half, returns those two tabs in tree order.
 * Used to auto-surface a comparison insight for split views the user made themselves by
 * dragging/splitting a tab - not just the ones the "agent" demo opens - since a side-by-side
 * view is the same "comparing two things" moment either way (see layout-agent-demo.svelte.ts). */
export function getTwoPanelSplitTabs(): [WorkspaceTab, WorkspaceTab] | undefined {
  const root = layoutState.tree;
  if (root.kind !== 'split' || root.children.length !== 2) return undefined;
  const [left, right] = root.children;
  if (left.kind !== 'leaf' || right.kind !== 'leaf') return undefined;
  if (left.tabIds.length !== 1 || right.tabIds.length !== 1) return undefined;
  const a = layoutState.tabs[left.tabIds[0]];
  const b = layoutState.tabs[right.tabIds[0]];
  if (!a || !b) return undefined;
  return [a, b];
}

export function selectTabAnyPanel(tabId: string): void {
  const leaf = findLeafContainingTab(layoutState.tree, tabId);
  if (leaf) selectTab(leaf.id, tabId);
}

export function closeAllTabsExcept(tabId: string): void {
  for (const otherId of Object.keys(layoutState.tabs)) {
    if (otherId === tabId || layoutState.tabs[otherId]?.pinned) continue;
    closeTabById(otherId);
  }
}

export function closeAllTabsEverywhere(): void {
  for (const id of Object.keys(layoutState.tabs)) {
    if (id === PAGE_TAB_ID) continue;
    if (layoutState.tabs[id]?.pinned || layoutState.tabs[id]?.permanent) continue;
    closeTabById(id);
  }
  if (usesPermanentPageTab(get(currentScreen))) {
    activatePageTab();
  }
}

/** Reordering in the flat bar can also move a tab between panels, resolved via the same primitives the per-panel drag-and-drop uses. */
export function reorderTabGlobal(tabId: string, beforeTabId: string | undefined): void {
  const sourceLeaf = findLeafContainingTab(layoutState.tree, tabId);
  if (!sourceLeaf) return;
  const targetLeaf = beforeTabId ? findLeafContainingTab(layoutState.tree, beforeTabId) : sourceLeaf;
  if (!targetLeaf) return;
  if (targetLeaf.id === sourceLeaf.id) {
    reorderTab(sourceLeaf.id, tabId, beforeTabId);
  } else {
    moveTabFromOtherPanel(targetLeaf.id, sourceLeaf.id, tabId, beforeTabId);
  }
}

/** Move `tabId` into a new section beside its current one (other sections unchanged). */
export function splitRightAnyPanel(tabId: string): void {
  const leaf = findLeafContainingTab(layoutState.tree, tabId);
  if (leaf) splitRight(leaf.id, tabId);
}

export function splitDownAnyPanel(tabId: string): void {
  const leaf = findLeafContainingTab(layoutState.tree, tabId);
  if (leaf) splitDown(leaf.id, tabId);
}

export function moveToNewPanelAnyPanel(tabId: string): void {
  const leaf = findLeafContainingTab(layoutState.tree, tabId);
  if (leaf) moveToNewPanel(leaf.id, tabId);
}

/**
 * True when this tab can leave its section for a new one. The permanent page tab
 * never moves; any other tab can move as long as at least one tab remains
 * (typically the page tab in the home section).
 */
export function canMoveTabToNewSection(tabId: string): boolean {
  if (tabId === PAGE_TAB_ID) return false;
  const leaf = findLeafContainingTab(layoutState.tree, tabId);
  if (!leaf) return false;
  return leaf.tabIds.some(id => id !== tabId);
}

/** Reset hook used by the "load named layout" flow (and tests). Presets do not call this. */
export function resetLayout(): void {
  const leaf = createLeaf();
  layoutState.tree = leaf;
  layoutState.tabs = {};
  layoutState.focusedPanelId = leaf.id;
  layoutState.maximizedPanelId = undefined;
  ensurePageTab();
}

// Permanent page tab is part of every fresh Version 1 workspace; Version 2 drops it.
ensurePageTab();
currentScreen.subscribe(() => {
  ensurePageTab();
});
