/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// The four built-in layout presets from section 4.8 of the vision doc. Each
// takes plain identifiers (rather than full store objects) so this module
// stays decoupled from the container/pod/image UI-model types.
import { layoutState, openTab, resetLayout } from './layout-store.svelte';
import { imageKey, podKey } from './layout-types';

export type PresetId = 'debug-duo' | 'logs-terminal' | 'pod-inspector' | 'image-diff';

export interface PresetDefinition {
  id: PresetId;
  title: string;
  description: string;
  iconClass: string;
}

export const PRESETS: PresetDefinition[] = [
  {
    id: 'debug-duo',
    title: 'Debug Duo',
    description: 'Two containers, logs side by side.',
    iconClass: 'fas fa-table-columns',
  },
  {
    id: 'logs-terminal',
    title: 'Logs + Terminal',
    description: 'One container: live logs on top, a shell below.',
    iconClass: 'fas fa-terminal',
  },
  {
    id: 'pod-inspector',
    title: 'Pod Inspector',
    description: 'Pod summary alongside one of its container logs.',
    iconClass: 'fas fa-cubes',
  },
  {
    id: 'image-diff',
    title: 'Image Diff',
    description: 'Two images, Inspect views side by side.',
    iconClass: 'fas fa-code-compare',
  },
];

export function applyDebugDuoPreset(
  containerA: { id: string; name: string },
  containerB: { id: string; name: string },
): void {
  resetLayout();
  const firstPanel = openTabAndGetPanel({
    resourceType: 'container',
    resourceId: containerA.id,
    subView: 'logs',
    title: `${containerA.name} · Logs`,
  });
  openTab(
    { resourceType: 'container', resourceId: containerB.id, subView: 'logs', title: `${containerB.name} · Logs` },
    'splitRight',
    firstPanel,
  );
}

export function applyLogsPlusTerminalPreset(container: { id: string; name: string }): void {
  resetLayout();
  const firstPanel = openTabAndGetPanel({
    resourceType: 'container',
    resourceId: container.id,
    subView: 'logs',
    title: `${container.name} · Logs`,
  });
  openTab(
    { resourceType: 'container', resourceId: container.id, subView: 'terminal', title: `${container.name} · Terminal` },
    'splitDown',
    firstPanel,
  );
}

export function applyPodInspectorPreset(
  pod: { name: string; engineId: string },
  container?: { id: string; name: string },
): void {
  resetLayout();
  const firstPanel = openTabAndGetPanel({
    resourceType: 'pod',
    resourceId: podKey(pod.name, pod.engineId),
    subView: 'summary',
    title: `${pod.name} · Summary`,
  });
  if (container) {
    openTab(
      { resourceType: 'container', resourceId: container.id, subView: 'logs', title: `${container.name} · Logs` },
      'splitRight',
      firstPanel,
    );
  }
}

export function applyImageDiffPreset(
  imageA: { id: string; engineId: string; base64RepoTag: string; name: string },
  imageB: { id: string; engineId: string; base64RepoTag: string; name: string },
): void {
  resetLayout();
  const firstPanel = openTabAndGetPanel({
    resourceType: 'image',
    resourceId: imageKey(imageA.id, imageA.engineId, imageA.base64RepoTag),
    subView: 'inspect',
    title: `${imageA.name} · Inspect`,
  });
  openTab(
    {
      resourceType: 'image',
      resourceId: imageKey(imageB.id, imageB.engineId, imageB.base64RepoTag),
      subView: 'inspect',
      title: `${imageB.name} · Inspect`,
    },
    'splitRight',
    firstPanel,
  );
}

function openTabAndGetPanel(input: Parameters<typeof openTab>[0]): string {
  openTab(input, 'newTab');
  // openTab() always leaves layoutState.focusedPanelId pointing at the panel it just placed the tab in.
  return layoutState.focusedPanelId;
}
