/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// What the "+" tab palette's Agent row leads with when the user hasn't typed anything yet. A
// static "Ask agent to prepare a layout for me" every single time gives users nothing to act on
// until they think of something to type - this scans the same mock metrics already shown on the
// Summary tabs (vulnerabilities, restarts, "rebuilt N days ago") for the single most urgent thing
// worth flagging, so opening the palette with an empty query can itself be the useful action.
import type { ImageInfoUI } from '/@/lib/image/ImageInfoUI';
import type { PodInfoUI } from '/@/lib/pod/PodInfoUI';

import { imageKey, podKey } from './layout-types';
import {
  formatVulnBreakdown,
  getImageMockMetrics,
  getImageUpdateInfo,
  getPodMockMetrics,
} from './mock-resource-metrics';

export interface ProactiveInsight {
  title: string;
  subtitle: string;
  iconClass: string;
  iconColorClass: string;
  resourceType: 'image' | 'pod';
  resourceId: string;
  tabTitle: string;
}

/** Picked in priority order - security issues first, then reliability, then "just" a version
 * bump - and only the single most urgent finding across all resources, so the palette surfaces
 * one clear thing to check rather than a wall of warnings. */
export function findProactiveInsight(images: ImageInfoUI[], pods: PodInfoUI[]): ProactiveInsight | undefined {
  let worstImage: { image: ImageInfoUI; id: string; severity: number } | undefined;
  for (const image of images) {
    const id = imageKey(image.id, image.engineId, image.base64RepoTag);
    const metrics = getImageMockMetrics(id);
    const severity = metrics.critical * 10 + metrics.high;
    if (severity > 0 && (!worstImage || severity > worstImage.severity)) {
      worstImage = { image, id, severity };
    }
  }
  if (worstImage) {
    const label = `${worstImage.image.name}:${worstImage.image.tag}`;
    const metrics = getImageMockMetrics(worstImage.id);
    return {
      title: `${label} has ${formatVulnBreakdown(metrics)}`,
      subtitle: 'Agent found this - open it',
      iconClass: 'fas fa-triangle-exclamation',
      iconColorClass: 'text-[var(--pd-status-degraded)]',
      resourceType: 'image',
      resourceId: worstImage.id,
      tabTitle: `${label} · Summary`,
    };
  }

  let flakiestPod: { pod: PodInfoUI; restarts: number } | undefined;
  for (const pod of pods) {
    const { restarts } = getPodMockMetrics(podKey(pod.name, pod.engineId));
    if (restarts >= 2 && (!flakiestPod || restarts > flakiestPod.restarts)) {
      flakiestPod = { pod, restarts };
    }
  }
  if (flakiestPod) {
    return {
      title: `${flakiestPod.pod.name} restarted ${flakiestPod.restarts} times`,
      subtitle: 'Agent found this - open it',
      iconClass: 'fas fa-arrow-rotate-right',
      iconColorClass: 'text-[var(--pd-status-degraded)]',
      resourceType: 'pod',
      resourceId: podKey(flakiestPod.pod.name, flakiestPod.pod.engineId),
      tabTitle: `${flakiestPod.pod.name} · Summary`,
    };
  }

  for (const image of images) {
    const id = imageKey(image.id, image.engineId, image.base64RepoTag);
    const { updateAvailable, daysAgo } = getImageUpdateInfo(id);
    if (updateAvailable) {
      const label = `${image.name}:${image.tag}`;
      return {
        title: `${label} was rebuilt ${daysAgo}d ago`,
        subtitle: 'Agent found a newer version - open it',
        iconClass: 'fas fa-rotate',
        iconColorClass: 'text-[var(--pd-status-running)]',
        resourceType: 'image',
        resourceId: id,
        tabTitle: `${label} · Summary`,
      };
    }
  }

  return undefined;
}
