/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Session autosave/restore, named layouts, and export/import for the Tabs &
// Flexible Layout prototype.
//
// Prototype simplification: uses `localStorage` for both session and named
// layouts. A real implementation should move this to the same main-process
// backed storage other persisted UI state uses, so it survives profile
// migrations and isn't subject to localStorage size limits.
import type { PanelNode } from '@podman-desktop/ui-svelte';

import { ensurePageTab, layoutState } from './layout-store.svelte';
import type { WorkspaceTab } from './layout-types';

const SESSION_KEY = 'podman-desktop.workspace.session.v1';
const NAMED_LAYOUTS_KEY = 'podman-desktop.workspace.named-layouts.v1';

export interface SerializedLayout {
  tree: PanelNode;
  tabs: Record<string, WorkspaceTab>;
  focusedPanelId: string;
}

export interface NamedLayout {
  name: string;
  savedAt: string;
  layout: SerializedLayout;
}

export function serializeCurrentLayout(): SerializedLayout {
  return {
    tree: JSON.parse(JSON.stringify(layoutState.tree)) as PanelNode,
    tabs: JSON.parse(JSON.stringify(layoutState.tabs)) as Record<string, WorkspaceTab>,
    focusedPanelId: layoutState.focusedPanelId,
  };
}

export function applySerializedLayout(serialized: SerializedLayout): void {
  layoutState.tree = serialized.tree;
  layoutState.tabs = serialized.tabs;
  layoutState.focusedPanelId = serialized.focusedPanelId;
  layoutState.maximizedPanelId = undefined;
  // Permanent page tab must always exist in the first section after restore.
  ensurePageTab();
}

// ---- session autosave/restore ----

let restoring = false;
let hasRestoredOnce = false;

export function restoreSession(): void {
  if (hasRestoredOnce) return;
  hasRestoredOnce = true;
  const raw = localStorage.getItem(SESSION_KEY);
  if (!raw) return;
  try {
    restoring = true;
    applySerializedLayout(JSON.parse(raw) as SerializedLayout);
  } catch (err) {
    console.warn('Failed to restore workspace session layout', err);
  } finally {
    restoring = false;
  }
}

function saveSession(): void {
  if (restoring) return;
  try {
    localStorage.setItem(SESSION_KEY, JSON.stringify(serializeCurrentLayout()));
  } catch (err) {
    console.warn('Failed to persist workspace session layout', err);
  }
}

let autosaveInitialized = false;
/** Call once at app startup; sets up the reactive autosave effect (needs an effect root since it runs outside a component). */
export function initSessionAutosave(): void {
  if (autosaveInitialized) return;
  autosaveInitialized = true;
  $effect.root(() => {
    $effect(() => {
      // saveSession() -> serializeCurrentLayout() reads layoutState.tree/tabs, which is
      // enough for Svelte to track them as this effect's dependencies.
      saveSession();
    });
  });
}

// ---- named layouts ----

function readNamedLayouts(): NamedLayout[] {
  const raw = localStorage.getItem(NAMED_LAYOUTS_KEY);
  if (!raw) return [];
  try {
    return JSON.parse(raw) as NamedLayout[];
  } catch {
    return [];
  }
}

function writeNamedLayouts(layouts: NamedLayout[]): void {
  localStorage.setItem(NAMED_LAYOUTS_KEY, JSON.stringify(layouts));
}

export function listNamedLayouts(): NamedLayout[] {
  return readNamedLayouts().toSorted((a, b) => b.savedAt.localeCompare(a.savedAt));
}

export function saveNamedLayout(name: string): void {
  const layouts = readNamedLayouts().filter(l => l.name !== name);
  // eslint-disable-next-line svelte/prefer-svelte-reactivity -- one-off timestamp, not reactive state
  const savedAt = new Date().toISOString();
  layouts.push({ name, savedAt, layout: serializeCurrentLayout() });
  writeNamedLayouts(layouts);
}

export function deleteNamedLayout(name: string): void {
  writeNamedLayouts(readNamedLayouts().filter(l => l.name !== name));
}

export function applyNamedLayout(name: string): void {
  const found = readNamedLayouts().find(l => l.name === name);
  if (found) applySerializedLayout(found.layout);
}

// ---- export / import (.podman-desktop-layout.json) ----

export function exportLayoutAsJson(): string {
  return JSON.stringify(serializeCurrentLayout(), null, 2);
}

export function downloadLayoutExport(): void {
  const blob = new Blob([exportLayoutAsJson()], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = '.podman-desktop-layout.json';
  a.click();
  URL.revokeObjectURL(url);
}

export function importLayoutFromJson(json: string): void {
  const parsed = JSON.parse(json) as SerializedLayout;
  applySerializedLayout(parsed);
}
