/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Podman-Desktop-specific tab shape, layered on top of the resource-agnostic
// `TabDescriptor` from `@podman-desktop/ui-svelte`.

import type { TabDescriptor } from '@podman-desktop/ui-svelte';

export type WorkspaceResourceType = 'container' | 'pod' | 'image' | 'kube-play';

export const CONTAINER_SUB_VIEWS = ['summary', 'logs', 'inspect', 'terminal', 'tty', 'kube'] as const;
export type ContainerSubView = (typeof CONTAINER_SUB_VIEWS)[number];

export const POD_SUB_VIEWS = ['summary', 'logs', 'inspect', 'kube'] as const;
export type PodSubView = (typeof POD_SUB_VIEWS)[number];

export const IMAGE_SUB_VIEWS = ['summary', 'history', 'inspect'] as const;
export type ImageSubView = (typeof IMAGE_SUB_VIEWS)[number];

export type SubView = ContainerSubView | PodSubView | ImageSubView;

/** A workspace tab is a TabDescriptor plus enough identity to resolve + re-resolve its resource and content. */
export interface WorkspaceTab extends TabDescriptor {
  resourceType: WorkspaceResourceType;
  /** Opaque per-resource-type identity, e.g. containerId, `${podName}::${engineId}`, `${imageId}::${engineId}::${base64RepoTag}` */
  resourceId: string;
  subView?: SubView;
}

/** The sub-views offered by the tab strip's "+" menu for a given resource type (see WorkspaceLayout's addTabActions). */
export function subViewsForResourceType(resourceType: WorkspaceResourceType): readonly SubView[] {
  switch (resourceType) {
    case 'container':
      // 'tty' is an auto-detected special case (see ContainerTabContent), not something to offer manually.
      return CONTAINER_SUB_VIEWS.filter(v => v !== 'tty');
    case 'pod':
      return POD_SUB_VIEWS;
    case 'image':
      return IMAGE_SUB_VIEWS;
    default:
      return [];
  }
}

export function subViewLabel(subView: SubView | undefined): string {
  switch (subView) {
    case 'summary':
      return 'Summary';
    case 'logs':
      return 'Logs';
    case 'inspect':
      return 'Inspect';
    case 'terminal':
      return 'Terminal';
    case 'tty':
      return 'Tty';
    case 'kube':
      return 'Kube';
    case 'history':
      return 'History';
    default:
      return '';
  }
}

export function podKey(name: string, engineId: string): string {
  return `${name}::${engineId}`;
}

export function parsePodKey(resourceId: string): { name: string; engineId: string } {
  const [name, engineId] = resourceId.split('::');
  return { name, engineId };
}

export function imageKey(imageId: string, engineId: string, base64RepoTag: string): string {
  return `${imageId}::${engineId}::${base64RepoTag}`;
}

export function parseImageKey(resourceId: string): { imageId: string; engineId: string; base64RepoTag: string } {
  const [imageId, engineId, base64RepoTag] = resourceId.split('::');
  return { imageId, engineId, base64RepoTag };
}

export function tabKey(resourceType: WorkspaceResourceType, resourceId: string, subView: SubView | undefined): string {
  return `${resourceType}:${resourceId}:${subView ?? ''}`;
}
