/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Thin, local-only stand-in for the MCP server described in the vision doc's
// "agent creates a layout" idea. There is no real MCP server here - this just
// demonstrates, end-to-end, what the UI should do once one exists: an
// "agent" opens a couple of tabs on the user's behalf and a banner explains
// what happened and lets the user undo it.
import { get } from 'svelte/store';

import { ContainerUtils } from '/@/lib/container/container-utils';
import { ImageUtils } from '/@/lib/image/image-utils';
import { containersInfos } from '/@/stores/containers';
import { imagesInfos } from '/@/stores/images';
import { podsInfos } from '/@/stores/pods';

import { applySerializedLayout, serializeCurrentLayout, type SerializedLayout } from './layout-persistence.svelte';
import { getTwoPanelSplitTabs, openTab } from './layout-store.svelte';
import type { WorkspaceTab } from './layout-types';
import { imageKey, podKey } from './layout-types';
import {
  formatVulnBreakdown,
  getContainerLogInsight,
  getImageMockMetrics,
  getPodMockMetrics,
  type ImageMockMetrics,
} from './mock-resource-metrics';

export const agentBannerState: { visible: boolean; message: string } = $state({ visible: false, message: '' });

/** Snapshot of the workspace taken right before the most recent agent action added its own
 * tabs, so the banner's "Undo" can put back exactly what was there before - including nothing,
 * if the workspace was empty - instead of wiping the whole workspace (which would also discard
 * any unrelated tabs the user already had open before asking the agent for anything). */
let preActionSnapshot: SerializedLayout | undefined;

export function dismissAgentBanner(): void {
  agentBannerState.visible = false;
}

/** Reverts only the most recent agent action, restoring the exact tree/tabs/focus that existed
 * right before it ran. */
export function undoLastAgentAction(): void {
  if (preActionSnapshot) {
    applySerializedLayout(preActionSnapshot);
    preActionSnapshot = undefined;
  }
  dismissAgentBanner();
}

interface CompareDimension {
  /** Matches the exact stat label shown in the two opened tabs' own "Live stats" card
   * (MockResourceStats.svelte), so the insight always points at something the user can
   * immediately verify by eye on screen instead of citing a number that isn't visible anywhere. */
  label: string;
  aVal: number;
  bVal: number;
  format: (n: number) => string;
  /** If the user's own prompt mentions this dimension by name, lead with it - "restart count
   * check" should produce a restarts insight even if CPU happens to differ more. */
  keywords: RegExp;
  /** Minimum gap before the difference is worth mentioning at all. */
  threshold: number;
}

/** Picks which dimension the banner should lead with: whatever the prompt asked about, if that
 * dimension actually differs by more than its threshold; otherwise the first dimension (in the
 * given priority order) that differs meaningfully. */
function pickCompareDimension(prompt: string, dimensions: CompareDimension[]): CompareDimension | undefined {
  const lower = prompt.toLowerCase();
  const significant = dimensions.filter(d => Math.abs(d.aVal - d.bVal) >= d.threshold);
  return significant.find(d => d.keywords.test(lower)) ?? significant[0];
}

/** Turns the same mock metrics shown in the two pod tabs the agent just opened into a one-line
 * takeaway, instead of leaving the banner saying only that a comparison happened. Mirrors the
 * four stats the "Live stats" card on both tabs already shows (Restarts / Memory / CPU usage /
 * Network I/O) using the same labels and units, and leads with whichever of those the prompt
 * actually asked about - falling back to restarts, then memory, then CPU, then network. */
function buildPodCompareInsight(prompt: string, aName: string, aId: string, bName: string, bId: string): string {
  const a = getPodMockMetrics(aId);
  const b = getPodMockMetrics(bId);

  const dimension = pickCompareDimension(prompt, [
    {
      label: 'Restarts',
      aVal: a.restarts,
      bVal: b.restarts,
      format: (n: number): string => `${n}`,
      keywords: /restart/,
      threshold: 1,
    },
    {
      label: 'Memory',
      aVal: a.memoryMb,
      bVal: b.memoryMb,
      format: (n: number): string => `${n} MB`,
      keywords: /\bmem(ory)?\b/,
      threshold: 40,
    },
    {
      label: 'CPU usage',
      aVal: a.cpuPercent,
      bVal: b.cpuPercent,
      format: (n: number): string => `${n}%`,
      keywords: /\bcpu\b/,
      threshold: 15,
    },
    {
      label: 'Network I/O',
      aVal: a.rxMb,
      bVal: b.rxMb,
      format: (n: number): string => `${n.toFixed(1)} MB/s`,
      keywords: /network|\bi\/o\b|\bio\b/,
      threshold: 10,
    },
  ]);

  if (!dimension)
    return 'Both pods look similar across CPU, memory, restarts, and network - no obvious hotspot between them.';

  const [worseName, worseVal, otherName, otherVal] =
    dimension.aVal > dimension.bVal
      ? [aName, dimension.aVal, bName, dimension.bVal]
      : [bName, dimension.bVal, aName, dimension.aVal];
  const flag = dimension.label === 'Restarts' && worseVal > 0 ? ' - worth checking first' : '';
  return `${dimension.label}: "${worseName}" ${dimension.format(worseVal)} vs "${otherName}" ${dimension.format(otherVal)}${flag}.`;
}

/** Same idea as buildPodCompareInsight, mirroring the four stats the two image tabs' own "Live
 * stats" card shows (Vulnerabilities / Layers / Pulls / Last scanned). */
function buildImageCompareInsight(prompt: string, aName: string, aId: string, bName: string, bId: string): string {
  const a = getImageMockMetrics(aId);
  const b = getImageMockMetrics(bId);
  const severity = (m: ImageMockMetrics): number => m.critical * 10 + m.high;

  const dimension = pickCompareDimension(prompt, [
    {
      label: 'Vulnerabilities',
      aVal: severity(a),
      bVal: severity(b),
      // Unused: vulnerabilities need the full critical/high/medium breakdown (formatVulnBreakdown
      // below), not a single number, so this dimension is rendered by its own branch after
      // pickCompareDimension - severity here only decides whether it's picked at all.
      format: (): string => '',
      keywords: /vulnerab|cve|security/,
      threshold: 1,
    },
    {
      label: 'Layers',
      aVal: a.layers,
      bVal: b.layers,
      format: (n: number): string => `${n}`,
      keywords: /layer/,
      threshold: 1,
    },
    {
      label: 'Pulls',
      aVal: a.pulls,
      bVal: b.pulls,
      format: (n: number): string => n.toLocaleString(),
      keywords: /pull/,
      threshold: 500,
    },
    {
      label: 'Last scanned',
      aVal: a.daysSinceScan,
      bVal: b.daysSinceScan,
      format: (n: number): string => `${n}d ago`,
      keywords: /scan|stale|old/,
      threshold: 2,
    },
  ]);

  if (!dimension) return 'Both images look similarly safe and lean.';

  if (dimension.label === 'Vulnerabilities') {
    const [worse, worseMetrics, other, otherMetrics] =
      severity(a) > severity(b) ? [aName, a, bName, b] : [bName, b, aName, a];
    return `Vulnerabilities: "${worse}" ${formatVulnBreakdown(worseMetrics)} vs "${other}" ${formatVulnBreakdown(otherMetrics)} - start there.`;
  }

  const [worseName, worseVal, otherName, otherVal] =
    dimension.aVal > dimension.bVal
      ? [aName, dimension.aVal, bName, dimension.bVal]
      : [bName, dimension.bVal, aName, dimension.aVal];
  return `${dimension.label}: "${worseName}" ${dimension.format(worseVal)} vs "${otherName}" ${dimension.format(otherVal)}.`;
}

/** Same idea as buildPodCompareInsight/buildImageCompareInsight, but for the container Logs
 * comparison (debugContainersLayout): names what each container's own Logs tab actually shows
 * (via getContainerLogInsight) instead of just announcing that logs were opened for both. */
function buildContainerLogInsight(aName: string, aId: string, bName: string, bId: string): string {
  const a = getContainerLogInsight(aId);
  const b = getContainerLogInsight(bId);

  if (a.severity === b.severity) {
    return `"${aName}" ${a.detail}; "${bName}" ${b.detail}.`;
  }

  const [worseName, worse, otherName, other] = a.severity > b.severity ? [aName, a, bName, b] : [bName, b, aName, a];
  return `"${worseName}" ${worse.detail}, while "${otherName}" ${other.detail} - start with "${worseName}".`;
}

// ---- passive split-view insight (no agent action involved) ----
//
// The banner above only appears right after an explicit agent action. But a side-by-side view
// of two pods or two images is the same "comparing two things" moment whether an agent opened
// it or the user split/dragged tabs there themselves - so surface the same kind of insight for
// *any* plain two-way split, not just agent-created ones. See SplitInsightBanner.svelte.

function tabDisplayName(tab: WorkspaceTab): string {
  // Tab titles follow "<name> · <SubView>" (see InspectCard.svelte) - strip the suffix so the
  // insight reads naturally, e.g. "demo-pod" instead of "demo-pod · Summary".
  return tab.title.split(' · ')[0];
}

function splitPairKey(a: WorkspaceTab, b: WorkspaceTab): string {
  return [a.id, b.id].toSorted().join('|');
}

let dismissedSplitInsightKey: string | undefined = $state(undefined);

export interface SplitComparisonInsight {
  key: string;
  message: string;
}

/** Recomputes whenever the two-panel split (see getTwoPanelSplitTabs) or its tabs change - stays
 * undefined unless both panels show exactly one tab each, of the same comparable resource type
 * (pod or image), for two different resources, and the user hasn't already dismissed this exact
 * pair. Not exported directly: Svelte doesn't allow exporting a `$derived` binding from a module,
 * only a function that reads its current value (see getSplitComparisonInsight below). */
const splitComparisonInsight: SplitComparisonInsight | undefined = $derived.by(() => {
  const pair = getTwoPanelSplitTabs();
  if (!pair) return undefined;
  const [a, b] = pair;
  if (a.resourceType !== b.resourceType || a.resourceId === b.resourceId) return undefined;

  const key = splitPairKey(a, b);
  if (key === dismissedSplitInsightKey) return undefined;

  const aName = tabDisplayName(a);
  const bName = tabDisplayName(b);
  let comparison: string | undefined;
  if (a.resourceType === 'pod') {
    comparison = buildPodCompareInsight('', aName, a.resourceId, bName, b.resourceId);
  } else if (a.resourceType === 'image') {
    comparison = buildImageCompareInsight('', aName, a.resourceId, bName, b.resourceId);
  }
  if (!comparison) return undefined;

  return { key, message: `Comparing "${aName}" and "${bName}": ${comparison}` };
});

/** Called from a component's own `$derived(getSplitComparisonInsight())` so it stays reactive
 * across the module boundary. */
export function getSplitComparisonInsight(): SplitComparisonInsight | undefined {
  return splitComparisonInsight;
}

export function dismissSplitInsight(): void {
  if (splitComparisonInsight) dismissedSplitInsightKey = splitComparisonInsight.key;
}

function debugContainersLayout(promptLabel?: string): void {
  const containerUtils = new ContainerUtils();
  const containers = get(containersInfos).map(c => containerUtils.getContainerInfoUI(c));
  const running = containers.filter(c => c.state === 'RUNNING');
  const pick = (running.length >= 2 ? running : containers).slice(0, 2);

  if (pick.length === 0) {
    // Nothing was opened this time, so clear any snapshot left over from an earlier, successful
    // agent action - otherwise "Undo" on *this* no-op banner would revert that unrelated action.
    preActionSnapshot = undefined;
    agentBannerState.visible = true;
    agentBannerState.message = 'No containers are available for the agent to inspect right now.';
    return;
  }

  preActionSnapshot = serializeCurrentLayout();
  openTab(
    {
      resourceType: 'container',
      resourceId: pick[0].id,
      subView: 'logs',
      title: `${pick[0].name} · Logs`,
      agentCreated: true,
    },
    'newTab',
  );

  const prefix = promptLabel ? `Based on "${promptLabel}", an agent` : 'An agent';
  if (pick[1]) {
    openTab(
      {
        resourceType: 'container',
        resourceId: pick[1].id,
        subView: 'logs',
        title: `${pick[1].name} · Logs`,
        agentCreated: true,
      },
      'splitRight',
    );
    const insight = buildContainerLogInsight(pick[0].name, pick[0].id, pick[1].name, pick[1].id);
    agentBannerState.message = `${prefix} opened logs for "${pick[0].name}" and "${pick[1].name}" side by side. ${insight}`;
  } else {
    openTab(
      {
        resourceType: 'container',
        resourceId: pick[0].id,
        subView: 'terminal',
        title: `${pick[0].name} · Terminal`,
        agentCreated: true,
      },
      'splitDown',
    );
    const { detail } = getContainerLogInsight(pick[0].id);
    agentBannerState.message = `${prefix} opened logs and a terminal for "${pick[0].name}" - its logs ${detail}.`;
  }
  agentBannerState.visible = true;
}

export function simulateAgentDebugLayout(): void {
  debugContainersLayout();
}

/** Prototype stand-in for sending a free-text prompt to a real MCP-backed agent (see the
 * "+" tab palette's agent text field): a few keyword heuristics decide which resource type
 * to act on, since there's no real model behind this yet, but the end-to-end flow - typed
 * request in, tabs + explanatory banner out - is the same shape a real integration would use. */
export function runAgentPrompt(prompt: string): void {
  const trimmed = prompt.trim();
  if (!trimmed) {
    debugContainersLayout();
    return;
  }
  const lower = trimmed.toLowerCase();

  if (lower.includes('pod')) {
    const pods = get(podsInfos);
    if (pods.length === 0) {
      preActionSnapshot = undefined;
      agentBannerState.visible = true;
      agentBannerState.message = `No pods are available for the agent to act on "${trimmed}".`;
      return;
    }

    preActionSnapshot = serializeCurrentLayout();
    const pick = pods.slice(0, 2);
    openTab(
      {
        resourceType: 'pod',
        resourceId: podKey(pick[0].name, pick[0].engineId),
        subView: 'summary',
        title: `${pick[0].name} · Summary`,
        agentCreated: true,
      },
      'newTab',
    );
    if (pick[1]) {
      openTab(
        {
          resourceType: 'pod',
          resourceId: podKey(pick[1].name, pick[1].engineId),
          subView: 'summary',
          title: `${pick[1].name} · Summary`,
          agentCreated: true,
        },
        'splitRight',
      );
      const insight = buildPodCompareInsight(
        trimmed,
        pick[0].name,
        podKey(pick[0].name, pick[0].engineId),
        pick[1].name,
        podKey(pick[1].name, pick[1].engineId),
      );
      agentBannerState.message = `An agent opened "${pick[0].name}" and "${pick[1].name}" side by side, based on "${trimmed}". ${insight}`;
    } else {
      openTab(
        {
          resourceType: 'pod',
          resourceId: podKey(pick[0].name, pick[0].engineId),
          subView: 'logs',
          title: `${pick[0].name} · Logs`,
          agentCreated: true,
        },
        'splitRight',
      );
      agentBannerState.message = `Based on "${trimmed}", an agent opened "${pick[0].name}"'s summary and logs side by side.`;
    }
    agentBannerState.visible = true;
    return;
  }

  if (lower.includes('image')) {
    const imageUtils = new ImageUtils();
    const containers = get(containersInfos);
    const allImages = get(imagesInfos);
    const images = allImages
      .flatMap(i => imageUtils.getImagesInfoUI(i, containers, undefined, [], allImages))
      .filter((i): i is NonNullable<typeof i> => !!i);
    const pick = images.slice(0, 2);

    if (pick.length === 0) {
      preActionSnapshot = undefined;
      agentBannerState.visible = true;
      agentBannerState.message = `No images are available for the agent to act on "${trimmed}".`;
      return;
    }

    preActionSnapshot = serializeCurrentLayout();
    openTab(
      {
        resourceType: 'image',
        resourceId: imageKey(pick[0].id, pick[0].engineId, pick[0].base64RepoTag),
        subView: 'summary',
        title: `${pick[0].name}:${pick[0].tag} · Summary`,
        agentCreated: true,
      },
      'newTab',
    );
    if (pick[1]) {
      openTab(
        {
          resourceType: 'image',
          resourceId: imageKey(pick[1].id, pick[1].engineId, pick[1].base64RepoTag),
          subView: 'summary',
          title: `${pick[1].name}:${pick[1].tag} · Summary`,
          agentCreated: true,
        },
        'splitRight',
      );
      const insight = buildImageCompareInsight(
        trimmed,
        `${pick[0].name}:${pick[0].tag}`,
        imageKey(pick[0].id, pick[0].engineId, pick[0].base64RepoTag),
        `${pick[1].name}:${pick[1].tag}`,
        imageKey(pick[1].id, pick[1].engineId, pick[1].base64RepoTag),
      );
      agentBannerState.message = `An agent opened "${pick[0].name}:${pick[0].tag}" and "${pick[1].name}:${pick[1].tag}" side by side, based on "${trimmed}". ${insight}`;
    } else {
      agentBannerState.message = `Based on "${trimmed}", an agent opened "${pick[0].name}:${pick[0].tag}".`;
    }
    agentBannerState.visible = true;
    return;
  }

  debugContainersLayout(trimmed);
}
