/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Thin, local-only stand-in for the MCP server described in the vision doc's
// "agent creates a layout" idea. There is no real MCP server here - this just
// demonstrates, end-to-end, what the UI should do once one exists: an
// "agent" opens a couple of tabs on the user's behalf and a banner explains
// what happened and lets the user undo it.
import { get } from 'svelte/store';

import { ContainerUtils } from '/@/lib/container/container-utils';
import { ImageUtils } from '/@/lib/image/image-utils';
import { containersInfos } from '/@/stores/containers';
import { imagesInfos } from '/@/stores/images';
import { podsInfos } from '/@/stores/pods';

import { openTab, resetLayout } from './layout-store.svelte';
import { imageKey, podKey } from './layout-types';
import { formatVulnBreakdown, getImageMockMetrics, getPodMockMetrics } from './mock-resource-metrics';

export const agentBannerState: { visible: boolean; message: string } = $state({ visible: false, message: '' });

export function dismissAgentBanner(): void {
  agentBannerState.visible = false;
}

/** Turns the same mock metrics shown in the two pod tabs the agent just opened into a one-line
 * takeaway, instead of leaving the banner saying only that a comparison happened. Checks
 * restarts before memory before CPU - a crash-looping pod is worth flagging over a merely
 * busier one. */
function buildPodCompareInsight(aName: string, aId: string, bName: string, bId: string): string {
  const a = getPodMockMetrics(aId);
  const b = getPodMockMetrics(bId);

  if (a.restarts !== b.restarts) {
    const [worse, worseCount, other, otherCount] =
      a.restarts > b.restarts ? [aName, a.restarts, bName, b.restarts] : [bName, b.restarts, aName, a.restarts];
    return `"${worse}" has restarted ${worseCount} time${worseCount === 1 ? '' : 's'} (vs ${otherCount} for "${other}") - worth checking first.`;
  }
  if (Math.abs(a.memoryMb - b.memoryMb) > 40) {
    const [heavier, heavyMb, lighter, lightMb] =
      a.memoryMb > b.memoryMb ? [aName, a.memoryMb, bName, b.memoryMb] : [bName, b.memoryMb, aName, a.memoryMb];
    return `"${heavier}" is using more memory (${heavyMb} MB vs ${lightMb} MB) than "${lighter}".`;
  }
  if (Math.abs(a.cpuPercent - b.cpuPercent) > 15) {
    const [hotter, hotPct, cooler, coolPct] =
      a.cpuPercent > b.cpuPercent
        ? [aName, a.cpuPercent, bName, b.cpuPercent]
        : [bName, b.cpuPercent, aName, a.cpuPercent];
    return `"${hotter}" is using more CPU (${hotPct}% vs ${coolPct}%) than "${cooler}".`;
  }
  return 'Both pods look similar - no obvious hotspot between them.';
}

/** Same idea as buildPodCompareInsight, for the two image tabs the agent opened: leads with
 * whichever image has the more severe vulnerabilities (critical counts twice as much as high
 * in the severity score), falling back to layer count when both are equally clean. */
function buildImageCompareInsight(aName: string, aId: string, bName: string, bId: string): string {
  const a = getImageMockMetrics(aId);
  const b = getImageMockMetrics(bId);
  const severity = (m: typeof a): number => m.critical * 10 + m.high;

  if (severity(a) !== severity(b)) {
    const [worse, worseMetrics, other, otherMetrics] =
      severity(a) > severity(b) ? [aName, a, bName, b] : [bName, b, aName, a];
    return `"${worse}" has more vulnerabilities (${formatVulnBreakdown(worseMetrics)}) than "${other}" (${formatVulnBreakdown(otherMetrics)}) - start there.`;
  }
  if (a.layers !== b.layers) {
    const [bulkier, bulkierLayers, leaner, leanerLayers] =
      a.layers > b.layers ? [aName, a.layers, bName, b.layers] : [bName, b.layers, aName, a.layers];
    return `"${bulkier}" has more layers (${bulkierLayers} vs ${leanerLayers}) than "${leaner}".`;
  }
  return 'Both images look similarly safe and lean.';
}

function debugContainersLayout(promptLabel?: string): void {
  const containerUtils = new ContainerUtils();
  const containers = get(containersInfos).map(c => containerUtils.getContainerInfoUI(c));
  const running = containers.filter(c => c.state === 'RUNNING');
  const pick = (running.length >= 2 ? running : containers).slice(0, 2);

  if (pick.length === 0) {
    agentBannerState.visible = true;
    agentBannerState.message = 'No containers are available for the agent to inspect right now.';
    return;
  }

  resetLayout();
  openTab(
    {
      resourceType: 'container',
      resourceId: pick[0].id,
      subView: 'logs',
      title: `${pick[0].name} · Logs`,
      agentCreated: true,
    },
    'newTab',
  );

  const prefix = promptLabel ? `Based on "${promptLabel}", an agent` : 'An agent';
  if (pick[1]) {
    openTab(
      {
        resourceType: 'container',
        resourceId: pick[1].id,
        subView: 'logs',
        title: `${pick[1].name} · Logs`,
        agentCreated: true,
      },
      'splitRight',
    );
    agentBannerState.message = `${prefix} opened logs for "${pick[0].name}" and "${pick[1].name}" side by side to help you debug.`;
  } else {
    openTab(
      {
        resourceType: 'container',
        resourceId: pick[0].id,
        subView: 'terminal',
        title: `${pick[0].name} · Terminal`,
        agentCreated: true,
      },
      'splitDown',
    );
    agentBannerState.message = `${prefix} opened logs and a terminal for "${pick[0].name}" to help you debug.`;
  }
  agentBannerState.visible = true;
}

export function simulateAgentDebugLayout(): void {
  debugContainersLayout();
}

/** Prototype stand-in for sending a free-text prompt to a real MCP-backed agent (see the
 * "+" tab palette's agent text field): a few keyword heuristics decide which resource type
 * to act on, since there's no real model behind this yet, but the end-to-end flow - typed
 * request in, tabs + explanatory banner out - is the same shape a real integration would use. */
export function runAgentPrompt(prompt: string): void {
  const trimmed = prompt.trim();
  if (!trimmed) {
    debugContainersLayout();
    return;
  }
  const lower = trimmed.toLowerCase();

  if (lower.includes('pod')) {
    const pods = get(podsInfos);
    if (pods.length === 0) {
      agentBannerState.visible = true;
      agentBannerState.message = `No pods are available for the agent to act on "${trimmed}".`;
      return;
    }

    resetLayout();
    const pick = pods.slice(0, 2);
    openTab(
      {
        resourceType: 'pod',
        resourceId: podKey(pick[0].name, pick[0].engineId),
        subView: 'summary',
        title: `${pick[0].name} · Summary`,
        agentCreated: true,
      },
      'newTab',
    );
    if (pick[1]) {
      openTab(
        {
          resourceType: 'pod',
          resourceId: podKey(pick[1].name, pick[1].engineId),
          subView: 'summary',
          title: `${pick[1].name} · Summary`,
          agentCreated: true,
        },
        'splitRight',
      );
      const insight = buildPodCompareInsight(
        pick[0].name,
        podKey(pick[0].name, pick[0].engineId),
        pick[1].name,
        podKey(pick[1].name, pick[1].engineId),
      );
      agentBannerState.message = `Based on "${trimmed}", an agent opened "${pick[0].name}" and "${pick[1].name}" side by side to compare. ${insight}`;
    } else {
      openTab(
        {
          resourceType: 'pod',
          resourceId: podKey(pick[0].name, pick[0].engineId),
          subView: 'logs',
          title: `${pick[0].name} · Logs`,
          agentCreated: true,
        },
        'splitRight',
      );
      agentBannerState.message = `Based on "${trimmed}", an agent opened "${pick[0].name}"'s summary and logs side by side.`;
    }
    agentBannerState.visible = true;
    return;
  }

  if (lower.includes('image')) {
    const imageUtils = new ImageUtils();
    const containers = get(containersInfos);
    const allImages = get(imagesInfos);
    const images = allImages
      .flatMap(i => imageUtils.getImagesInfoUI(i, containers, undefined, [], allImages))
      .filter((i): i is NonNullable<typeof i> => !!i);
    const pick = images.slice(0, 2);

    if (pick.length === 0) {
      agentBannerState.visible = true;
      agentBannerState.message = `No images are available for the agent to act on "${trimmed}".`;
      return;
    }

    resetLayout();
    openTab(
      {
        resourceType: 'image',
        resourceId: imageKey(pick[0].id, pick[0].engineId, pick[0].base64RepoTag),
        subView: 'summary',
        title: `${pick[0].name}:${pick[0].tag} · Summary`,
        agentCreated: true,
      },
      'newTab',
    );
    if (pick[1]) {
      openTab(
        {
          resourceType: 'image',
          resourceId: imageKey(pick[1].id, pick[1].engineId, pick[1].base64RepoTag),
          subView: 'summary',
          title: `${pick[1].name}:${pick[1].tag} · Summary`,
          agentCreated: true,
        },
        'splitRight',
      );
      const insight = buildImageCompareInsight(
        `${pick[0].name}:${pick[0].tag}`,
        imageKey(pick[0].id, pick[0].engineId, pick[0].base64RepoTag),
        `${pick[1].name}:${pick[1].tag}`,
        imageKey(pick[1].id, pick[1].engineId, pick[1].base64RepoTag),
      );
      agentBannerState.message = `Based on "${trimmed}", an agent opened "${pick[0].name}:${pick[0].tag}" and "${pick[1].name}:${pick[1].tag}" side by side to compare. ${insight}`;
    } else {
      agentBannerState.message = `Based on "${trimmed}", an agent opened "${pick[0].name}:${pick[0].tag}".`;
    }
    agentBannerState.visible = true;
    return;
  }

  debugContainersLayout(trimmed);
}
