/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Framework-agnostic version of the deterministic mock metrics MockResourceStats.svelte
// renders as each pod/image tab's "Live stats" card. Pulled out so the agent-demo "compare"
// flow (layout-agent-demo.svelte.ts) can build its insight out of the *same* numbers the user
// is about to see in the two tabs it opens, instead of a second, independently-seeded set of
// stats that could disagree with what's on screen.

function hash(input: string): number {
  let h = 0;
  for (let i = 0; i < input.length; i++) {
    // Unsigned shift (>>>): h can exceed 0x7FFFFFFF, and a signed >> would sign-extend that
    // into a negative number, producing nonsense like "-184 MB" of memory.
    h = (h * 31 + input.charCodeAt(i)) >>> 0;
  }
  return h;
}

export interface PodMockMetrics {
  cpuPercent: number;
  memoryMb: number;
  restarts: number;
  rxMb: number;
}

export interface ImageVulnCounts {
  critical: number;
  high: number;
  medium: number;
}

export interface ImageMockMetrics extends ImageVulnCounts {
  pulls: number;
  layers: number;
  daysSinceScan: number;
}

export function getPodMockMetrics(resourceId: string): PodMockMetrics {
  const h = hash(`pod:${resourceId}`);
  return {
    cpuPercent: (h % 55) + 3,
    memoryMb: ((h >>> 3) % 420) + 48,
    restarts: (h >>> 7) % 4,
    rxMb: (((h >>> 11) % 480) + 5) / 10,
  };
}

export function getImageMockMetrics(resourceId: string): ImageMockMetrics {
  const h = hash(`image:${resourceId}`);
  return {
    critical: (h >>> 2) % 3,
    high: (h >>> 5) % 6,
    medium: (h >>> 9) % 14,
    pulls: ((h >>> 13) % 9000) + 120,
    layers: ((h >>> 17) % 11) + 3,
    daysSinceScan: (h % 6) + 1,
  };
}

export interface ImageUpdateInfo {
  updateAvailable: boolean;
  /** Only meaningful when `updateAvailable` is true - how long ago the newer build landed. */
  daysAgo: number;
}

/** Separate hash namespace (`update:`, not `image:`) from getImageMockMetrics - otherwise reusing
 * the same hash for two unrelated booleans/counts would make them suspiciously correlated (e.g.
 * every image with 0 critical vulns would also always show "no update available"). Roughly 1 in 3
 * images report an update, so the "+" palette's proactive insight (see layout-proactive-insight.ts)
 * has something to surface without every single image claiming to be outdated. */
export function getImageUpdateInfo(resourceId: string): ImageUpdateInfo {
  const h = hash(`update:${resourceId}`);
  return {
    updateAvailable: h % 3 === 0,
    daysAgo: ((h >>> 4) % 14) + 1,
  };
}

export interface ContainerLogInsight {
  /** Higher = more worth checking first. Ties are broken by log order (first container wins),
   * same as the pod/image compare dimensions. */
  severity: number;
  /** What actually shows up in that container's Logs tab - specific enough that clicking through
   * to the real Logs tab should read as confirming this, not contradicting it. */
  detail: string;
}

/** Small deterministic catalog instead of raw random text: every entry describes something a
 * real container log plausibly shows, so the debug-duo/"Simulate Agent" comparison
 * (buildContainerLogInsight in layout-agent-demo.svelte.ts) can name what's actually different
 * between two containers' logs instead of just saying logs were opened for both. */
const CONTAINER_LOG_FINDINGS: ContainerLogInsight[] = [
  { severity: 0, detail: 'started up cleanly with no errors or warnings' },
  { severity: 1, detail: 'logs a few deprecation warnings but no errors' },
  { severity: 1, detail: 'logs several slow query warnings (>1s)' },
  { severity: 2, detail: 'shows repeated "connection refused" errors reaching a dependency' },
  { severity: 2, detail: 'shows repeated request timeouts' },
  { severity: 3, detail: 'shows an out-of-memory warning shortly before exiting' },
  { severity: 3, detail: 'shows repeated crashes and restarts' },
];

export function getContainerLogInsight(resourceId: string): ContainerLogInsight {
  const h = hash(`logs:${resourceId}`);
  return CONTAINER_LOG_FINDINGS[h % CONTAINER_LOG_FINDINGS.length];
}

/** Drops zero counts instead of printing "1 critical, 0 high, 0 medium". */
export function formatVulnBreakdown({ critical, high, medium }: ImageVulnCounts, noneLabel = 'None found'): string {
  const parts = [
    critical > 0 ? `${critical} critical` : undefined,
    high > 0 ? `${high} high` : undefined,
    medium > 0 ? `${medium} medium` : undefined,
  ].filter((part): part is string => !!part);
  return parts.length > 0 ? parts.join(', ') : noneLabel;
}
