/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Tracks which list/dashboard page the permanent first-section tab should show
// (Containers, Pods, …). The tab itself lives in layout-store (ensurePageTab).
import { router } from 'tinro';

import { currentPage } from '/@/stores/breadcrumb';

export const PAGE_TAB_ID = 'app-page-tab';

/** Last non-workspace, non-detail route — page tab content + sidebar return target. */
let lastAppPageUrl = $state('/');
let lastAppPageName = $state('Dashboard Page');

let currentRouteUrl = $state('/');

/** Legacy `/containers/:id` (and peers) that only bridge into workspace tabs. */
function isResourceDetailBridge(url: string): boolean {
  const path = url.split('?')[0] || '/';
  if (/^\/containers\/.+/.test(path)) return true;
  if (/^\/pods\/podman\//.test(path)) return true;
  if (/^\/compose\/details\//.test(path)) return true;
  if (/^\/volumes\/[^/]+\/[^/]+/.test(path)) return true;
  if (/^\/networks\/[^/]+\/[^/]+/.test(path)) return true;
  if (/^\/secrets\/[^/]+\/[^/]+/.test(path)) return true;
  if (/^\/images\/[^/]+\/[^/]+\/[^/]+/.test(path)) return true;
  return false;
}

function listRootForDetail(url: string): { url: string; name: string } {
  const path = url.split('?')[0] || '/';
  if (path.startsWith('/containers')) return { url: '/containers', name: 'Containers' };
  if (path.startsWith('/pods')) return { url: '/pods', name: 'Pods' };
  if (path.startsWith('/images')) return { url: '/images', name: 'Images' };
  if (path.startsWith('/volumes')) return { url: '/volumes', name: 'Volumes' };
  if (path.startsWith('/networks')) return { url: '/networks', name: 'Networks' };
  if (path.startsWith('/secrets')) return { url: '/secrets', name: 'Secrets' };
  if (path.startsWith('/compose')) return { url: '/pods', name: 'Pods' };
  return { url: '/containers', name: 'Containers' };
}

function shouldTrackAsPageTab(url: string): boolean {
  const path = url.split('?')[0] || '/';
  if (path.startsWith('/workspace') || path.startsWith('/preferences')) return false;
  if (isResourceDetailBridge(path)) return false;
  return true;
}

export function rememberAppPage(url: string, name?: string): void {
  const path = url.split('?')[0] || '/';
  if (!shouldTrackAsPageTab(path)) return;
  lastAppPageUrl = path;
  if (name) lastAppPageName = name;
}

router.subscribe(route => {
  currentRouteUrl = route.url;
  if (route.url.startsWith('/workspace') || route.url.startsWith('/preferences')) return;
  if (isResourceDetailBridge(route.url)) return;
  if (shouldTrackAsPageTab(route.url)) {
    rememberAppPage(route.url);
  }
});

currentPage.subscribe(page => {
  if (!page?.name) return;
  if (!shouldTrackAsPageTab(currentRouteUrl)) return;
  lastAppPageName = page.name;
  if (page.path && shouldTrackAsPageTab(page.path)) {
    lastAppPageUrl = page.path.split('?')[0] || lastAppPageUrl;
  }
});

export function isPageTabId(tabId: string | undefined): boolean {
  return tabId === PAGE_TAB_ID;
}

export function getPageTabTitle(): string {
  return lastAppPageName;
}

/** Descriptor for callers that still build a flat tab strip (legacy GlobalTabBar). */
export function getPageTab(): {
  id: string;
  key: string;
  title: string;
  permanent: true;
  pinned: true;
  iconClass: string;
} {
  return {
    id: PAGE_TAB_ID,
    key: PAGE_TAB_ID,
    title: lastAppPageName,
    permanent: true,
    pinned: true,
    iconClass: 'fas fa-house',
  };
}

export function isPageTabSelected(): boolean {
  return false;
}

export function getLastAppPageUrl(): string {
  const url = lastAppPageUrl || '/';
  if (isResourceDetailBridge(url)) return listRootForDetail(url).url;
  return url;
}

/** Navigate to the list/dashboard route for the permanent page tab (if needed). */
export function goToAppPageRoute(): void {
  let target = getLastAppPageUrl();
  if (isResourceDetailBridge(target)) {
    const root = listRootForDetail(target);
    target = root.url;
    lastAppPageUrl = root.url;
    lastAppPageName = root.name;
  }
  if (currentRouteUrl.split('?')[0] !== target) {
    router.goto(target);
  }
}

/** After opening a resource tab, land on the list shell (keeps page tab + nav). */
export function gotoListShell(): void {
  goToAppPageRoute();
}

/** @deprecated use goToAppPageRoute + layout activatePageTab */
export function selectPageTab(): void {
  goToAppPageRoute();
}

export function markResourceTabActive(): void {
  // kept for call sites; page vs resource selection is leaf.activeTabId now
}
