<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Same Environment control used in production list tables (provider connection label).
import ContainerEngineEnvironmentColumn from '/@/lib/table/columns/ContainerEngineEnvironmentColumn.svelte';

interface Props {
  engineId: string;
}

let { engineId }: Props = $props();
</script>

<div class="flex flex-col min-w-0 gap-0.5">
  <span class="text-xs text-[var(--pd-content-text)] opacity-60">Environment</span>
  <div class="min-w-0">
    <ContainerEngineEnvironmentColumn object={{ engineId }} />
  </div>
</div>
