<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/-->
<script lang="ts">
// Generated by Cursor
// Summary-tab Inspect card: always shows raw JSON; "Open in new tab" pops the
// dedicated Inspect sub-view beside this Summary tab.
import type { Snippet } from 'svelte';

import { findLeafContainingTab, layoutState, openTab } from '/@/stores/layout/layout-store.svelte';
import type { WorkspaceResourceType } from '/@/stores/layout/layout-types';

import SummaryCard from './SummaryCard.svelte';

interface Props {
  resourceType: WorkspaceResourceType;
  resourceId: string;
  /** Bare resource name (no " · Summary" suffix) for the Inspect tab title. */
  resourceTitle: string;
  /** Summary tab id — Inspect opens in the same panel. */
  tabId: string;
  children: Snippet;
}

let { resourceType, resourceId, resourceTitle, tabId, children }: Props = $props();

function openFullInspect(): void {
  const targetPanelId = findLeafContainingTab(layoutState.tree, tabId)?.id;
  openTab(
    { resourceType, resourceId, subView: 'inspect', title: `${resourceTitle} · Inspect` },
    'newTab',
    targetPanelId,
  );
}
</script>

<SummaryCard title="Inspect" icon="fas fa-code">
  {#snippet trailing()}
    <button type="button" class="hover:underline text-[var(--pd-link)]" onclick={openFullInspect}>
      Open in new tab <i class="fas fa-arrow-up-right-from-square text-[10px]" aria-hidden="true"></i>
    </button>
  {/snippet}
  <div class="h-[420px] border-t border-[var(--pd-content-divider)]">
    {@render children()}
  </div>
</SummaryCard>
