<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/-->
<script lang="ts">
// Generated by Cursor
// The redesigned Summary tabs (see PodSummaryTabContent, ImageSummaryTabContent,
// ContainerSummaryTabContent) only surface a curated subset of each resource's fields - the
// legacy Inspect sub-view's full raw JSON (env vars, mounts, network settings, engine-specific
// config...) isn't shown anywhere on Summary, and it's easy to forget it still exists once
// Summary is what everyone sees by default. This closes that gap without dumping a giant JSON
// blob into every Summary tab: collapsed by default, expands the same MonacoEditor-based view
// as the dedicated Inspect tab in place, or "Open in new tab" jumps to that full tab directly.
import type { Snippet } from 'svelte';

import { findLeafContainingTab, layoutState, openTab } from '/@/stores/layout/layout-store.svelte';
import type { WorkspaceResourceType } from '/@/stores/layout/layout-types';

import SummaryCard from './SummaryCard.svelte';

interface Props {
  resourceType: WorkspaceResourceType;
  resourceId: string;
  /** Bare resource name (no " · Summary" suffix) so the opened tab's title matches every
   * other tab's "<name> · <SubView>" convention. */
  resourceTitle: string;
  /** Id of the Summary tab this card is rendered inside - used so the new Inspect tab opens
   * next to it, in whichever panel that actually is. Without this, `openTab`'s default target
   * (the last globally-focused panel) can silently drop the new tab into a *different* panel
   * than the one the user is looking at in a split view - which reads as "the button did
   * nothing" since nothing visibly changes in front of them. */
  tabId: string;
  /** The resource-specific `*DetailsInspect` component (Container/Pod/Image) - only mounted
   * once expanded, so its onMount inspect fetch doesn't fire for every Summary tab a user
   * happens to open. */
  children: Snippet;
}

let { resourceType, resourceId, resourceTitle, tabId, children }: Props = $props();

let expanded = $state(false);

function openFullInspect(): void {
  const targetPanelId = findLeafContainingTab(layoutState.tree, tabId)?.id;
  openTab(
    { resourceType, resourceId, subView: 'inspect', title: `${resourceTitle} · Inspect` },
    'newTab',
    targetPanelId,
  );
}
</script>

<SummaryCard title="Inspect" icon="fas fa-code">
  {#snippet trailing()}
    <span class="inline-flex items-center gap-3">
      <button
        type="button"
        class="hover:underline text-[var(--pd-link)]"
        onclick={(): boolean => (expanded = !expanded)}>
        {expanded ? 'Hide raw JSON' : 'Show raw JSON'}
      </button>
      <button type="button" class="hover:underline text-[var(--pd-link)]" onclick={openFullInspect}>
        Open in new tab <i class="fas fa-arrow-up-right-from-square text-[10px]" aria-hidden="true"></i>
      </button>
    </span>
  {/snippet}
  {#if expanded}
    <div class="h-[420px] border-t border-[var(--pd-content-divider)]">
      {@render children()}
    </div>
  {:else}
    <div class="px-4 pb-3 text-sm text-[var(--pd-content-text)] opacity-60">
      Full raw inspect output for this resource - env vars, mounts, network settings, and
      everything else not summarized above.
    </div>
  {/if}
</SummaryCard>
