<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// A consistent "who/what am I looking at" header for the Pod/Container/Image summary tabs -
// name, live status, and the id/created/age metadata that used to be buried as plain rows
// inside a dense details table. Pulling it out into one glanceable header (with the same
// StatusIcon used everywhere else in the app, so the color coding matches list rows) is most
// of what makes the redesigned tabs easier to read than the old table.
import type { IconDefinition } from '@fortawesome/free-solid-svg-icons';
import { faCheck, faCopy } from '@fortawesome/free-solid-svg-icons';
import { StatusIcon } from '@podman-desktop/ui-svelte';
import { Icon } from '@podman-desktop/ui-svelte/icons';
import type { Component } from 'svelte';

interface Props {
  name: string;
  /** Upper-case status token understood by StatusIcon (RUNNING/DEGRADED/...) - omit for
   * resources with no running/stopped concept of their own (e.g. images). */
  status?: string;
  /** Human-friendly, lower-case label shown next to the status dot - falls back to `status`. */
  statusLabel?: string;
  icon: IconDefinition | Component | string;
  id: string;
  created?: Date;
  age?: string;
}

let { name, status, statusLabel, icon, id, created, age }: Props = $props();

let justCopied = $state(false);
let copyTimeout: ReturnType<typeof setTimeout> | undefined;

async function copyId(): Promise<void> {
  await window.clipboardWriteText(id);
  justCopied = true;
  clearTimeout(copyTimeout);
  copyTimeout = setTimeout(() => (justCopied = false), 1500);
}
</script>

<div class="flex items-start gap-3">
  {#if status}
    <div class="mt-1 shrink-0">
      <StatusIcon {icon} {status} size={18} />
    </div>
  {/if}
  <div class="flex flex-col min-w-0 gap-1">
    <div class="flex items-center gap-2 flex-wrap">
      <h1 class="text-lg font-semibold text-[var(--pd-content-header)] truncate">{name}</h1>
      {#if statusLabel ?? status}
        <span
          class="text-[11px] leading-none px-2 py-1 rounded-full border border-[var(--pd-content-divider)] text-[var(--pd-content-text)] opacity-80 lowercase whitespace-nowrap">
          {statusLabel ?? status}
        </span>
      {/if}
    </div>
    <div class="flex items-center gap-3 flex-wrap text-xs text-[var(--pd-content-text)] opacity-60">
      <button
        type="button"
        class="flex items-center gap-1 font-mono hover:opacity-100"
        title="Copy full ID: {id}"
        aria-label="Copy full ID to clipboard"
        onclick={copyId}>
        {id.substring(0, 12)}
        <Icon icon={justCopied ? faCheck : faCopy} class="w-2.5 text-[10px]" />
      </button>
      {#if created}
        <span>Created {created.toLocaleString()}</span>
      {/if}
      {#if age}
        <span>{age} old</span>
      {/if}
    </div>
  </div>
</div>
