<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// A small bordered card with an uppercase title row - the same visual language
// MockResourceStats already established for the "Live stats" card - reused across the
// redesigned Pod/Container/Image summary tabs so all the info on a tab reads as one
// consistent set of sections instead of a single dense, untitled table.
import type { Snippet } from 'svelte';

interface Props {
  title: string;
  icon?: string;
  /** Rendered right-aligned in the title row, e.g. a count badge like "2 running". */
  trailing?: Snippet;
  children: Snippet;
}

let { title, icon, trailing, children }: Props = $props();
</script>

<div class="rounded-md border border-[var(--pd-content-divider)] bg-[var(--pd-content-card-bg)]">
  <div class="flex items-center gap-2 px-4 pt-3 pb-2">
    {#if icon}<i class="{icon} text-xs opacity-70" aria-hidden="true"></i>{/if}
    <span class="text-xs font-semibold uppercase tracking-wide text-[var(--pd-content-header)] opacity-70">{title}</span>
    {#if trailing}
      <span class="ml-auto normal-case font-normal text-xs text-[var(--pd-content-text)] opacity-80">{@render trailing()}</span>
    {/if}
  </div>
  {@render children()}
</div>
