<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// A cursor-positioned context menu, used for the new right-click "Open in
// New Tab / Split Right / Split Down" affordances on list rows and tabs.
// Deliberately independent from DropdownMenu.svelte (which anchors to its
// own trigger button) since this one anchors to an arbitrary click point.
import Icon from '../icons/Icon.svelte';
import type { ContextMenuAction } from './types';

interface Props {
  x: number;
  y: number;
  actions: ContextMenuAction[];
  onClose: () => void;
}

let { x, y, actions, onClose }: Props = $props();

let menuEl: HTMLDivElement | undefined = $state();
let top = $state(0);
let left = $state(0);

$effect(() => {
  top = y;
  left = x;
  if (!menuEl) return;
  const rect = menuEl.getBoundingClientRect();
  if (y + rect.height > window.innerHeight) {
    top = Math.max(0, window.innerHeight - rect.height - 8);
  }
  if (x + rect.width > window.innerWidth) {
    left = Math.max(0, window.innerWidth - rect.width - 8);
  }
});

function handleWindowClick(event: MouseEvent): void {
  if (menuEl && !menuEl.contains(event.target as Node)) {
    onClose();
  }
}

function handleKeydown(event: KeyboardEvent): void {
  if (event.key === 'Escape') {
    onClose();
  }
}

function select(action: ContextMenuAction): void {
  if (action.disabled) return;
  action.onSelect();
  onClose();
}
</script>

<svelte:window onmousedown={handleWindowClick} onkeydown={handleKeydown} oncontextmenu={handleWindowClick} />

<div
  bind:this={menuEl}
  role="menu"
  style="position: fixed; top: {top}px; left: {left}px; z-index: 100;"
  class="min-w-[180px] py-1 rounded-md shadow-lg bg-[var(--pd-dropdown-bg)] ring-2 ring-[var(--pd-dropdown-ring)] divide-y divide-[var(--pd-dropdown-divider)] focus:outline-hidden">
  {#each actions as action (action.id)}
    {#if action.separatorBefore}
      <div class="border-t border-[var(--pd-dropdown-divider)]"></div>
    {/if}
    <div
      role="menuitem"
      tabindex="-1"
      class="px-3 py-2 flex items-center gap-2 whitespace-nowrap text-sm"
      class:opacity-50={action.disabled}
      class:cursor-not-allowed={action.disabled}
      class:cursor-pointer={!action.disabled}
      class:hover:bg-[var(--pd-dropdown-item-hover-bg)]={!action.disabled}
      class:text-[var(--pd-dropdown-item-text)]={!action.danger}
      class:text-[var(--pd-danger-text)]={!!action.danger && !action.disabled}
      onclick={(): void => select(action)}
      onkeydown={(e: KeyboardEvent): void => {
        if (e.key === 'Enter' || e.key === ' ') select(action);
      }}>
      {#if action.iconClass}
        <Icon class="w-4 text-md" icon={action.iconClass} />
      {/if}
      <span>{action.title}</span>
    </div>
  {/each}
</div>
