<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// One leaf panel: its TabBar plus the active tab's content. Resource-agnostic -
// the actual content for a given TabDescriptor is supplied by the caller via
// the `tabContent` snippet, so this component has zero knowledge of
// containers/pods/images.
import { faCompress, faExpand } from '@fortawesome/free-solid-svg-icons';
import type { Snippet } from 'svelte';

import Icon from '../icons/Icon.svelte';
import TabBar from './TabBar.svelte';
import type { TabDescriptor } from './types';

interface Props {
  panelId: string;
  tabs: TabDescriptor[];
  activeTabId?: string;
  focused: boolean;
  maximized: boolean;
  canMaximize: boolean;
  onFocus: () => void;
  onSelect: (tabId: string) => void;
  onClose: (tabId: string) => void;
  onCloseOthers: (tabId: string) => void;
  onCloseAllInPanel: () => void;
  onPinToggle: (tabId: string) => void;
  onReorder: (tabId: string, beforeTabId: string | undefined) => void;
  onMoveFromOtherPanel: (sourcePanelId: string, tabId: string, beforeTabId: string | undefined) => void;
  onSplitRight: (tabId: string) => void;
  onSplitDown: (tabId: string) => void;
  onMoveToNewPanel: (tabId: string) => void;
  onToggleMaximize: () => void;
  /** See TabBar's `onAddTab` - resolved here against this panel's own active tab. */
  onAddTab?: (panelId: string, activeTab: TabDescriptor | undefined) => void;
  /** See TabBar's `canOpenInNewSection`. */
  canOpenInNewSection?: (tabId: string) => boolean;
  /** See TabBar's `trailing`. */
  trailing?: Snippet<[string]>;
  /** See TabBar's `beforeAdd` — called with this panel's id. */
  beforeAdd?: Snippet<[string]>;
  /** When false, skip this panel's TabBar (global strip owns chrome — e.g. single-panel workspace). */
  showTabBar?: boolean;
  tabContent: Snippet<[TabDescriptor]>;
  emptyState?: Snippet;
}

let {
  panelId,
  tabs,
  activeTabId,
  focused,
  maximized,
  canMaximize,
  onFocus,
  onSelect,
  onClose,
  onCloseOthers,
  onCloseAllInPanel,
  onPinToggle,
  onReorder,
  onMoveFromOtherPanel,
  onSplitRight,
  onSplitDown,
  onMoveToNewPanel,
  onToggleMaximize,
  onAddTab,
  canOpenInNewSection,
  trailing,
  beforeAdd: beforeAddForPanel,
  showTabBar = true,
  tabContent,
  emptyState,
}: Props = $props();

const activeTab = $derived(tabs.find(t => t.id === activeTabId));
</script>

<div
  class="flex flex-col min-w-0 min-h-0 h-full w-full overflow-hidden"
  class:ring-1={focused}
  class:ring-[var(--pd-content-divider)]={focused}
  onclick={onFocus}
  onfocus={onFocus}
  role="presentation">
  {#if showTabBar}
    <div class="flex items-stretch min-w-0">
      <div class="grow min-w-0">
        <TabBar
          {panelId}
          {tabs}
          {activeTabId}
          {onSelect}
          {onClose}
          {onCloseOthers}
          {onCloseAllInPanel}
          {onPinToggle}
          {onReorder}
          {onMoveFromOtherPanel}
          {onSplitRight}
          {onSplitDown}
          {onMoveToNewPanel}
          {canOpenInNewSection}
          onAddTab={onAddTab ? (): void => onAddTab(panelId, activeTab) : undefined}
          {trailing}>
          {#snippet beforeAdd()}
            {#if beforeAddForPanel}
              {@render beforeAddForPanel(panelId)}
            {/if}
          {/snippet}
        </TabBar>
      </div>
      {#if canMaximize}
        <button
          type="button"
          aria-label={maximized ? 'Restore panel' : 'Maximize panel'}
          title={maximized ? 'Restore panel' : 'Maximize panel'}
          class="px-2 border-b border-l border-[var(--pd-content-divider)] bg-[var(--pd-content-card-bg)] hover:bg-[var(--pd-action-button-details-bg)]"
          onclick={onToggleMaximize}>
          <Icon class="w-3 text-xs" icon={maximized ? faCompress : faExpand} />
        </button>
      {/if}
    </div>
  {:else if canMaximize}
    <!-- Maximize only — never a second tab strip (global bar is the only tab level). -->
    <div class="flex items-stretch justify-end min-w-0 shrink-0">
      <button
        type="button"
        aria-label={maximized ? 'Restore panel' : 'Maximize panel'}
        title={maximized ? 'Restore panel' : 'Maximize panel'}
        class="px-2 py-1 border-b border-[var(--pd-content-divider)] bg-[var(--pd-content-card-bg)] hover:bg-[var(--pd-action-button-details-bg)]"
        onclick={(e: MouseEvent): void => {
          e.stopPropagation();
          onToggleMaximize();
        }}>
        <Icon class="w-3 text-xs" icon={maximized ? faCompress : faExpand} />
      </button>
    </div>
  {/if}
  <div class="grow min-h-0 overflow-auto bg-[var(--pd-content-bg)]">
    {#if activeTab}
      {@render tabContent(activeTab)}
    {:else if emptyState}
      {@render emptyState()}
    {/if}
  </div>
</div>
