<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Multi-tab strip: reorder by drag, close, pin, overflow, and drop targets for
// moving a tab in from another panel. Resource-agnostic - operates purely on
// TabDescriptor[].
import { faChevronDown, faPlus, faTableColumns, faThumbtack, faXmark } from '@fortawesome/free-solid-svg-icons';
import type { Snippet } from 'svelte';

import Icon from '../icons/Icon.svelte';
import Tooltip from '../tooltip/Tooltip.svelte';
import ContextMenu from './ContextMenu.svelte';
import type { ContextMenuAction, TabDescriptor } from './types';

export const TAB_DRAG_MIME = 'application/x-podman-desktop-tab';

interface DragPayload {
  panelId: string;
  tabId: string;
}

interface Props {
  panelId: string;
  tabs: TabDescriptor[];
  activeTabId?: string;
  onSelect: (tabId: string) => void;
  onClose: (tabId: string) => void;
  onCloseOthers: (tabId: string) => void;
  onCloseAllInPanel: () => void;
  onPinToggle: (tabId: string) => void;
  onReorder: (tabId: string, beforeTabId: string | undefined) => void;
  onMoveFromOtherPanel: (sourcePanelId: string, tabId: string, beforeTabId: string | undefined) => void;
  onSplitRight: (tabId: string) => void;
  onSplitDown: (tabId: string) => void;
  onMoveToNewPanel: (tabId: string) => void;
  /** When provided, renders a "+" button after the tabs that opens a new-tab picker (other
   * views of the active resource, any pod/container/image, or a free-text ask-the-agent
   * entry) - instead of cluttering every tab's content with a static row of sub-views. */
  onAddTab?: () => void;
  /** Rendered pinned to the far right of the bar, regardless of tab count - e.g. a settings
   * button - so the bar itself doubles as the app's persistent toolbar instead of needing a
   * separate full-width row above it. */
  trailing?: Snippet;
  /** Rendered in place of the tab list only while `tabs` is empty - a first-run hint like "Open
   * a resource to start a tab here", so an empty bar isn't just an unlabeled strip with no clue
   * what it's for. Callers are expected to only pass this once (e.g. gated on a "has the user
   * ever opened a tab" flag) so it doesn't reappear every time the bar happens to be empty again. */
  emptyHint?: Snippet;
}

let {
  panelId,
  tabs,
  activeTabId,
  onSelect,
  onClose,
  onCloseOthers,
  onCloseAllInPanel,
  onPinToggle,
  onReorder,
  onMoveFromOtherPanel,
  onSplitRight,
  onSplitDown,
  onMoveToNewPanel,
  onAddTab,
  trailing,
  emptyHint,
}: Props = $props();

let scrollEl: HTMLDivElement | undefined = $state();
let overflowing = $state(false);
let showOverflowMenu = $state(false);
let dragOverTabId: string | undefined = $state();
let contextMenu: { x: number; y: number; tabId: string } | undefined = $state();

function checkOverflow(_tabCount: number): void {
  if (!scrollEl) return;
  overflowing = scrollEl.scrollWidth > scrollEl.clientWidth + 1;
}

$effect(() => {
  // reading tabs.length here makes this effect re-run whenever the tab list changes
  const tabCount = tabs.length;
  requestAnimationFrame(() => checkOverflow(tabCount));
});

function onWheel(event: WheelEvent): void {
  if (!scrollEl) return;
  if (event.deltaY === 0) return;
  scrollEl.scrollLeft += event.deltaY;
  event.preventDefault();
}

function onDragStart(event: DragEvent, tabId: string): void {
  const payload: DragPayload = { panelId, tabId };
  event.dataTransfer?.setData(TAB_DRAG_MIME, JSON.stringify(payload));
  if (event.dataTransfer) event.dataTransfer.effectAllowed = 'move';
}

function onDragOverTab(event: DragEvent, tabId: string): void {
  event.preventDefault();
  dragOverTabId = tabId;
}

function onDragLeaveTab(): void {
  dragOverTabId = undefined;
}

function readPayload(event: DragEvent): DragPayload | undefined {
  const raw = event.dataTransfer?.getData(TAB_DRAG_MIME);
  if (!raw) return undefined;
  try {
    return JSON.parse(raw) as DragPayload;
  } catch {
    return undefined;
  }
}

function onDropOnTab(event: DragEvent, beforeTabId: string): void {
  event.preventDefault();
  dragOverTabId = undefined;
  const payload = readPayload(event);
  if (!payload) return;
  if (payload.panelId === panelId) {
    if (payload.tabId !== beforeTabId) onReorder(payload.tabId, beforeTabId);
  } else {
    onMoveFromOtherPanel(payload.panelId, payload.tabId, beforeTabId);
  }
}

function onDropOnEnd(event: DragEvent): void {
  event.preventDefault();
  dragOverTabId = undefined;
  const payload = readPayload(event);
  if (!payload) return;
  if (payload.panelId === panelId) {
    onReorder(payload.tabId, undefined);
  } else {
    onMoveFromOtherPanel(payload.panelId, payload.tabId, undefined);
  }
}

function openContextMenu(event: MouseEvent, tabId: string): void {
  event.preventDefault();
  contextMenu = { x: event.clientX, y: event.clientY, tabId };
}

function contextMenuActions(tabId: string): ContextMenuAction[] {
  const tab = tabs.find(t => t.id === tabId);
  return [
    { id: 'close', title: 'Close', iconClass: 'fas fa-xmark', onSelect: (): void => onClose(tabId) },
    {
      id: 'close-others',
      title: 'Close Others',
      iconClass: 'fas fa-xmark',
      onSelect: (): void => onCloseOthers(tabId),
    },
    {
      id: 'close-all',
      title: 'Close All in Panel',
      iconClass: 'fas fa-xmark',
      onSelect: (): void => onCloseAllInPanel(),
    },
    {
      id: 'pin',
      title: tab?.pinned ? 'Unpin Tab' : 'Pin Tab',
      iconClass: 'fas fa-thumbtack',
      separatorBefore: true,
      onSelect: (): void => onPinToggle(tabId),
    },
    {
      id: 'split-right',
      title: 'Split Right',
      iconClass: 'fas fa-table-columns',
      separatorBefore: true,
      onSelect: (): void => onSplitRight(tabId),
    },
    {
      id: 'split-down',
      title: 'Split Down',
      iconClass: 'fas fa-table-columns',
      onSelect: (): void => onSplitDown(tabId),
    },
    {
      id: 'move-new-panel',
      title: 'Move to New Panel',
      iconClass: 'fas fa-up-right-from-square',
      onSelect: (): void => onMoveToNewPanel(tabId),
    },
  ];
}
</script>

<div
  class="flex items-stretch min-h-6 border-b border-[var(--pd-content-divider)] bg-[var(--pd-content-card-bg)] text-sm min-w-0">
  <!-- min-h-6 keeps this bar's height stable across empty <-> non-empty tab states: with no tabs
       open, `items-stretch` would otherwise size the whole row down to its shortest child (the
       icon-only trailing button, ~11px) instead of a real tab's own height (~24.5px, from its
       padding + text-sm line-height) - shifting the empty-state placeholder below it up/down
       every time the last tab closes or the first one opens. -->
  <div
    bind:this={scrollEl}
    onwheel={onWheel}
    class="flex flex-row items-stretch overflow-x-auto min-w-0 grow scrollbar-hide"
    role="tablist"
    tabindex="-1"
    ondragover={(e: DragEvent): void => e.preventDefault()}
    ondrop={onDropOnEnd}>
    {#each tabs as tab (tab.id)}
      <div
        role="tab"
        tabindex="0"
        aria-selected={tab.id === activeTabId}
        draggable="true"
        ondragstart={(e: DragEvent): void => onDragStart(e, tab.id)}
        ondragover={(e: DragEvent): void => onDragOverTab(e, tab.id)}
        ondragleave={onDragLeaveTab}
        ondrop={(e: DragEvent): void => onDropOnTab(e, tab.id)}
        oncontextmenu={(e: MouseEvent): void => openContextMenu(e, tab.id)}
        onclick={(): void => onSelect(tab.id)}
        onkeydown={(e: KeyboardEvent): void => {
          if (e.key === 'Enter' || e.key === ' ') onSelect(tab.id);
        }}
        class="group flex items-center gap-2 px-3 py-1 border-r border-[var(--pd-content-divider)] whitespace-nowrap cursor-pointer select-none max-w-[220px]"
        class:bg-[var(--pd-content-bg)]={tab.id === activeTabId}
        class:border-l-2={dragOverTabId === tab.id}
        class:border-l-[var(--pd-tab-highlight)]={dragOverTabId === tab.id}
        class:text-[var(--pd-tab-text-highlight)]={tab.id === activeTabId}
        class:text-[var(--pd-tab-text)]={tab.id !== activeTabId}
        class:opacity-70={!!tab.stale}
        title={tab.subtitle ? `${tab.title} — ${tab.subtitle}` : tab.title}>
        {#if tab.pinned}
          <Icon class="w-3 text-xs opacity-70" icon={faThumbtack} />
        {/if}
        {#if tab.agentCreated}
          <Tooltip tip="Opened by an agent" top>
            <span class="block w-1.5 h-1.5 rounded-full bg-[var(--pd-status-running)] shrink-0"></span>
          </Tooltip>
        {/if}
        <span class="overflow-hidden text-ellipsis">{tab.title}</span>
        {#if tab.stale}
          <span class="text-[10px] uppercase tracking-wide text-[var(--pd-status-degraded)]">missing</span>
        {/if}
        <div class="flex items-center gap-0.5">
          <Tooltip tip={tabs.length > 1 ? 'Open in a new section' : 'Can\'t split - only tab in section'} top>
            <button
              type="button"
              aria-label="Split {tab.title} to the right"
              disabled={tabs.length <= 1}
              class="opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 focus-visible:opacity-100 disabled:group-hover:opacity-40 disabled:group-focus-within:opacity-40 hover:bg-[var(--pd-action-button-details-bg)] disabled:hover:bg-transparent rounded-sm p-0.5 disabled:cursor-not-allowed"
              onclick={(e: MouseEvent): void => {
                e.stopPropagation();
                onSplitRight(tab.id);
              }}>
              <Icon class="w-3 text-xs" icon={faTableColumns} />
            </button>
          </Tooltip>
          {#if !tab.pinned}
            <Tooltip tip="Close tab" top>
              <button
                type="button"
                aria-label="Close tab {tab.title}"
                class="opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 focus-visible:opacity-100 hover:bg-[var(--pd-action-button-details-bg)] rounded-sm p-0.5"
                class:opacity-100={tab.id === activeTabId}
                onclick={(e: MouseEvent): void => {
                  e.stopPropagation();
                  onClose(tab.id);
                }}>
                <Icon class="w-3 text-xs" icon={faXmark} />
              </button>
            </Tooltip>
          {/if}
        </div>
      </div>
    {/each}

    {#if tabs.length === 0 && emptyHint}
      <div class="flex items-center px-3 text-xs text-[var(--pd-content-text)] opacity-60 whitespace-nowrap">
        {@render emptyHint()}
      </div>
    {/if}

    {#if onAddTab && tabs.length > 0}
      <!-- Lives inside the scrollable row, right next to the last tab - not pinned to the
           far edge of the bar - and scrolls along with the tabs, like Cursor/VS Code.
           Nothing to offer "another view" of with zero tabs open - the empty state already
           covers that case, so skip the button rather than leave it floating alone in an
           otherwise-empty bar. -->
      <Tooltip tip="Open a new tab" top containerClass="flex items-stretch" class="flex items-stretch">
        <button
          type="button"
          aria-label="Open a new tab"
          class="flex items-center px-2.5 shrink-0 hover:bg-[var(--pd-action-button-details-bg)]"
          onclick={onAddTab}>
          <Icon class="w-3 text-xs" icon={faPlus} />
        </button>
      </Tooltip>
    {/if}
  </div>

  {#if overflowing}
    <div class="relative flex items-center border-l border-[var(--pd-content-divider)] px-1">
      <button
        type="button"
        aria-label="Show all open tabs"
        class="px-2 py-1 hover:bg-[var(--pd-action-button-details-bg)] rounded-sm"
        onclick={(): void => {
          showOverflowMenu = !showOverflowMenu;
        }}>
        <Icon class="w-3 text-xs" icon={faChevronDown} />
      </button>
      {#if showOverflowMenu}
        <div
          class="absolute right-0 top-8 z-20 max-h-72 overflow-y-auto min-w-[220px] rounded-md shadow-lg bg-[var(--pd-dropdown-bg)] ring-2 ring-[var(--pd-dropdown-ring)] divide-y divide-[var(--pd-dropdown-divider)]">
          {#each tabs as tab (tab.id)}
            <div
              role="menuitem"
              tabindex="-1"
              class="px-3 py-2 text-sm whitespace-nowrap cursor-pointer hover:bg-[var(--pd-dropdown-item-hover-bg)]"
              class:text-[var(--pd-tab-text-highlight)]={tab.id === activeTabId}
              onclick={(): void => {
                onSelect(tab.id);
                showOverflowMenu = false;
              }}
              onkeydown={(e: KeyboardEvent): void => {
                if (e.key === 'Enter' || e.key === ' ') {
                  onSelect(tab.id);
                  showOverflowMenu = false;
                }
              }}>
              {tab.title}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  {/if}

  {#if trailing}
    <div class="flex items-stretch border-l border-[var(--pd-content-divider)]">
      {@render trailing()}
    </div>
  {/if}
</div>

{#if contextMenu}
  <ContextMenu
    x={contextMenu.x}
    y={contextMenu.y}
    actions={contextMenuActions(contextMenu.tabId)}
    onClose={(): void => {
      contextMenu = undefined;
    }} />
{/if}

<style>
  .scrollbar-hide {
    scrollbar-width: none;
  }
  .scrollbar-hide::-webkit-scrollbar {
    display: none;
  }
</style>
