<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Multi-tab strip: reorder by drag, close, pin, overflow, and drop targets for
// moving a tab in from another panel. Resource-agnostic - operates purely on
// TabDescriptor[].
import { faChevronDown, faEllipsisVertical, faPlus, faThumbtack } from '@fortawesome/free-solid-svg-icons';
import type { Snippet } from 'svelte';

import Icon from '../icons/Icon.svelte';
import Tooltip from '../tooltip/Tooltip.svelte';
import ContextMenu from './ContextMenu.svelte';
import type { ContextMenuAction, TabDescriptor } from './types';

export const TAB_DRAG_MIME = 'application/x-podman-desktop-tab';

interface DragPayload {
  panelId: string;
  tabId: string;
}

interface Props {
  panelId: string;
  tabs: TabDescriptor[];
  activeTabId?: string;
  onSelect: (tabId: string) => void;
  onClose: (tabId: string) => void;
  onPinToggle: (tabId: string) => void;
  onReorder: (tabId: string, beforeTabId: string | undefined) => void;
  onMoveFromOtherPanel: (sourcePanelId: string, tabId: string, beforeTabId: string | undefined) => void;
  onSplitRight: (tabId: string) => void;
  onSplitDown: (tabId: string) => void;
  onMoveUp?: (tabId: string) => void;
  canMoveUp?: (tabId: string) => boolean;
  /** When set, controls whether "Open in a new section" is enabled for a tab. Defaults to
   * "at least two non-permanent tabs in this bar" (fine for a per-panel bar; global bars
   * should pass a per-section check so a lone tab in its section cannot be moved out). */
  canOpenInNewSection?: (tabId: string) => boolean;
  /** When provided, renders a "+" button after the tab scroller (always visible — does not
   * scroll away with overflow) that opens a new-tab picker (other views of the active
   * resource, any pod/container/image, or a free-text ask-the-agent entry). */
  onAddTab?: () => void;
  /** Rendered pinned to the far right of the bar, regardless of tab count - e.g. a settings
   * button - so the bar itself doubles as the app's persistent toolbar instead of needing a
   * separate full-width row above it. Called with this bar's own `panelId`, so a "close all"
   * style action in there can be scoped to just this panel instead of every panel. */
  trailing?: Snippet<[string]>;
  /** Rendered after the last tab inside the scrollable row (before the pinned "+") —
   * e.g. a compact "+N hidden sections" chip. */
  beforeAdd?: Snippet;
  /** Rendered in place of the tab list only while `tabs` is empty - a first-run hint like "Open
   * a resource to start a tab here", so an empty bar isn't just an unlabeled strip with no clue
   * what it's for. Callers are expected to only pass this once (e.g. gated on a "has the user
   * ever opened a tab" flag) so it doesn't reappear every time the bar happens to be empty again. */
  emptyHint?: Snippet;
}

let {
  panelId,
  tabs,
  activeTabId,
  onSelect,
  onClose,
  onPinToggle,
  onReorder,
  onMoveFromOtherPanel,
  onSplitRight,
  onSplitDown,
  onMoveUp,
  canMoveUp,
  canOpenInNewSection,
  onAddTab,
  trailing,
  beforeAdd,
  emptyHint,
}: Props = $props();

function sectionOpenAllowed(tabId: string): boolean {
  if (canOpenInNewSection) return canOpenInNewSection(tabId);
  // Default: leave at least one tab behind (permanent page tab counts).
  const tab = tabs.find(t => t.id === tabId);
  if (tab?.permanent) return false;
  return tabs.some(t => t.id !== tabId);
}

let scrollEl: HTMLDivElement | undefined = $state();
let overflowing = $state(false);
let showOverflowMenu = $state(false);
let dragTarget: { tabId: string; edge: 'before' | 'after' } | undefined = $state();
let draggingTabId: string | undefined = $state();
let draggedTabWidth = $state(120);
let contextMenu: { x: number; y: number; tabId: string } | undefined = $state();

function checkOverflow(_tabCount: number): void {
  if (!scrollEl) return;
  overflowing = scrollEl.scrollWidth > scrollEl.clientWidth + 1;
}

$effect(() => {
  // reading tabs.length here makes this effect re-run whenever the tab list changes
  const tabCount = tabs.length;
  requestAnimationFrame(() => checkOverflow(tabCount));
});

function onWheel(event: WheelEvent): void {
  if (!scrollEl) return;
  if (event.deltaY === 0) return;
  scrollEl.scrollLeft += event.deltaY;
  event.preventDefault();
}

function onDragStart(event: DragEvent, tabId: string): void {
  const tab = tabs.find(t => t.id === tabId);
  if (tab?.permanent) {
    event.preventDefault();
    return;
  }
  const payload: DragPayload = { panelId, tabId };
  draggingTabId = tabId;
  draggedTabWidth = Math.max(96, (event.currentTarget as HTMLElement).getBoundingClientRect().width);
  event.dataTransfer?.setData(TAB_DRAG_MIME, JSON.stringify(payload));
  if (event.dataTransfer) event.dataTransfer.effectAllowed = 'move';
}

function onDragOverTab(event: DragEvent, tabId: string, forcedEdge?: 'before' | 'after'): void {
  event.preventDefault();
  event.stopPropagation();
  if (event.dataTransfer) event.dataTransfer.dropEffect = 'move';
  const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
  dragTarget = { tabId, edge: forcedEdge ?? (event.clientX < rect.left + rect.width / 2 ? 'before' : 'after') };
  if (scrollEl && event.clientX < scrollEl.getBoundingClientRect().left + 32) scrollEl.scrollLeft -= 12;
  if (scrollEl && event.clientX > scrollEl.getBoundingClientRect().right - 32) scrollEl.scrollLeft += 12;
}

function onDragEnd(): void {
  dragTarget = undefined;
  draggingTabId = undefined;
}

function onDragLeaveBar(event: DragEvent): void {
  if ((event.currentTarget as HTMLElement).contains(event.relatedTarget as Node | null)) return;
  dragTarget = undefined;
}

function readPayload(event: DragEvent): DragPayload | undefined {
  const raw = event.dataTransfer?.getData(TAB_DRAG_MIME);
  if (!raw) return undefined;
  try {
    return JSON.parse(raw) as DragPayload;
  } catch {
    return undefined;
  }
}

function onDropOnTab(event: DragEvent, targetTabId: string): void {
  event.preventDefault();
  event.stopPropagation();
  const payload = readPayload(event);
  const edge = dragTarget?.tabId === targetTabId ? dragTarget.edge : 'before';
  dragTarget = undefined;
  if (!payload) return;
  if (payload.panelId === panelId && payload.tabId === targetTabId) return;
  const orderedIds = tabs.map(tab => tab.id).filter(id => id !== payload.tabId);
  const targetIndex = orderedIds.indexOf(targetTabId);
  const targetTab = tabs.find(tab => tab.id === targetTabId);
  const beforeTabId = targetTab?.permanent
    ? targetTabId
    : edge === 'before'
      ? targetTabId
      : orderedIds[targetIndex + 1];
  if (payload.panelId === panelId) {
    onReorder(payload.tabId, beforeTabId);
  } else {
    onMoveFromOtherPanel(payload.panelId, payload.tabId, beforeTabId);
  }
}

function onDropOnEnd(event: DragEvent): void {
  event.preventDefault();
  dragTarget = undefined;
  const payload = readPayload(event);
  if (!payload) return;
  if (payload.panelId === panelId) {
    onReorder(payload.tabId, undefined);
  } else {
    onMoveFromOtherPanel(payload.panelId, payload.tabId, undefined);
  }
}

function openContextMenu(event: MouseEvent, tabId: string): void {
  event.preventDefault();
  contextMenu = { x: event.clientX, y: event.clientY, tabId };
}

function openActionsMenu(event: MouseEvent, tabId: string): void {
  event.stopPropagation();
  const rect = (event.currentTarget as HTMLButtonElement).getBoundingClientRect();
  contextMenu = { x: rect.right - 190, y: rect.bottom + 4, tabId };
}

function contextMenuActions(tabId: string): ContextMenuAction[] {
  const tab = tabs.find(t => t.id === tabId);
  const canSplit = sectionOpenAllowed(tabId);
  const moveUpAllowed = canMoveUp?.(tabId) ?? false;
  if (tab?.permanent) return [];
  return [
    { id: 'close', title: 'Close Tab', iconClass: 'fas fa-xmark', onSelect: (): void => onClose(tabId) },
    {
      id: 'pin',
      title: tab?.pinned ? 'Unpin Tab' : 'Pin Tab',
      iconClass: 'fas fa-thumbtack',
      separatorBefore: true,
      onSelect: (): void => onPinToggle(tabId),
    },
    {
      id: 'split-right',
      title: 'Split Right',
      iconClass: 'fas fa-table-columns',
      disabled: !canSplit,
      separatorBefore: true,
      onSelect: (): void => onSplitRight(tabId),
    },
    {
      id: 'split-down',
      title: moveUpAllowed ? 'Move Up' : 'Split Down',
      iconClass: moveUpAllowed ? 'fas fa-arrow-up' : 'fas fa-grip-lines',
      disabled: !moveUpAllowed && !canSplit,
      onSelect: (): void => (moveUpAllowed ? onMoveUp?.(tabId) : onSplitDown(tabId)),
    },
  ];
}
</script>

<div
  class="flex items-stretch min-h-6 border-b border-[var(--pd-content-divider)] bg-[var(--pd-content-card-bg)] text-sm min-w-0">
  <!-- Tabs + "+" share a grow group: scroller sizes to content when it fits (so "+" sits
       right after the last tab), and shrinks with overflow-x when it doesn't — "+" stays
       pinned outside the scroller so it never scrolls away. -->
  <div class="flex items-stretch min-w-0 grow min-h-6">
    <div
      bind:this={scrollEl}
      onwheel={onWheel}
      class="flex flex-row items-stretch overflow-x-auto min-w-0 shrink scrollbar-hide"
      role="tablist"
      tabindex="-1"
      ondragover={(e: DragEvent): void => e.preventDefault()}
      ondragleave={onDragLeaveBar}
      ondrop={onDropOnEnd}>
      {#each tabs as tab (tab.id)}
        {#if dragTarget?.tabId === tab.id && dragTarget.edge === 'before'}
          <div
            class="shrink-0 flex items-center justify-center border-2 border-dashed border-[var(--pd-tab-highlight)] bg-[var(--pd-content-bg)] text-[10px] text-[var(--pd-tab-text-highlight)]"
            style:width="{draggedTabWidth}px"
            ondragover={(event: DragEvent): void => {
              event.preventDefault();
              event.stopPropagation();
            }}
            ondrop={(event: DragEvent): void => onDropOnTab(event, tab.id)}>
            Drop here
          </div>
        {/if}
        <div
          role="tab"
          tabindex="0"
          aria-selected={tab.id === activeTabId}
          draggable={!tab.permanent}
          ondragstart={(e: DragEvent): void => onDragStart(e, tab.id)}
          ondragend={onDragEnd}
          ondragover={(e: DragEvent): void => onDragOverTab(e, tab.id, tab.permanent ? 'after' : undefined)}
          ondrop={(e: DragEvent): void => onDropOnTab(e, tab.id)}
          oncontextmenu={(e: MouseEvent): void => openContextMenu(e, tab.id)}
          onclick={(): void => onSelect(tab.id)}
          onkeydown={(e: KeyboardEvent): void => {
            if (e.key === 'Enter' || e.key === ' ') onSelect(tab.id);
          }}
          class="group flex items-center gap-2 px-3 py-1 border-r border-[var(--pd-content-divider)] whitespace-nowrap cursor-pointer select-none max-w-[220px]"
          class:bg-[var(--pd-content-bg)]={tab.id === activeTabId}
          class:border-l-2={dragTarget?.tabId === tab.id && dragTarget.edge === 'before'}
          class:border-l-[var(--pd-tab-highlight)]={dragTarget?.tabId === tab.id && dragTarget.edge === 'before'}
          class:border-r-2={dragTarget?.tabId === tab.id && dragTarget.edge === 'after'}
          class:border-r-[var(--pd-tab-highlight)]={dragTarget?.tabId === tab.id && dragTarget.edge === 'after'}
          class:text-[var(--pd-tab-text-highlight)]={tab.id === activeTabId}
          class:text-[var(--pd-tab-text)]={tab.id !== activeTabId}
          class:opacity-70={!!tab.stale}
          class:opacity-40={draggingTabId === tab.id}
          title={tab.subtitle ? `${tab.title} — ${tab.subtitle}` : tab.title}>
          {#if tab.pinned && !tab.permanent}
            <Icon class="w-3 text-xs opacity-70" icon={faThumbtack} />
          {/if}
          {#if tab.agentCreated}
            <Tooltip tip="Opened by an agent" top>
              <span class="block w-1.5 h-1.5 rounded-full bg-[var(--pd-status-running)] shrink-0"></span>
            </Tooltip>
          {/if}
          <span class="overflow-hidden text-ellipsis">{tab.title}</span>
          {#if tab.stale}
            <span class="text-[10px] uppercase tracking-wide text-[var(--pd-status-degraded)]">missing</span>
          {/if}
          {#if !tab.permanent}
            <Tooltip tip="Tab actions" top>
              <button
                type="button"
                aria-label="Actions for {tab.title}"
                class="opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 focus-visible:opacity-100 hover:bg-[var(--pd-action-button-details-bg)] rounded-sm p-0.5"
                class:opacity-100={tab.id === activeTabId}
                onclick={(event: MouseEvent): void => openActionsMenu(event, tab.id)}>
                <Icon class="w-3 text-xs" icon={faEllipsisVertical} />
              </button>
            </Tooltip>
          {/if}
        </div>
        {#if dragTarget?.tabId === tab.id && dragTarget.edge === 'after'}
          <div
            class="shrink-0 flex items-center justify-center border-2 border-dashed border-[var(--pd-tab-highlight)] bg-[var(--pd-content-bg)] text-[10px] text-[var(--pd-tab-text-highlight)]"
            style:width="{draggedTabWidth}px"
            ondragover={(event: DragEvent): void => {
              event.preventDefault();
              event.stopPropagation();
            }}
            ondrop={(event: DragEvent): void => onDropOnTab(event, tab.id)}>
            Drop here
          </div>
        {/if}
      {/each}

      {#if tabs.length === 0 && emptyHint}
        <div class="flex items-center px-3 text-xs text-[var(--pd-content-text)] opacity-60 whitespace-nowrap">
          {@render emptyHint()}
        </div>
      {/if}

      {#if beforeAdd}
        {@render beforeAdd()}
      {/if}
    </div>

    {#if onAddTab && tabs.length > 0}
      <Tooltip tip="Open a new tab" top containerClass="flex items-stretch shrink-0" class="flex items-stretch">
        <button
          type="button"
          aria-label="Open a new tab"
          class="flex items-center px-2.5 shrink-0 border-l border-[var(--pd-content-divider)] hover:bg-[var(--pd-action-button-details-bg)]"
          onclick={onAddTab}>
          <Icon class="w-3 text-xs" icon={faPlus} />
        </button>
      </Tooltip>
    {/if}
  </div>

  {#if overflowing}
    <div class="relative flex items-center border-l border-[var(--pd-content-divider)] px-1">
      <button
        type="button"
        aria-label="Show all open tabs"
        class="px-2 py-1 hover:bg-[var(--pd-action-button-details-bg)] rounded-sm"
        onclick={(): void => {
          showOverflowMenu = !showOverflowMenu;
        }}>
        <Icon class="w-3 text-xs" icon={faChevronDown} />
      </button>
      {#if showOverflowMenu}
        <div
          class="absolute right-0 top-8 z-20 max-h-72 overflow-y-auto min-w-[220px] rounded-md shadow-lg bg-[var(--pd-dropdown-bg)] ring-2 ring-[var(--pd-dropdown-ring)] divide-y divide-[var(--pd-dropdown-divider)]">
          {#each tabs as tab (tab.id)}
            <div
              role="menuitem"
              tabindex="-1"
              class="px-3 py-2 text-sm whitespace-nowrap cursor-pointer hover:bg-[var(--pd-dropdown-item-hover-bg)]"
              class:text-[var(--pd-tab-text-highlight)]={tab.id === activeTabId}
              onclick={(): void => {
                onSelect(tab.id);
                showOverflowMenu = false;
              }}
              onkeydown={(e: KeyboardEvent): void => {
                if (e.key === 'Enter' || e.key === ' ') {
                  onSelect(tab.id);
                  showOverflowMenu = false;
                }
              }}>
              {tab.title}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  {/if}

  {#if trailing}
    <div class="flex items-stretch border-l border-[var(--pd-content-divider)]">
      {@render trailing(panelId)}
    </div>
  {/if}
</div>

{#if contextMenu}
  <ContextMenu
    x={contextMenu.x}
    y={contextMenu.y}
    actions={contextMenuActions(contextMenu.tabId)}
    onClose={(): void => {
      contextMenu = undefined;
    }} />
{/if}

<style>
  .scrollbar-hide {
    scrollbar-width: none;
  }
  .scrollbar-hide::-webkit-scrollbar {
    display: none;
  }
</style>
