/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Resource-agnostic primitives for the Tabs & Flexible Layout prototype.
// These types intentionally know nothing about containers/pods/images so that
// this whole `layout` folder can be reused as-is by other products (e.g. Kaiden)
// built on the same design system.

/** A single open tab. `key` is what identifies "sameness" across opens (used to focus an existing tab instead of duplicating it). */
export interface TabDescriptor {
  id: string;
  /** Stable identity, e.g. `container:abc123:logs`. Two opens with the same key focus the same tab instead of creating a duplicate. */
  key: string;
  title: string;
  subtitle?: string;
  /** Font Awesome icon class list, e.g. 'fa-solid fa-box' */
  iconClass?: string;
  pinned?: boolean;
  /** Permanent tabs cannot be closed, pinned, dragged, or split (e.g. the app page tab). */
  permanent?: boolean;
  /** Set when the underlying resource this tab points to no longer exists. */
  stale?: boolean;
  /** Set when this tab/panel was opened programmatically (e.g. by an agent) rather than by the user. */
  agentCreated?: boolean;
}

export type SplitDirection = 'row' | 'column';

export interface LeafPanelNode {
  kind: 'leaf';
  id: string;
  tabIds: string[];
  activeTabId?: string;
  maximized?: boolean;
}

export interface SplitPanelNode {
  kind: 'split';
  id: string;
  direction: SplitDirection;
  children: PanelNode[];
  /** Relative size weights, same length/order as `children`. */
  sizes: number[];
}

export type PanelNode = LeafPanelNode | SplitPanelNode;

export type OpenMode = 'replace' | 'newTab' | 'splitRight' | 'splitDown';

export interface ContextMenuAction {
  id: string;
  title: string;
  iconClass?: string;
  disabled?: boolean;
  danger?: boolean;
  separatorBefore?: boolean;
  onSelect: () => void;
}
