/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Open create/load/pull form pages as workspace tabs (Version 2 compact-nav).
import type { OpenMode } from '@podman-desktop/ui-svelte';

import { openTab } from '/@/stores/layout/layout-store.svelte';
import type { ActionPageId } from '/@/stores/layout/layout-types';
import { gotoListShell } from '/@/stores/layout/page-tab.svelte';

const ACTION_META: Record<ActionPageId, { title: string; iconClass: string }> = {
  'load-images': { title: 'Load Images', iconClass: 'fas fa-upload' },
  'import-images': { title: 'Import Containers', iconClass: 'fas fa-arrow-circle-down' },
  'pull-image': { title: 'Pull Image', iconClass: 'fas fa-arrow-circle-down' },
  'build-image': { title: 'Build Image', iconClass: 'fas fa-cube' },
  'create-volume': { title: 'Create a Volume', iconClass: 'fas fa-plus-circle' },
  'create-network': { title: 'Create a Network', iconClass: 'fas fa-plus-circle' },
  'create-secret': { title: 'Create a Secret', iconClass: 'fas fa-plus-circle' },
  'create-container-existing': { title: 'Select an image', iconClass: 'fas fa-plus-circle' },
  'kube-play': { title: 'Podman kube play', iconClass: 'fas fa-play-circle' },
};

export function openActionPageTab(actionId: ActionPageId, mode: OpenMode = 'newTab'): void {
  const meta = ACTION_META[actionId];
  openTab(
    {
      resourceType: 'action',
      resourceId: actionId,
      title: meta.title,
      iconClass: meta.iconClass,
    },
    mode,
  );
  gotoListShell();
}
