<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Hosts Load / Import / Pull / Build / Create / kube-play forms inside a workspace tab.
import { setContext } from 'svelte';

import CreateContainerFromExistingImage from '/@/lib/container/CreateContainerFromExistingImage.svelte';
import BuildImageFromContainerfile from '/@/lib/image/BuildImageFromContainerfile.svelte';
import ImportContainersImages from '/@/lib/image/ImportContainersImages.svelte';
import LoadImages from '/@/lib/image/LoadImages.svelte';
import PullImage from '/@/lib/image/PullImage.svelte';
import KubePlayYAML from '/@/lib/kube/KubePlayYAML.svelte';
import CreateNetwork from '/@/lib/network/CreateNetwork.svelte';
import SecretCreate from '/@/lib/secrets/SecretCreate.svelte';
import CreateVolume from '/@/lib/volume/CreateVolume.svelte';
import type { ActionPageId } from '/@/stores/layout/layout-types';

import { ACTION_PAGE_EMBEDDED_CONTEXT } from './action-page-context';

interface Props {
  actionId: string;
}

let { actionId }: Props = $props();

setContext(ACTION_PAGE_EMBEDDED_CONTEXT, true);

const id = $derived(actionId as ActionPageId);
</script>

<div class="h-full min-h-0 overflow-auto">
  {#if id === 'load-images'}
    <LoadImages />
  {:else if id === 'import-images'}
    <ImportContainersImages />
  {:else if id === 'pull-image'}
    <PullImage />
  {:else if id === 'build-image'}
    <BuildImageFromContainerfile />
  {:else if id === 'create-volume'}
    <CreateVolume />
  {:else if id === 'create-network'}
    <CreateNetwork />
  {:else if id === 'create-secret'}
    <SecretCreate />
  {:else if id === 'create-container-existing'}
    <CreateContainerFromExistingImage />
  {:else if id === 'kube-play'}
    <KubePlayYAML />
  {/if}
</div>
