<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Renders the permanent first-section tab: the current list/dashboard page.
import ContainerList from '/@/lib/container/ContainerList.svelte';
import DashboardPage from '/@/lib/dashboard/DashboardPage.svelte';
import ImagesList from '/@/lib/image/ImagesList.svelte';
import NetworksList from '/@/lib/network/NetworksList.svelte';
import PodsList from '/@/lib/pod/PodsList.svelte';
import SecretsList from '/@/lib/secrets/SecretsList.svelte';
import VolumesList from '/@/lib/volume/VolumesList.svelte';
import { getLastAppPageUrl } from '/@/stores/layout/page-tab.svelte';

const pageUrl = $derived(getLastAppPageUrl());
</script>

<div class="h-full min-h-0 overflow-auto">
  {#if pageUrl === '/' || pageUrl.startsWith('/?')}
    <DashboardPage />
  {:else if pageUrl.startsWith('/containers')}
    <ContainerList />
  {:else if pageUrl.startsWith('/pods')}
    <PodsList />
  {:else if pageUrl.startsWith('/images')}
    <ImagesList />
  {:else if pageUrl.startsWith('/volumes')}
    <VolumesList />
  {:else if pageUrl.startsWith('/networks')}
    <NetworksList />
  {:else if pageUrl.startsWith('/secrets')}
    <SecretsList />
  {:else}
    <ContainerList />
  {/if}
</div>
