<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Per-section close control in the tab bar trailing slot. The shared layout
// settings gear lives only on the last section (see LayoutToolbar).
import { faXmark } from '@fortawesome/free-solid-svg-icons';
import { Tooltip } from '@podman-desktop/ui-svelte';
import { Icon } from '@podman-desktop/ui-svelte/icons';

import { closeAllInPanel, hasClosableTabsInPanel } from '/@/stores/layout/layout-store.svelte';

interface Props {
  panelId: string;
}

let { panelId }: Props = $props();

const canClose = $derived(hasClosableTabsInPanel(panelId));
const tip = $derived(canClose ? 'Close section' : 'No tabs to close in this section');

function onClose(): void {
  if (!canClose) return;
  closeAllInPanel(panelId);
}
</script>

<!-- Match TabBar's "+" Tooltip stretch so the X centers with tabs (and gear when present). -->
<Tooltip bottom tip={tip} containerClass="flex items-stretch self-stretch" class="flex items-stretch">
  <button
    type="button"
    aria-label={tip}
    disabled={!canClose}
    class="flex items-center px-2.5 self-stretch hover:bg-[var(--pd-action-button-details-bg)] text-[var(--pd-tab-text)] disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-transparent"
    onclick={onClose}>
    <Icon class="w-3 text-xs" icon={faXmark} />
  </button>
</Tooltip>
