<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Sidebar resource row: StatusIcon (shape + icon) plus a text status label —
// color alone is not enough for accessibility. On a narrow sidebar the label is
// hidden and the status is exposed via tooltip on the status icon instead.
// Optional actions snippet shows a kebab menu on hover next to the status.
import type { IconDefinition } from '@fortawesome/fontawesome-common-types';
import { Spinner, StatusIcon, Tooltip } from '@podman-desktop/ui-svelte';
import type { Component, Snippet } from 'svelte';

import { isLoadingStatus } from '/@/lib/layout/compact-nav-action-status.svelte';
import { capitalize } from '/@/lib/ui/Util';

interface Props {
  label: string;
  status: string;
  icon: IconDefinition | Component | string;
  onclick: () => void;
  /** When false (narrow sidebar), hide the status text and use a status-icon tooltip. */
  showStatusLabel?: boolean;
  actions?: Snippet;
}

let { label, status, icon, onclick, showStatusLabel = true, actions }: Props = $props();

const statusKey = $derived((status || 'UNKNOWN').toUpperCase());
const statusLabel = $derived(capitalize(statusKey.toLowerCase().replaceAll('_', ' ')));
const loading = $derived(isLoadingStatus(statusKey));

function onActionsPointerDown(e: MouseEvent): void {
  // Keep the row from navigating when interacting with the kebab.
  e.stopPropagation();
}
</script>

<div class="group flex w-full items-center gap-0.5 px-2 py-0.5 min-w-0 hover:bg-[var(--pd-global-nav-icon-hover-bg)]">
  <button
    type="button"
    class="flex grow items-center gap-2 px-2 py-1 text-left min-w-0"
    title={showStatusLabel ? label : undefined}
    aria-label="{label}, {statusLabel}"
    {onclick}>
    {#if showStatusLabel}
      <span class="shrink-0 scale-90 origin-center" class:opacity-80={loading}>
        {#if loading}
          <span class="flex h-4 w-4 items-center justify-center" role="status" aria-label="Loading">
            <Spinner size="0.85em" />
          </span>
        {:else}
          <StatusIcon {icon} status={statusKey} size={12} />
        {/if}
      </span>
    {:else}
      <Tooltip tip={statusLabel} right>
        <span class="shrink-0 scale-90 origin-center" class:opacity-80={loading}>
          {#if loading}
            <span class="flex h-4 w-4 items-center justify-center" role="status" aria-label={statusLabel}>
              <Spinner size="0.85em" />
            </span>
          {:else}
            <StatusIcon {icon} status={statusKey} size={12} />
          {/if}
        </span>
      </Tooltip>
    {/if}
    <span class="truncate grow min-w-0">{label}</span>
    {#if showStatusLabel}
      <span
        class="shrink-0 text-[10px] font-medium uppercase tracking-wide text-[var(--pd-global-nav-icon)]"
        class:opacity-70={!loading}
        class:opacity-100={loading}
        class:text-[var(--pd-status-starting)]={loading}>
        {statusLabel}
      </span>
    {/if}
  </button>

  {#if actions}
    <!--
      Keep pointer-events enabled so the kebab stays reachable. Only fade with
      opacity — pointer-events-none made the hit-area fall through and clear
      :hover before the control could be clicked. Visibility is hover-only so
      icons do not stick after the menu closes.
    -->
    <div
      class="shrink-0 flex items-center w-7 justify-center opacity-0 group-hover:opacity-100 focus-within:opacity-100"
      role="presentation"
      onpointerdown={onActionsPointerDown}>
      {@render actions()}
    </div>
  {/if}
</div>
