/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Reactive status overlays for the Version 2 compact-nav sidebar.
// List rows are $derived from stores, so mutating actionInProgress/state on the
// UI object does not re-render the row — this map is the source of truth while
// a kebab status action is in flight (and briefly after, for the final state).

export const LOADING_STATUSES = new Set(['STARTING', 'STOPPING', 'RESTARTING', 'DELETING', 'UPDATING']);

/** Minimum time to keep a loading status visible in the prototype. */
export const PROTOTYPE_ACTION_MIN_MS = 1200;

/** How long to keep the final status before falling back to the live store. */
const FINAL_STATUS_HOLD_MS = 1500;

let overlays = $state<Record<string, string>>({});
const clearTimers = new Map<string, ReturnType<typeof setTimeout>>();

export function getActionStatusOverlay(id: string): string | undefined {
  return overlays[id];
}

export function displayResourceStatus(id: string, storeStatus: string): string {
  return overlays[id] ?? storeStatus;
}

export function isLoadingStatus(status: string): boolean {
  return LOADING_STATUSES.has((status || '').toUpperCase());
}

function setOverlay(id: string, status: string): void {
  const timer = clearTimers.get(id);
  if (timer) {
    clearTimeout(timer);
    clearTimers.delete(id);
  }
  overlays = { ...overlays, [id]: status };
}

function scheduleClear(id: string, delayMs: number): void {
  const existing = clearTimers.get(id);
  if (existing) clearTimeout(existing);
  clearTimers.set(
    id,
    setTimeout(() => {
      const rest = { ...overlays };
      delete rest[id];
      overlays = rest;
      clearTimers.delete(id);
    }, delayMs),
  );
}

/** Map a transitional loading status to the prototyped terminal status. */
export function finalStatusForLoading(loadingStatus: string): string | undefined {
  switch (loadingStatus.toUpperCase()) {
    case 'STARTING':
    case 'RESTARTING':
      return 'RUNNING';
    case 'STOPPING':
      return 'EXITED';
    case 'DELETING':
      return 'DELETING';
    default:
      return undefined;
  }
}

/**
 * Apply updates from ContainerActions / PodActions (actionInProgress + state).
 * While loading, pin the transitional status; when the action ends, show the
 * expected final status long enough to read, then clear so the store wins.
 */
export function applyActionUpdate(
  id: string,
  update: { actionInProgress?: boolean; state?: string; status?: string },
): void {
  const next = (update.state ?? update.status ?? '').toUpperCase();
  if (!next) return;

  if (update.actionInProgress && isLoadingStatus(next)) {
    setOverlay(id, next);
    return;
  }

  if (update.actionInProgress === false || !update.actionInProgress) {
    const previous = overlays[id];
    if (previous && isLoadingStatus(previous)) {
      if (next === 'ERROR') {
        setOverlay(id, 'ERROR');
        scheduleClear(id, FINAL_STATUS_HOLD_MS);
        return;
      }
      const finalStatus = finalStatusForLoading(previous) ?? next;
      setOverlay(id, finalStatus);
      // Deleting rows usually disappear from the store; clear the overlay either way.
      scheduleClear(id, previous === 'DELETING' ? 600 : FINAL_STATUS_HOLD_MS);
      return;
    }
    if (isLoadingStatus(next) || next === 'ERROR') {
      setOverlay(id, next);
      scheduleClear(id, FINAL_STATUS_HOLD_MS);
    }
  }
}

/** Simpler path for image/volume/network delete that only sets DELETING. */
export function applyDeletingUpdate(id: string): void {
  setOverlay(id, 'DELETING');
  scheduleClear(id, PROTOTYPE_ACTION_MIN_MS + 400);
}

export async function withPrototypeActionDelay<T>(action: () => Promise<T>): Promise<T> {
  const [result] = await Promise.all([
    action(),
    new Promise<void>(resolve => {
      setTimeout(resolve, PROTOTYPE_ACTION_MIN_MS);
    }),
  ]);
  return result;
}
