<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Bridges legacy `/compose/details/:name/:engineId/*` into a workspace tab.
import { findAnyTabForResource, openTab } from '/@/stores/layout/layout-store.svelte';
import { composeKey } from '/@/stores/layout/layout-types';
import { gotoListShell } from '/@/stores/layout/page-tab.svelte';

interface Props {
  composeName: string;
  engineId: string;
}

let { composeName, engineId }: Props = $props();

$effect(() => {
  if (!composeName || !engineId) return;
  const resourceId = composeKey(composeName, engineId);
  if (!findAnyTabForResource('compose', resourceId)) {
    openTab({ resourceType: 'compose', resourceId, subView: 'summary', title: `${composeName} · Summary` }, 'newTab');
  }
  gotoListShell();
});
</script>

<div class="h-full flex items-center justify-center text-[var(--pd-content-text)]">
  <i class="fas fa-spinner fa-spin mr-2"></i>Opening in Workspace…
</div>
