<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Section kebab for Version 2 compact-nav: mirrors production list-page
// header actions (Create / Prune / Pull / …) with the same labels and icons.
import { faArrowCircleDown, faCube, faPieChart, faPlusCircle, faUpload } from '@fortawesome/free-solid-svg-icons';
import { DropdownMenu } from '@podman-desktop/ui-svelte';

import type { EngineInfoUI } from '/@/lib/engine/EngineInfoUI';
import Prune from '/@/lib/engine/Prune.svelte';
import KubePlayIcon from '/@/lib/kube/KubePlayIcon.svelte';
import ListItemButtonIcon from '/@/lib/ui/ListItemButtonIcon.svelte';
import { containersInfos } from '/@/stores/containers';
import { imagesInfos } from '/@/stores/images';
import { podsInfos } from '/@/stores/pods';
import { providerInfos } from '/@/stores/providers';
import { fetchVolumesWithData, volumeListInfos } from '/@/stores/volumes';

import { openActionPageTab } from './action-open';

type SectionId = 'containers' | 'pods' | 'images' | 'volumes' | 'networks' | 'secrets';

interface Props {
  sectionId: SectionId;
}

let { sectionId }: Props = $props();

const providerConnections = $derived(
  $providerInfos
    .flatMap(provider => provider.containerConnections)
    .filter(connection => connection.status === 'started'),
);

const providerPodmanConnections = $derived(
  $providerInfos
    .flatMap(provider => provider.containerConnections)
    .filter(connection => connection.type === 'podman')
    .filter(connection => connection.status === 'started'),
);

function uniqueEngines(items: { engineName: string; engineId: string }[]): EngineInfoUI[] {
  const engines = items.map(item => ({ name: item.engineName, id: item.engineId }));
  return engines.filter((engine, index, self) => index === self.findIndex(t => t.name === engine.name));
}

const containerEngines = $derived(
  uniqueEngines($containersInfos.map(c => ({ engineName: c.engineName, engineId: c.engineId }))),
);
const podEngines = $derived(uniqueEngines($podsInfos.map(p => ({ engineName: p.engineName, engineId: p.engineId }))));
const imageEngines = $derived(
  uniqueEngines($imagesInfos.map(i => ({ engineName: i.engineName, engineId: i.engineId }))),
);
const volumeEngines = $derived(
  uniqueEngines(
    $volumeListInfos.flatMap(list => list.Volumes.map(v => ({ engineName: v.engineName, engineId: v.engineId }))),
  ),
);

const hasVolumes = $derived($volumeListInfos.some(list => list.Volumes.length > 0));

const hasActions = $derived.by(() => {
  switch (sectionId) {
    case 'containers':
    case 'images':
      return true;
    case 'pods':
      return $podsInfos.length > 0 || providerPodmanConnections.length > 0;
    case 'volumes':
      return hasVolumes || providerConnections.length > 0;
    case 'networks':
    case 'secrets':
      return providerConnections.length > 0;
  }
});

async function createContainer(): Promise<void> {
  // Same two choices as the production Create modal on Containers.
  const existing = 'Existing image';
  const dockerfile = 'Containerfile or Dockerfile';
  const result = await window.showMessageBox({
    title: 'Create a container',
    message: 'How do you want to create a container?',
    buttons: ['Cancel', existing, dockerfile],
  });
  if (result.response === existing) {
    openActionPageTab('create-container-existing');
  } else if (result.response === dockerfile) {
    openActionPageTab('build-image');
  }
}

function gotoPullImage(): void {
  openActionPageTab('pull-image');
}

function gotoBuildImage(): void {
  openActionPageTab('build-image');
}

function importImage(): void {
  openActionPageTab('import-images');
}

function loadImages(): void {
  openActionPageTab('load-images');
}

function gotoCreateVolume(): void {
  openActionPageTab('create-volume');
}

async function gatherVolumeSizes(): Promise<void> {
  await fetchVolumesWithData();
}

function runPodmanKubePlay(): void {
  openActionPageTab('kube-play');
}

function gotoCreateNetwork(): void {
  openActionPageTab('create-network');
}

function gotoCreateSecret(): void {
  openActionPageTab('create-secret');
}
</script>

{#if hasActions}
  <div
    class="shrink-0 flex items-center w-7 justify-center [&_button]:!p-1 [&_button]:text-[var(--pd-global-nav-icon)] [&_button]:hover:text-[var(--pd-global-nav-icon-hover)] [&_button]:hover:bg-[var(--pd-global-nav-icon-hover-bg)]"
    role="presentation"
    onpointerdown={(e: MouseEvent): void => e.stopPropagation()}>
    <DropdownMenu title="{sectionId} actions">
      {#if sectionId === 'containers'}
        {#if $containersInfos.length > 0}
          <Prune type="containers" engines={containerEngines} asMenuItem={true} />
        {/if}
        <ListItemButtonIcon title="Create" onClick={createContainer} menu={true} icon={faPlusCircle} />
      {:else if sectionId === 'pods'}
        {#if $podsInfos.length > 0}
          <Prune type="pods" engines={podEngines} asMenuItem={true} />
        {/if}
        {#if providerPodmanConnections.length > 0}
          <DropdownMenu.Item
            title="Podman kube play"
            tooltip="Create containers, pods and volumes based on Kubernetes YAML"
            icon={KubePlayIcon}
            onClick={runPodmanKubePlay} />
        {/if}
      {:else if sectionId === 'images'}
        {#if $imagesInfos.length > 0}
          <Prune type="images" engines={imageEngines} asMenuItem={true} />
        {/if}
        <ListItemButtonIcon
          title="Load"
          tooltip="Load Images From Tar Archives"
          onClick={loadImages}
          menu={true}
          icon={faUpload} />
        <ListItemButtonIcon
          title="Import"
          tooltip="Import Containers From Filesystem"
          onClick={importImage}
          menu={true}
          icon={faArrowCircleDown} />
        <ListItemButtonIcon
          title="Pull"
          tooltip="Pull Image From a Registry"
          onClick={gotoPullImage}
          menu={true}
          icon={faArrowCircleDown} />
        <ListItemButtonIcon
          title="Build"
          tooltip="Build Image From Containerfile"
          onClick={gotoBuildImage}
          menu={true}
          icon={faCube} />
      {:else if sectionId === 'volumes'}
        {#if hasVolumes}
          <Prune type="volumes" engines={volumeEngines} asMenuItem={true} />
          <ListItemButtonIcon
            title="Gather volume sizes"
            tooltip="Gather sizes for volumes. It can take a while..."
            onClick={gatherVolumeSizes}
            menu={true}
            icon={faPieChart} />
        {/if}
        {#if providerConnections.length > 0}
          <ListItemButtonIcon
            title="Create"
            tooltip="Create a volume"
            onClick={gotoCreateVolume}
            menu={true}
            icon={faPlusCircle} />
        {/if}
      {:else if sectionId === 'networks'}
        <ListItemButtonIcon
          title="Create"
          tooltip="Create a network"
          onClick={gotoCreateNetwork}
          menu={true}
          icon={faPlusCircle} />
      {:else if sectionId === 'secrets'}
        <ListItemButtonIcon
          title="Create"
          tooltip="Create a secret"
          onClick={gotoCreateSecret}
          menu={true}
          icon={faPlusCircle} />
      {/if}
    </DropdownMenu>
  </div>
{:else}
  <span class="shrink-0 w-7" aria-hidden="true"></span>
{/if}
