<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Bridges the legacy `/containers/:id/*` deep link to the single, persistent
// tabbed workspace at `/workspace`: makes sure a tab for this container
// exists (opening one as a fallback for direct/deep links), then redirects
// there so the tab strip and its content are visible from the one shared
// workspace destination regardless of which resource type the user came
// from. If a list row already opened this exact tab (see
// ContainerColumnNameContainer.svelte), openTab() here is a no-op focus
// rather than a duplicate open, since tabs are deduplicated by key.
import { router } from 'tinro';

import { ContainerUtils } from '/@/lib/container/container-utils';
import { containersInfos } from '/@/stores/containers';
import { findAnyTabForResource, openTab } from '/@/stores/layout/layout-store.svelte';

interface Props {
  containerID: string;
}

let { containerID }: Props = $props();

const containerUtils = new ContainerUtils();

let container = $derived.by(() => {
  const found = $containersInfos.find(c => c.Id === containerID);
  return found ? containerUtils.getContainerInfoUI(found) : undefined;
});

$effect(() => {
  if (!container) return;
  if (!findAnyTabForResource('container', container.id)) {
    openTab(
      { resourceType: 'container', resourceId: container.id, subView: 'summary', title: `${container.name} · Summary` },
      'replace',
    );
  }
  router.goto('/workspace');
});
</script>

<div class="h-full flex items-center justify-center text-[var(--pd-content-text)]">
  <i class="fas fa-spinner fa-spin mr-2"></i>Opening in Workspace…
</div>
