<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Redesigned Container "Summary" tab content - see PodSummaryTabContent for the same treatment
// applied to pods. Keeps every fact the old ContainerDetailsSummary table showed (image, ports,
// labels, pod/compose group) but groups them into scannable cards instead of one long table.
import { faExternalLink } from '@fortawesome/free-solid-svg-icons';
import { Link, Tooltip } from '@podman-desktop/ui-svelte';
import { ContainerIcon, Icon } from '@podman-desktop/ui-svelte/icons';
import { router } from 'tinro';

import type { ContainerInfoUI } from '/@/lib/container/ContainerInfoUI';
import { ContainerGroupInfoTypeUI } from '/@/lib/container/ContainerInfoUI';

import ResourceSummaryHeader from './summary/ResourceSummaryHeader.svelte';
import SummaryCard from './summary/SummaryCard.svelte';

interface Props {
  container: ContainerInfoUI;
}

let { container }: Props = $props();

const startedTime = $derived(new Date(container.startedAt));
const createdTime = $derived(container.groupInfo.created ? new Date(container.groupInfo.created) : undefined);
const labelEntries = $derived(Object.entries(container.labels));

function portUrl(port: number): string {
  return `http://localhost:${port}`;
}

function openPort(port: number): void {
  window.openExternal(portUrl(port)).catch((err: unknown) => console.error(`Error opening port ${port}`, err));
}
</script>

<div class="flex flex-col gap-4 px-5 py-4">
  <ResourceSummaryHeader
    name={container.name}
    status={container.state}
    statusLabel={container.state.toLowerCase()}
    icon={ContainerIcon}
    id={container.id}
    created={createdTime}
    age={container.uptime || undefined} />

  <SummaryCard title="Details" icon="fas fa-circle-info">
    <div class="flex flex-col gap-2 px-4 pb-3 text-sm">
      <div class="flex items-center justify-between gap-3">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60 shrink-0">Image</span>
        <Link class="truncate" on:click={(): void => router.goto(container.imageHref ?? $router.path)}>
          {container.image}
        </Link>
      </div>
      {#if container.command}
        <div class="flex items-center justify-between gap-3">
          <span class="text-xs text-[var(--pd-content-text)] opacity-60 shrink-0">Command</span>
          <span class="text-[var(--pd-content-header)] font-mono text-xs truncate" title={container.command}>
            {container.command}
          </span>
        </div>
      {/if}
      <div class="flex items-center justify-between gap-3">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60 shrink-0">Engine</span>
        <span class="text-[var(--pd-content-header)]">{container.engineType}</span>
      </div>
      {#if container.uptime}
        <div class="flex items-center justify-between gap-3">
          <span class="text-xs text-[var(--pd-content-text)] opacity-60 shrink-0">Started</span>
          <span class="text-[var(--pd-content-header)]">{startedTime.toLocaleString()}</span>
        </div>
      {/if}
    </div>
  </SummaryCard>

  {#if container.hasPublicPort}
    <SummaryCard title="Network" icon="fas fa-network-wired">
      <div class="divide-y divide-[var(--pd-content-divider)]">
        {#each container.ports as port, i (`${port.IP ?? ''}-${port.PublicPort}-${port.Type}-${i}`)}
          <div class="flex items-center justify-between px-4 py-2 text-sm">
            <span class="text-[var(--pd-content-text)] opacity-80">{port.Type}</span>
            <Tooltip tip={portUrl(port.PublicPort)} bottom>
              <Link on:click={(): void => openPort(port.PublicPort)}>
                <span class="inline-flex items-center gap-1 font-mono text-xs">
                  localhost:{port.PublicPort} → {port.PrivatePort}
                  <Icon icon={faExternalLink} class="w-2.5 text-[10px]" />
                </span>
              </Link>
            </Tooltip>
          </div>
        {/each}
      </div>
    </SummaryCard>
  {/if}

  {#if container.groupInfo.type !== ContainerGroupInfoTypeUI.STANDALONE}
    <SummaryCard title={container.groupInfo.type === ContainerGroupInfoTypeUI.POD ? 'Pod' : 'Compose project'} icon="fas fa-layer-group">
      <div class="flex flex-col gap-2 px-4 pb-3 text-sm">
        <div class="flex items-center justify-between gap-3">
          <span class="text-xs text-[var(--pd-content-text)] opacity-60 shrink-0">Name</span>
          <span class="text-[var(--pd-content-header)] truncate">{container.groupInfo.name}</span>
        </div>
        {#if container.groupInfo.status}
          <div class="flex items-center justify-between gap-3">
            <span class="text-xs text-[var(--pd-content-text)] opacity-60 shrink-0">Status</span>
            <span class="text-[var(--pd-content-header)] lowercase">{container.groupInfo.status}</span>
          </div>
        {/if}
      </div>
    </SummaryCard>
  {/if}

  {#if labelEntries.length > 0}
    <SummaryCard title="Labels" icon="fas fa-tags">
      <div class="flex flex-wrap gap-1.5 px-4 pb-3">
        {#each labelEntries as [key, value] (key)}
          <span
            class="text-xs font-mono px-2 py-1 rounded-md bg-[var(--pd-content-bg)] border border-[var(--pd-content-divider)] text-[var(--pd-content-text)]">
            {key}={value}
          </span>
        {/each}
      </div>
    </SummaryCard>
  {/if}
</div>
