<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Renders one container sub-view (Summary/Logs/Inspect/Terminal/Tty/Kube)
// inside a workspace tab, reusing the same leaf components the pre-existing
// (non-tabbed) ContainerDetails.svelte uses.
import { ContainerUtils } from '/@/lib/container/container-utils';
import ContainerDetailsInspect from '/@/lib/container/ContainerDetailsInspect.svelte';
import ContainerDetailsKube from '/@/lib/container/ContainerDetailsKube.svelte';
import ContainerDetailsLogs from '/@/lib/container/ContainerDetailsLogs.svelte';
import ContainerDetailsTerminal from '/@/lib/container/ContainerDetailsTerminal.svelte';
import ContainerDetailsTtyTerminal from '/@/lib/container/ContainerDetailsTtyTerminal.svelte';
import { containersInfos } from '/@/stores/containers';
import { markTabStale } from '/@/stores/layout/layout-store.svelte';
import type { ContainerSubView } from '/@/stores/layout/layout-types';

import ContainerSummaryTabContent from './ContainerSummaryTabContent.svelte';
import MockResourceStats from './MockResourceStats.svelte';
import StaleTabPlaceholder from './StaleTabPlaceholder.svelte';

interface Props {
  tabId: string;
  containerId: string;
  subView?: ContainerSubView;
}

let { tabId, containerId, subView = 'summary' }: Props = $props();

const containerUtils = new ContainerUtils();

let container = $derived.by(() => {
  const found = $containersInfos.find(c => c.Id === containerId);
  return found ? containerUtils.getContainerInfoUI(found) : undefined;
});

$effect(() => {
  markTabStale(tabId, !container);
});
</script>

{#if container}
  <div class="flex flex-col h-full min-h-0">
    <div class="grow min-h-0 overflow-auto">
      {#if subView === 'summary'}
        <MockResourceStats resourceId={container.id} kind="container" running={container.state === 'RUNNING'} />
        <ContainerSummaryTabContent {tabId} container={container} />
      {:else if subView === 'inspect'}
        <ContainerDetailsInspect container={container} />
      {:else if subView === 'kube'}
        <ContainerDetailsKube container={container} />
      {:else if subView === 'terminal'}
        <ContainerDetailsTerminal container={container} />
      {:else if subView === 'tty'}
        <ContainerDetailsTtyTerminal container={container} />
      {:else}
        <ContainerDetailsLogs container={container} />
      {/if}
    </div>
  </div>
{:else}
  <StaleTabPlaceholder resourceLabel="Container" tabId={tabId} />
{/if}
