<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
import { EmptyScreen } from '@podman-desktop/ui-svelte';

import { currentScreen } from '/@/stores/prototype';
</script>

<div class="flex h-full w-full items-center justify-center p-6">
  <EmptyScreen
    icon="fas fa-flask"
    title="Future idea — coming later"
    message="This prototype screen is reserved for the next concept. Switch back to Tabs & Flexible Layout in the titlebar to explore the current tabs experience.">
    <button
      type="button"
      class="mt-4 px-3 py-1.5 rounded-sm bg-[var(--pd-button-primary-bg)] text-[var(--pd-button-primary-text)] text-sm"
      onclick={(): void => currentScreen.set('tabs-layout')}>
      Show Tabs & Flexible Layout
    </button>
  </EmptyScreen>
</div>
