<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Persistent global tab strip: first tab is always the current app page
// (never closable; title tracks the page name). Remaining tabs are open
// resource views. Mounted at the App root on every non-preferences page.
import { TabBar } from '@podman-desktop/ui-svelte';
import { router } from 'tinro';

import {
  canMoveTabToNewSection,
  closeAllTabsEverywhere,
  closeAllTabsExcept,
  closeTabById,
  findLeaf,
  findLeafContainingTab,
  getAllTabsOrdered,
  layoutState,
  moveToNewPanelAnyPanel,
  pinToggle,
  reorderTabGlobal,
  selectTabAnyPanel,
  splitDownAnyPanel,
  splitRightAnyPanel,
} from '/@/stores/layout/layout-store.svelte';
import type { WorkspaceTab } from '/@/stores/layout/layout-types';
import {
  getPageTab,
  isPageTabId,
  isPageTabSelected,
  markResourceTabActive,
  PAGE_TAB_ID,
  selectPageTab,
} from '/@/stores/layout/page-tab.svelte';

import LayoutToolbar from './LayoutToolbar.svelte';
import NewTabPalette from './NewTabPalette.svelte';

let resourceTabs = $derived(getAllTabsOrdered());
let pageTab = $derived(getPageTab());
let tabs = $derived([pageTab, ...resourceTabs]);
let activeTabId = $derived(
  isPageTabSelected()
    ? PAGE_TAB_ID
    : (findLeaf(layoutState.tree, layoutState.focusedPanelId)?.activeTabId ?? PAGE_TAB_ID),
);

let newTabPaletteFor: { panelId: string; activeTab: WorkspaceTab | undefined } | undefined = $state();

function onSelect(tabId: string): void {
  if (isPageTabId(tabId)) {
    selectPageTab();
    return;
  }
  markResourceTabActive();
  selectTabAnyPanel(tabId);
  router.goto('/workspace');
}

function onClose(tabId: string): void {
  if (isPageTabId(tabId)) return;
  closeTabById(tabId);
}

function onCloseOthers(tabId: string): void {
  if (isPageTabId(tabId)) {
    closeAllTabsEverywhere();
    selectPageTab();
    return;
  }
  closeAllTabsExcept(tabId);
}

function onCloseAll(): void {
  closeAllTabsEverywhere();
  selectPageTab();
}

function onPin(tabId: string): void {
  if (isPageTabId(tabId)) return;
  pinToggle('global-tab-bar', tabId);
}

function onReorder(tabId: string, beforeTabId: string | undefined): void {
  if (isPageTabId(tabId) || isPageTabId(beforeTabId)) return;
  reorderTabGlobal(tabId, beforeTabId);
}

function onMoveFromOther(_sourcePanelId: string, tabId: string, beforeTabId: string | undefined): void {
  if (isPageTabId(tabId) || isPageTabId(beforeTabId)) return;
  reorderTabGlobal(tabId, beforeTabId);
}

function onSplitRight(tabId: string): void {
  if (isPageTabId(tabId)) return;
  splitRightAnyPanel(tabId);
  markResourceTabActive();
  router.goto('/workspace');
}

function onSplitDown(tabId: string): void {
  if (isPageTabId(tabId)) return;
  splitDownAnyPanel(tabId);
  markResourceTabActive();
  router.goto('/workspace');
}

function onMoveToNewPanel(tabId: string): void {
  if (isPageTabId(tabId)) return;
  moveToNewPanelAnyPanel(tabId);
  markResourceTabActive();
  router.goto('/workspace');
}

function openNewTabPalette(): void {
  const focusedActive = findLeaf(layoutState.tree, layoutState.focusedPanelId)?.activeTabId;
  const activeTab = focusedActive ? layoutState.tabs[focusedActive] : undefined;
  const panelId =
    (focusedActive && findLeafContainingTab(layoutState.tree, focusedActive)?.id) ?? layoutState.focusedPanelId;
  newTabPaletteFor = { panelId, activeTab };
}

function closeNewTabPalette(opened?: boolean): void {
  newTabPaletteFor = undefined;
  if (opened) {
    markResourceTabActive();
    router.goto('/workspace');
  }
}
</script>

<!-- Page tab always present — strip never empty. -->
<TabBar
  panelId="global-tab-bar"
  {tabs}
  {activeTabId}
  {onSelect}
  onClose={onClose}
  onCloseOthers={onCloseOthers}
  onCloseAllInPanel={onCloseAll}
  onPinToggle={onPin}
  onReorder={onReorder}
  onMoveFromOtherPanel={onMoveFromOther}
  onSplitRight={onSplitRight}
  onSplitDown={onSplitDown}
  onMoveToNewPanel={onMoveToNewPanel}
  canOpenInNewSection={canMoveTabToNewSection}
  onAddTab={openNewTabPalette}>
  {#snippet trailing()}
    <!-- Gear only — "+" lives next to the last tab via TabBar onAddTab. -->
    <LayoutToolbar />
  {/snippet}
</TabBar>

{#if newTabPaletteFor}
  <NewTabPalette
    panelId={newTabPaletteFor.panelId}
    activeTab={newTabPaletteFor.activeTab}
    onClose={closeNewTabPalette} />
{/if}
