<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// The one persistent tab strip for the whole app: mounted once at the App
// root (see App.svelte), so it's visible on every page - Dashboard,
// Containers, Pods, Images, etc. - not just while inside the /workspace
// route. This is what lets a tab opened from a Pod stay reachable while
// you're browsing Images, without a dedicated "Workspace" destination to
// remember.
//
// It shows every open tab as a single flat, ordered list, regardless of
// which split/panel holds it inside the workspace - splits still exist there
// for side-by-side viewing, but from anywhere else in the app there's only
// ever one thing to reason about: "here's everything I have open".
import { TabBar } from '@podman-desktop/ui-svelte';
import { router } from 'tinro';

import {
  activeTabIdOfFocusedPanel,
  closeAllTabsEverywhere,
  closeAllTabsExcept,
  closeTabById,
  getAllTabsOrdered,
  moveToNewPanelAnyPanel,
  pinToggle,
  reorderTabGlobal,
  selectTabAnyPanel,
  splitDownAnyPanel,
  splitRightAnyPanel,
} from '/@/stores/layout/layout-store.svelte';

import LayoutToolbar from './LayoutToolbar.svelte';

let tabs = $derived(getAllTabsOrdered());
let activeTabId = $derived(activeTabIdOfFocusedPanel());

function onSelect(tabId: string): void {
  selectTabAnyPanel(tabId);
  router.goto('/workspace');
}
</script>

<!-- Always rendered - even with zero tabs open - so the Layout settings button in `trailing`
     stays reachable as the entry point for starting a layout in the first place (new layout,
     a built-in preset, importing one, or the agent demo). -->
<TabBar
  panelId="global-tab-bar"
  {tabs}
  {activeTabId}
  {onSelect}
  onClose={closeTabById}
  onCloseOthers={closeAllTabsExcept}
  onCloseAllInPanel={closeAllTabsEverywhere}
  onPinToggle={(tabId): void => pinToggle('global-tab-bar', tabId)}
  onReorder={reorderTabGlobal}
  onMoveFromOtherPanel={(_sourcePanelId, tabId, beforeTabId): void => reorderTabGlobal(tabId, beforeTabId)}
  onSplitRight={splitRightAnyPanel}
  onSplitDown={splitDownAnyPanel}
  onMoveToNewPanel={moveToNewPanelAnyPanel}>
  {#snippet trailing()}
    <LayoutToolbar />
  {/snippet}
</TabBar>
