<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Redesigned Image "Summary" tab content - see PodSummaryTabContent for the same treatment
// applied to pods. In addition to a scannable header/cards layout, this surfaces something the
// old ImageDetailsSummary never did: which of the containers you actually have are running this
// exact image (real data, cross-referenced from the container store by ImageID) - "am I allowed
// to delete this image" is one of the first questions an image detail view should answer.
import type { ManifestInspectInfo } from '@podman-desktop/api';
import { onMount } from 'svelte';

import { ImageUtils } from '/@/lib/image/image-utils';
import ImageDetailsInspect from '/@/lib/image/ImageDetailsInspect.svelte';
import type { ImageInfoUI } from '/@/lib/image/ImageInfoUI';
import { containersInfos } from '/@/stores/containers';
import { imageKey } from '/@/stores/layout/layout-types';

import MockResourceStats from './MockResourceStats.svelte';
import EnvironmentField from './summary/EnvironmentField.svelte';
import InspectCard from './summary/InspectCard.svelte';
import OverviewField from './summary/OverviewField.svelte';
import ResourceSummaryHeader from './summary/ResourceSummaryHeader.svelte';
import SummaryCard from './summary/SummaryCard.svelte';

interface Props {
  tabId: string;
  image: ImageInfoUI;
}

let { tabId, image }: Props = $props();

const imageUtils = new ImageUtils();

const STATUS_LABEL: Record<ImageInfoUI['status'], string> = {
  USED: 'used',
  UNUSED: 'unused',
  DELETING: 'deleting',
};

// image.createdAt is a Unix *seconds* timestamp (see image-utils.ts's own use of
// moment.unix(created)) - Date() expects milliseconds.
const createdDate = $derived(new Date(image.createdAt * 1000));

const usedByContainers = $derived($containersInfos.filter(c => c.ImageID === image.id));

const labelEntries = $derived(Object.entries(image.labels ?? {}));

let manifestDetails: ManifestInspectInfo | undefined = $state();
// Distinguishes "not a manifest list, nothing to show" (manifestError stays undefined, card is
// skipped entirely below) from "is a manifest list but the fetch itself failed" - previously a
// failed inspectManifest() call was only console.error'd, so the Manifest details card just
// silently never appeared with no way to tell the difference from the first, common case.
let manifestError: string | undefined = $state();

async function loadManifest(): Promise<void> {
  if (!image.isManifest) return;
  manifestError = undefined;
  try {
    manifestDetails = await window.inspectManifest(image.engineId, image.id);
  } catch (err) {
    manifestError = err instanceof Error ? err.message : String(err);
  }
}

onMount(loadManifest);
</script>

<div class="flex flex-col gap-4 px-5 py-4">
  <ResourceSummaryHeader
    name="{image.name}:{image.tag}"
    status={image.status}
    statusLabel={STATUS_LABEL[image.status]}
    icon={image.icon ?? 'fas fa-cube'}
    id={image.id}
    created={createdDate}
    age={image.age} />

  <MockResourceStats
    resourceId={imageKey(image.id, image.engineId, image.base64RepoTag)}
    kind="image"
    imageName={image.name}
    imageDigest={image.id} />

  <!-- Same columns as the production Images table (minus Actions). -->
  <SummaryCard title="Overview" icon="fas fa-table-list">
    <div class="grid grid-cols-2 sm:grid-cols-3 gap-3 px-4 pb-3">
      <OverviewField label="Status" value={STATUS_LABEL[image.status]} />
      <EnvironmentField engineId={image.engineId} />
      <OverviewField label="Age" value={image.age || 'N/A'} />
      <OverviewField label="Size" value={image.humanSize} />
      <OverviewField label="Arch" value={image.arch} />
      {#if image.digest}
        <OverviewField label="Digest" value={imageUtils.getShortId(image.digest)} title={image.digest} />
      {/if}
    </div>
  </SummaryCard>

  <SummaryCard title="Used by">
    {#snippet trailing()}
      {usedByContainers.length} container{usedByContainers.length === 1 ? '' : 's'}
    {/snippet}
    {#if usedByContainers.length > 0}
      <div class="divide-y divide-[var(--pd-content-divider)]">
        {#each usedByContainers as container (container.Id)}
          <div class="flex items-center justify-between px-4 py-2 text-sm">
            <span class="text-[var(--pd-content-text)] opacity-80 truncate">{container.Names[0]?.replace(/^\//, '')}</span>
            <span class="text-xs text-[var(--pd-content-text)] opacity-60 lowercase">{container.State}</span>
          </div>
        {/each}
      </div>
    {:else}
      <div class="px-4 pb-3 text-sm text-[var(--pd-content-text)] opacity-60">
        No containers are currently using this image - it's safe to remove.
      </div>
    {/if}
  </SummaryCard>

  <InspectCard
    resourceType="image"
    resourceId={imageKey(image.id, image.engineId, image.base64RepoTag)}
    resourceTitle="{image.name}:{image.tag}"
    {tabId}>
    <ImageDetailsInspect image={image} />
  </InspectCard>

  {#if labelEntries.length > 0}
    <SummaryCard title="Labels" icon="fas fa-tags">
      <div class="flex flex-wrap gap-1.5 px-4 pb-3">
        {#each labelEntries as [key, value] (key)}
          <span
            class="text-xs font-mono px-2 py-1 rounded-md bg-[var(--pd-content-bg)] border border-[var(--pd-content-divider)] text-[var(--pd-content-text)] break-all min-w-0 max-w-full">
            {key}={value}
          </span>
        {/each}
      </div>
    </SummaryCard>
  {/if}

  {#if manifestError}
    <SummaryCard title="Manifest details" icon="fas fa-layer-group">
      <div class="flex items-center justify-between gap-3 px-4 pb-3 text-sm">
        <span class="flex items-center gap-2 text-[var(--pd-state-error)]">
          <i class="fas fa-triangle-exclamation" aria-hidden="true"></i>
          Couldn't load manifest details: {manifestError}
        </span>
        <button
          type="button"
          class="shrink-0 text-[var(--pd-link)] hover:underline"
          onclick={loadManifest}>
          Retry
        </button>
      </div>
    </SummaryCard>
  {:else if manifestDetails && manifestDetails.manifests.length > 0}
    <SummaryCard title="Manifest details" icon="fas fa-layer-group">
      <div class="divide-y divide-[var(--pd-content-divider)]">
        {#each manifestDetails.manifests as manifest (manifest.digest)}
          <div class="px-4 py-2.5 flex flex-col gap-1">
            <span class="text-sm font-medium text-[var(--pd-content-header)] font-mono">
              {imageUtils.getShortId(manifest.digest)}
            </span>
            <span class="text-xs text-[var(--pd-content-text)] opacity-70">
              {manifest.platform.os}/{manifest.platform.architecture}{manifest.platform.variant
                ? `/${manifest.platform.variant}`
                : ''} · {manifest.mediaType} · {imageUtils.getHumanSize(manifest.size)}
            </span>
          </div>
        {/each}
      </div>
    </SummaryCard>
  {/if}
</div>
