<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Renders one image sub-view (Summary/History/Inspect) inside a workspace
// tab, reusing the leaf components the pre-existing (non-tabbed)
// ImageDetails.svelte uses.
import type { ViewInfoUI } from '@podman-desktop/core-api';

import { ImageUtils } from '/@/lib/image/image-utils';
import ImageDetailsHistory from '/@/lib/image/ImageDetailsHistory.svelte';
import ImageDetailsInspect from '/@/lib/image/ImageDetailsInspect.svelte';
import {
  IMAGE_DETAILS_VIEW_BADGES,
  IMAGE_DETAILS_VIEW_ICONS,
  IMAGE_VIEW_BADGES,
  IMAGE_VIEW_ICONS,
} from '/@/lib/view/views';
import { containersInfos } from '/@/stores/containers';
import { context } from '/@/stores/context';
import { imagesInfos } from '/@/stores/images';
import { markTabStale } from '/@/stores/layout/layout-store.svelte';
import type { ImageSubView } from '/@/stores/layout/layout-types';
import { imageKey } from '/@/stores/layout/layout-types';
import { viewsContributions } from '/@/stores/views';

import ImageSummaryTabContent from './ImageSummaryTabContent.svelte';
import MockResourceStats from './MockResourceStats.svelte';
import StaleTabPlaceholder from './StaleTabPlaceholder.svelte';

interface Props {
  tabId: string;
  imageId: string;
  engineId: string;
  base64RepoTag: string;
  subView?: ImageSubView;
}

let { tabId, imageId, engineId, base64RepoTag, subView = 'summary' }: Props = $props();

const imageUtils = new ImageUtils();

let viewContributions: ViewInfoUI[] = $derived(
  $viewsContributions.filter(
    view =>
      view.viewId === IMAGE_DETAILS_VIEW_ICONS ||
      view.viewId === IMAGE_VIEW_ICONS ||
      view.viewId === IMAGE_VIEW_BADGES ||
      view.viewId === IMAGE_DETAILS_VIEW_BADGES,
  ),
);

let imageInfo = $derived($imagesInfos.find(c => c.Id === imageId && c.engineId === engineId));
let image = $derived.by(() =>
  imageInfo
    ? imageUtils.getImageInfoUI(imageInfo, base64RepoTag, $containersInfos, $context, viewContributions)
    : undefined,
);

$effect(() => {
  markTabStale(tabId, !image);
});
</script>

{#if image}
  <div class="flex flex-col h-full min-h-0">
    <div class="grow min-h-0 overflow-auto">
      {#if subView === 'history'}
        <ImageDetailsHistory image={image} />
      {:else if subView === 'inspect'}
        <ImageDetailsInspect image={image} />
      {:else}
        <MockResourceStats
          resourceId={imageKey(image.id, image.engineId, base64RepoTag)}
          kind="image"
          imageName={image.name}
          imageDigest={image.id} />
        <ImageSummaryTabContent {tabId} image={image} />
      {/if}
    </div>
  </div>
{:else}
  <StaleTabPlaceholder resourceLabel="Image" tabId={tabId} />
{/if}
