<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Bridges the legacy `/images/:id/:engineId/:base64RepoTag/*` deep link to
// the single, persistent tabbed workspace at `/workspace`. See
// ContainerWorkspaceEntry.svelte for the general pattern.
import { router } from 'tinro';

import { ImageUtils } from '/@/lib/image/image-utils';
import { containersInfos } from '/@/stores/containers';
import { context } from '/@/stores/context';
import { imagesInfos } from '/@/stores/images';
import { findAnyTabForResource, openTab } from '/@/stores/layout/layout-store.svelte';
import { imageKey } from '/@/stores/layout/layout-types';

interface Props {
  imageID: string;
  engineId: string;
  base64RepoTag: string;
}

let { imageID, engineId, base64RepoTag }: Props = $props();

const imageUtils = new ImageUtils();

let imageInfo = $derived($imagesInfos.find(c => c.Id === imageID && c.engineId === engineId));
let image = $derived.by(() =>
  imageInfo ? imageUtils.getImageInfoUI(imageInfo, base64RepoTag, $containersInfos, $context, []) : undefined,
);

$effect(() => {
  if (!image) return;
  const resourceId = imageKey(image.id, image.engineId, image.base64RepoTag);
  if (!findAnyTabForResource('image', resourceId)) {
    openTab({ resourceType: 'image', resourceId, subView: 'summary', title: `${image.name} · Summary` }, 'replace');
  }
  router.goto('/workspace');
});
</script>

<div class="h-full flex items-center justify-center text-[var(--pd-content-text)]">
  <i class="fas fa-spinner fa-spin mr-2"></i>Opening in Workspace…
</div>
