<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Shared layout settings gear — shown once on the last section's tab bar
// (see WorkspaceLayout trailing). Per-section close uses CloseSectionButton.
import { faFloppyDisk, faFolderOpen, faGear, faPlus, faXmark } from '@fortawesome/free-solid-svg-icons';
import { Button, DropdownMenu } from '@podman-desktop/ui-svelte';
import { Icon } from '@podman-desktop/ui-svelte/icons';

import Dialog from '/@/lib/dialogs/Dialog.svelte';
import { saveNamedLayout } from '/@/stores/layout/layout-persistence.svelte';
import { type PresetId, PRESETS } from '/@/stores/layout/layout-presets';
import { closeAllTabsEverywhere, countLeaves, hasAnyTabs, layoutState } from '/@/stores/layout/layout-store.svelte';

import { autofocus } from './autofocus';
import ManageLayoutsModal from './ManageLayoutsModal.svelte';
import PresetPickerModal from './PresetPickerModal.svelte';

interface Props {
  /** Section that owns this gear (last leaf). Presets open relative to it. */
  panelId?: string;
  /** When this bar has no tabs of its own, TabBar skips its usual inline "+" entirely (there's
   * no tab strip left to put it in) - passing this renders an equivalent "+" right next to the
   * gear so there's still a one-click way to open a first tab instead of only a menu. */
  onAddTab?: () => void;
}

let { panelId, onAddTab }: Props = $props();

const multiSection = $derived(countLeaves(layoutState.tree) > 1);
const closeActionTitle = $derived(multiSection ? 'Close all sections' : 'Close all tabs');
const hasTabs = $derived(hasAnyTabs());

let showMenu = $state(false);
let menuAnchor = $state<HTMLButtonElement>();
let menuEl = $state<HTMLDivElement>();
let clientX = $state(0);
let clientY = $state(0);
// Hidden (off-screen + invisible) until positionMenu() below has measured the menu's real size
// and placed it - avoids a one-frame flash at the top-left corner.
let menuStyle = $state('top: -9999px; left: -9999px; visibility: hidden;');

let showSaveDialog = $state(false);
let saveName = $state('');
let activePreset: PresetId | undefined = $state();
let showManageModal = $state(false);

// Closing the "Save Layout As" dialog was previously the only feedback a successful save gave -
// the saved name only ever showed up later, inside "Manage Layouts…", if you went looking for
// it. A brief self-dismissing toast confirms the save actually happened, right where it happened.
let saveToastMessage: string | undefined = $state();
let saveToastTimeout: ReturnType<typeof setTimeout> | undefined;

function toggleMenu(event: MouseEvent): void {
  const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
  clientX = rect.left;
  clientY = rect.bottom;
  showMenu = !showMenu;
  if (showMenu) {
    // Reset to hidden before the effect below re-measures and re-places the (freshly mounted)
    // menu - otherwise it would flash at wherever it was left positioned last time it was open.
    menuStyle = 'top: -9999px; left: -9999px; visibility: hidden;';
  }
}

// Panel.svelte clips overflow at the split boundary. Position this menu with
// `position: fixed` so it floats over neighboring sections.
$effect(() => {
  if (!showMenu || !menuEl) return;
  const rect = menuEl.getBoundingClientRect();
  const margin = 8;

  let top = clientY + margin;
  if (top + rect.height > window.innerHeight - margin) {
    top = Math.max(margin, clientY - rect.height - 40);
  }

  let left = clientX;
  if (left + rect.width > window.innerWidth - margin) {
    left = Math.max(margin, window.innerWidth - rect.width - margin);
  }

  menuStyle = `top: ${top}px; left: ${left}px; visibility: visible;`;
});

function handleEscape({ key }: KeyboardEvent): void {
  if (key === 'Escape') showMenu = false;
}

function onWindowClick(e: MouseEvent): void {
  const target = e.target;
  if (target instanceof Node && (menuAnchor?.contains(target) || menuEl?.contains(target))) return;
  showMenu = false;
}

function closeAllAction(): void {
  showMenu = false;
  if (!hasTabs) return;
  closeAllTabsEverywhere();
}

function openSaveDialog(): void {
  showMenu = false;
  if (!hasTabs) return;
  saveName = '';
  showSaveDialog = true;
}

function confirmSave(): void {
  const name = saveName.trim();
  if (!name) return;
  saveNamedLayout(name);
  showSaveDialog = false;

  saveToastMessage = `Saved as "${name}"`;
  clearTimeout(saveToastTimeout);
  saveToastTimeout = setTimeout(() => {
    saveToastMessage = undefined;
  }, 3000);
}

function pickPreset(id: PresetId): void {
  showMenu = false;
  activePreset = id;
}

function openManageModal(): void {
  showMenu = false;
  showManageModal = true;
}
</script>

<svelte:window onkeyup={handleEscape} onclick={onWindowClick} />

<!-- Distinct fill so the global layout control reads separately from per-section chrome. -->
<div
  class="relative flex items-stretch self-stretch text-left border-b border-l border-[var(--pd-content-divider)] bg-[var(--pd-button-secondary-bg)]">
  {#if onAddTab && !hasTabs}
    <button
      type="button"
      aria-label="Open a new tab"
      title="Open a new tab"
      class="flex items-center self-stretch px-2.5 border-r border-[var(--pd-content-divider)] hover:bg-[var(--pd-action-button-details-bg)] text-[var(--pd-tab-text)]"
      onclick={onAddTab}>
      <Icon class="w-3 text-xs" icon={faPlus} />
    </button>
  {/if}
  <button
    bind:this={menuAnchor}
    type="button"
    aria-label="Layout options"
    title="Layout options"
    aria-haspopup="menu"
    aria-expanded={showMenu}
    class="flex items-center self-stretch gap-1.5 px-2.5 hover:bg-[var(--pd-button-secondary-hover-bg)] text-[var(--pd-button-secondary-text)]"
    class:bg-[var(--pd-button-secondary-hover-bg)]={showMenu}
    onclick={toggleMenu}>
    <Icon class="w-3 text-xs" icon={faGear} />
    {#if !hasTabs}
      <!-- With zero resource tabs open, a bare gear reads as decoration. Label only in this
           state so the control stays compact once real tabs are back. -->
      <span class="text-xs font-medium whitespace-nowrap">Layout options</span>
    {/if}
  </button>

  {#if showMenu}
    <div
      bind:this={menuEl}
      role="menu"
      tabindex="-1"
      style={menuStyle}
      class="fixed z-50 w-64 max-h-[80vh] overflow-y-auto rounded-md shadow-lg bg-[var(--pd-dropdown-bg)] ring-2 ring-[var(--pd-dropdown-ring)] hover:ring-[var(--pd-dropdown-hover-ring)] divide-y divide-[var(--pd-dropdown-divider)] focus:outline-hidden">
      <div>
        <div class="px-3 pt-2 pb-1 text-xs font-semibold uppercase tracking-wide text-[var(--pd-dropdown-item-text)] opacity-60">
          Layouts
        </div>
        <DropdownMenu.Item
          title={closeActionTitle}
          icon={faXmark}
          enabled={hasTabs}
          tooltip={hasTabs
            ? undefined
            : multiSection
              ? 'No sections to close'
              : 'No tabs to close'}
          onClick={closeAllAction} />
        <DropdownMenu.Item
          title="Save Layout As…"
          icon={faFloppyDisk}
          enabled={hasTabs}
          tooltip={hasTabs ? undefined : 'Nothing to save - open a tab first'}
          onClick={openSaveDialog} />
        <DropdownMenu.Item title="Manage Layouts…" icon={faFolderOpen} onClick={openManageModal} />
      </div>

      <div>
        <div class="px-3 pt-2 pb-1 text-xs font-semibold uppercase tracking-wide text-[var(--pd-dropdown-item-text)] opacity-60">
          Presets
        </div>
        {#each PRESETS as preset (preset.id)}
          <DropdownMenu.Item
            title={preset.title}
            tooltip={preset.description}
            icon={preset.iconClass}
            onClick={(): void => pickPreset(preset.id)} />
        {/each}
      </div>
    </div>
  {/if}
</div>

{#if showSaveDialog}
  <Dialog
    title="Save Layout As"
    onclose={(): void => {
      showSaveDialog = false;
    }}>
    {#snippet content()}
      <div class="w-full">
        <label for="layoutName" class="block my-2 text-sm font-bold text-[var(--pd-modal-text)]">Layout name</label>
        <input
          id="layoutName"
          use:autofocus
          class="w-full p-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)]"
          placeholder="e.g. Nightly debug session"
          bind:value={saveName}
          onkeydown={(e: KeyboardEvent): void => {
            if (e.key === 'Enter') confirmSave();
          }} />
      </div>
    {/snippet}
    {#snippet buttons()}
      <Button
        type="link"
        on:click={(): void => {
          showSaveDialog = false;
        }}>Cancel</Button>
      <Button type="primary" disabled={!saveName.trim()} on:click={confirmSave}>Save</Button>
    {/snippet}
  </Dialog>
{/if}

{#if activePreset}
  <PresetPickerModal
    presetId={activePreset}
    panelId={panelId}
    onClose={(): void => (activePreset = undefined)} />
{/if}

{#if showManageModal}
  <ManageLayoutsModal
    onClose={(): void => {
      showManageModal = false;
    }} />
{/if}

{#if saveToastMessage}
  <div
    role="status"
    class="fixed bottom-4 right-4 z-50 flex items-center gap-2 px-3 py-2 rounded-md shadow-lg bg-[var(--pd-dropdown-bg)] ring-2 ring-[var(--pd-dropdown-ring)] text-sm text-[var(--pd-dropdown-item-text)]">
    <i class="fas fa-circle-check text-[var(--pd-status-running)]" aria-hidden="true"></i>
    {saveToastMessage}
  </div>
{/if}
