<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// A single settings-gear button - meant to be dropped into a tab bar's
// `trailing` slot (see TabBar.svelte) rather than occupying its own full-width
// row - that opens the "Layout" menu: new/save/load named layouts, built-in
// presets, export/import, and (for the demo) simulating an agent opening a
// layout on the user's behalf.
import {
  faCirclePlus,
  faFileExport,
  faFileImport,
  faFloppyDisk,
  faFolderOpen,
  faGear,
  faRobot,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import { Button, DropdownMenu } from '@podman-desktop/ui-svelte';
import { Icon } from '@podman-desktop/ui-svelte/icons';
import { router } from 'tinro';

import Dialog from '/@/lib/dialogs/Dialog.svelte';
import { simulateAgentDebugLayout } from '/@/stores/layout/layout-agent-demo.svelte';
import {
  applyNamedLayout,
  deleteNamedLayout,
  downloadLayoutExport,
  importLayoutFromJson,
  listNamedLayouts,
  type NamedLayout,
  saveNamedLayout,
} from '/@/stores/layout/layout-persistence.svelte';
import { type PresetId, PRESETS } from '/@/stores/layout/layout-presets';
import { hasAnyTabs, resetLayout } from '/@/stores/layout/layout-store.svelte';

import PresetPickerModal from './PresetPickerModal.svelte';

let showMenu = $state(false);
let menuAnchor = $state<HTMLButtonElement>();
let menuEl = $state<HTMLDivElement>();
let clientX = $state(0);
let clientY = $state(0);
// Hidden (off-screen + invisible) until positionMenu() below has measured the menu's real size
// and placed it - avoids a one-frame flash at the top-left corner.
let menuStyle = $state('top: -9999px; left: -9999px; visibility: hidden;');

let showSaveDialog = $state(false);
let saveName = $state('');
let activePreset: PresetId | undefined = $state();
let fileInput: HTMLInputElement | undefined = $state();

let namedLayouts: NamedLayout[] = $state([]);

function refreshNamedLayouts(): void {
  namedLayouts = listNamedLayouts();
}

function toggleMenu(event: MouseEvent): void {
  const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
  clientX = rect.left;
  clientY = rect.bottom;
  showMenu = !showMenu;
  if (showMenu) {
    // Reset to hidden before the effect below re-measures and re-places the (freshly mounted)
    // menu - otherwise it would flash at wherever it was left positioned last time it was open.
    menuStyle = 'top: -9999px; left: -9999px; visibility: hidden;';
    refreshNamedLayouts();
  }
}

// This menu is embedded in each panel's tab bar (see the `trailing` slot wiring in
// WorkspaceLayout/GlobalTabBar), and Panel.svelte's own root clips overflow (so a split's
// content can't spill into its neighbor). A plain `position: absolute` dropdown - anchored to
// its small parent wrapper, as the shared DropdownMenu.Items component does - gets clipped at
// that panel boundary instead of floating over it (the "menu got cut" bug). Positioning this
// one with `position: fixed` and explicit viewport coordinates (computed here, once the menu's
// real size is known) escapes that clipping entirely, the same way the app's modals do.
$effect(() => {
  if (!showMenu || !menuEl) return;
  const rect = menuEl.getBoundingClientRect();
  const margin = 8;

  let top = clientY + margin;
  if (top + rect.height > window.innerHeight - margin) {
    // Flip to open upward from the button instead of down, roughly undoing the button's own
    // height (~32px) plus the same gap so it doesn't overlap the button itself.
    top = Math.max(margin, clientY - rect.height - 40);
  }

  let left = clientX;
  if (left + rect.width > window.innerWidth - margin) {
    left = Math.max(margin, window.innerWidth - rect.width - margin);
  }

  menuStyle = `top: ${top}px; left: ${left}px; visibility: visible;`;
});

function handleEscape({ key }: KeyboardEvent): void {
  if (key === 'Escape') showMenu = false;
}

function onWindowClick(e: MouseEvent): void {
  const target = e.target;
  if (target instanceof Node && (menuAnchor?.contains(target) || menuEl?.contains(target))) return;
  showMenu = false;
}

// This menu is mounted globally (every page, not just /workspace - see App.svelte), so any
// action that changes the layout needs to take the user there to see the result.
function goToWorkspace(): void {
  router.goto('/workspace');
}

function newLayout(): void {
  showMenu = false;
  if (hasAnyTabs() && !window.confirm('Close all open tabs and start a new layout?')) return;
  resetLayout();
  goToWorkspace();
}

function openSaveDialog(): void {
  showMenu = false;
  saveName = '';
  showSaveDialog = true;
}

function confirmSave(): void {
  if (!saveName.trim()) return;
  saveNamedLayout(saveName.trim());
  refreshNamedLayouts();
  showSaveDialog = false;
}

function pickPreset(id: PresetId): void {
  showMenu = false;
  activePreset = id;
}

function onImportFile(event: Event): void {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;
  file
    .text()
    .then(text => {
      importLayoutFromJson(text);
      goToWorkspace();
    })
    .catch((err: unknown) => console.error('Failed to import layout', err));
  input.value = '';
}
</script>

<svelte:window onkeyup={handleEscape} onclick={onWindowClick} />

<div class="relative flex items-stretch text-left">
  <button
    bind:this={menuAnchor}
    type="button"
    aria-label="Layout options"
    title="Layout options"
    aria-haspopup="menu"
    aria-expanded={showMenu}
    class="flex items-center px-2.5 hover:bg-[var(--pd-action-button-details-bg)] text-[var(--pd-tab-text)]"
    onclick={toggleMenu}>
    <Icon class="w-4 text-sm" icon={faGear} />
  </button>

  {#if showMenu}
    <div
      bind:this={menuEl}
      role="menu"
      tabindex="-1"
      style={menuStyle}
      class="fixed z-50 w-64 max-h-[80vh] overflow-y-auto rounded-md shadow-lg bg-[var(--pd-dropdown-bg)] ring-2 ring-[var(--pd-dropdown-ring)] hover:ring-[var(--pd-dropdown-hover-ring)] divide-y divide-[var(--pd-dropdown-divider)] focus:outline-hidden">
      <DropdownMenu.Item title="New Layout" icon={faCirclePlus} onClick={newLayout} />
      <DropdownMenu.Item title="Save Layout As…" icon={faFloppyDisk} onClick={openSaveDialog} />

      <div>
        <div class="px-3 pt-2 pb-1 text-xs font-semibold uppercase tracking-wide text-[var(--pd-dropdown-item-text)] opacity-60">
          Saved layouts
        </div>
        {#if namedLayouts.length === 0}
          <div class="px-3 pb-2 text-sm text-[var(--pd-dropdown-item-text)] opacity-60">No saved layouts yet</div>
        {/if}
        {#each namedLayouts as layout (layout.name)}
          <div class="group/layout-row flex items-center justify-between px-2.5 py-1.5 mx-1 rounded-md hover:bg-[var(--pd-dropdown-item-hover-bg)]">
            <button
              type="button"
              class="flex-1 min-w-0 flex items-center gap-2 text-left text-sm text-[var(--pd-dropdown-item-text)]"
              onclick={(): void => {
                applyNamedLayout(layout.name);
                showMenu = false;
                goToWorkspace();
              }}>
              <Icon icon={faFolderOpen} class="w-4 shrink-0" />
              <span class="truncate">{layout.name}</span>
            </button>
            <button
              type="button"
              aria-label="Delete layout {layout.name}"
              class="ml-2 shrink-0 opacity-0 group-hover/layout-row:opacity-60 hover:opacity-100"
              onclick={(e: MouseEvent): void => {
                e.stopPropagation();
                deleteNamedLayout(layout.name);
                refreshNamedLayouts();
              }}>
              <Icon icon={faXmark} class="w-3" />
            </button>
          </div>
        {/each}
      </div>

      <div>
        <div class="px-3 pt-2 pb-1 text-xs font-semibold uppercase tracking-wide text-[var(--pd-dropdown-item-text)] opacity-60">
          Presets
        </div>
        {#each PRESETS as preset (preset.id)}
          <DropdownMenu.Item title={preset.title} tooltip={preset.description} icon={preset.iconClass} onClick={(): void => pickPreset(preset.id)} />
        {/each}
      </div>

      <DropdownMenu.Item title="Export Layout" icon={faFileExport} onClick={downloadLayoutExport} />
      <DropdownMenu.Item
        title="Import Layout…"
        icon={faFileImport}
        onClick={(): void => {
          showMenu = false;
          fileInput?.click();
        }} />

      <DropdownMenu.Item
        title="Simulate Agent (Demo)"
        tooltip="Demo only: simulates an AI agent opening a debugging layout for you"
        icon={faRobot}
        onClick={(): void => {
          showMenu = false;
          simulateAgentDebugLayout();
          goToWorkspace();
        }} />
    </div>
  {/if}
</div>

<input bind:this={fileInput} type="file" accept="application/json" class="hidden" onchange={onImportFile} />

{#if showSaveDialog}
  <Dialog
    title="Save Layout As"
    onclose={(): void => {
      showSaveDialog = false;
    }}>
    {#snippet content()}
      <div class="w-full">
        <label for="layoutName" class="block my-2 text-sm font-bold text-[var(--pd-modal-text)]">Layout name</label>
        <input
          id="layoutName"
          class="w-full p-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)]"
          placeholder="e.g. Nightly debug session"
          bind:value={saveName}
          onkeydown={(e: KeyboardEvent): void => {
            if (e.key === 'Enter') confirmSave();
          }} />
      </div>
    {/snippet}
    {#snippet buttons()}
      <Button
        type="link"
        on:click={(): void => {
          showSaveDialog = false;
        }}>Cancel</Button>
      <Button type="primary" disabled={!saveName.trim()} on:click={confirmSave}>Save</Button>
    {/snippet}
  </Dialog>
{/if}

{#if activePreset}
  <PresetPickerModal presetId={activePreset} onClose={(): void => (activePreset = undefined)} />
{/if}
