<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/-->
<script lang="ts">
// Generated by Cursor
// Everything about *your own* saved layouts that isn't "pick one to load" (that quick action
// stays inline in the gear menu, alongside the built-in presets) - open/delete the full list,
// export/import as JSON, and the agent demo (which is really just "apply a layout an agent
// picked") - pulled into one modal so the gear menu itself doesn't turn into a mile-long list.
import { faFileExport, faFileImport, faFolderOpen, faRobot, faXmark } from '@fortawesome/free-solid-svg-icons';
import { Button } from '@podman-desktop/ui-svelte';
import { Icon } from '@podman-desktop/ui-svelte/icons';
import { router } from 'tinro';

import Dialog from '/@/lib/dialogs/Dialog.svelte';
import { simulateAgentDebugLayout } from '/@/stores/layout/layout-agent-demo.svelte';
import {
  applyNamedLayout,
  deleteNamedLayout,
  downloadLayoutExport,
  importLayoutFromJson,
  listNamedLayouts,
  type NamedLayout,
} from '/@/stores/layout/layout-persistence.svelte';

interface Props {
  onClose: () => void;
}

let { onClose }: Props = $props();

let namedLayouts: NamedLayout[] = $state(listNamedLayouts());
let fileInput: HTMLInputElement | undefined = $state();

function refresh(): void {
  namedLayouts = listNamedLayouts();
}

function goToWorkspace(): void {
  router.goto('/workspace');
}

function apply(name: string): void {
  applyNamedLayout(name);
  onClose();
  goToWorkspace();
}

function remove(name: string): void {
  deleteNamedLayout(name);
  refresh();
}

function runAgentDemo(): void {
  simulateAgentDebugLayout();
  onClose();
  goToWorkspace();
}

function onImportFile(event: Event): void {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;
  file
    .text()
    .then(text => {
      importLayoutFromJson(text);
      onClose();
      goToWorkspace();
    })
    .catch((err: unknown) => console.error('Failed to import layout', err));
  input.value = '';
}
</script>

<Dialog title="Manage Layouts" onclose={onClose}>
  {#snippet content()}
    <div class="flex flex-col gap-4 w-full text-left">
      <div>
        <div class="text-xs font-semibold uppercase tracking-wide text-[var(--pd-modal-text)] opacity-60 mb-1">
          Saved layouts
        </div>
        {#if namedLayouts.length === 0}
          <div class="text-sm text-[var(--pd-modal-text)] opacity-60">No saved layouts yet</div>
        {:else}
          <div class="flex flex-col gap-0.5">
            {#each namedLayouts as layout (layout.name)}
              <div
                class="group/layout-row flex items-center justify-between px-2 py-1.5 rounded-md hover:bg-[var(--pd-dropdown-item-hover-bg)]">
                <button
                  type="button"
                  class="flex-1 min-w-0 flex items-center gap-2 text-left text-sm text-[var(--pd-modal-text)]"
                  onclick={(): void => apply(layout.name)}>
                  <Icon icon={faFolderOpen} class="w-4 shrink-0" />
                  <span class="truncate">{layout.name}</span>
                </button>
                <button
                  type="button"
                  aria-label="Delete layout {layout.name}"
                  class="ml-2 shrink-0 opacity-0 group-hover/layout-row:opacity-60 hover:opacity-100"
                  onclick={(): void => remove(layout.name)}>
                  <Icon icon={faXmark} class="w-3" />
                </button>
              </div>
            {/each}
          </div>
        {/if}
      </div>

      <div class="flex flex-col gap-2 pt-3 border-t border-[var(--pd-content-divider)]">
        <button
          type="button"
          class="flex items-center gap-2 text-sm text-[var(--pd-modal-text)] hover:text-[var(--pd-link)]"
          onclick={downloadLayoutExport}>
          <Icon icon={faFileExport} class="w-4" /> Export Layout
        </button>
        <button
          type="button"
          class="flex items-center gap-2 text-sm text-[var(--pd-modal-text)] hover:text-[var(--pd-link)]"
          onclick={(): void => fileInput?.click()}>
          <Icon icon={faFileImport} class="w-4" /> Import Layout…
        </button>
        <button
          type="button"
          class="flex items-center gap-2 text-sm text-[var(--pd-modal-text)] hover:text-[var(--pd-link)]"
          onclick={runAgentDemo}>
          <Icon icon={faRobot} class="w-4" /> Simulate Agent (Demo)
        </button>
      </div>
    </div>
    <input bind:this={fileInput} type="file" accept="application/json" class="hidden" onchange={onImportFile} />
  {/snippet}
  {#snippet buttons()}
    <Button type="link" on:click={onClose}>Close</Button>
  {/snippet}
</Dialog>
