<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Everything about *your own* saved layouts that isn't "pick one to load" (that quick action
// stays inline in the gear menu, alongside the built-in presets) - open/delete the full list,
// export/import as JSON, and the agent demo (which is really just "apply a layout an agent
// picked") - pulled into one modal so the gear menu itself doesn't turn into a mile-long list.
//
// Built directly on Modal (not the shared Dialog wrapper) so each group of actions can read as
// its own card - the same SummaryCard visual language already used for the Pod/Container/Image
// Summary tabs - instead of Dialog's single flat list crammed into a ~320px-tall scroll box.
import { faFileExport, faFileImport, faFolderOpen, faRobot, faXmark } from '@fortawesome/free-solid-svg-icons';
import { Button, CloseButton, Modal } from '@podman-desktop/ui-svelte';
import { Icon } from '@podman-desktop/ui-svelte/icons';

import { simulateAgentDebugLayout } from '/@/stores/layout/layout-agent-demo.svelte';
import {
  applyNamedLayout,
  deleteNamedLayout,
  downloadLayoutExport,
  importLayoutFromJson,
  listNamedLayouts,
  type NamedLayout,
} from '/@/stores/layout/layout-persistence.svelte';
import { gotoListShell } from '/@/stores/layout/page-tab.svelte';

import SummaryCard from './summary/SummaryCard.svelte';

interface Props {
  onClose: () => void;
}

let { onClose }: Props = $props();

let namedLayouts: NamedLayout[] = $state(listNamedLayouts());
let fileInput: HTMLInputElement | undefined = $state();

function refresh(): void {
  namedLayouts = listNamedLayouts();
}

function goToWorkspace(): void {
  gotoListShell();
}

function apply(name: string): void {
  applyNamedLayout(name);
  onClose();
  goToWorkspace();
}

function remove(name: string): void {
  deleteNamedLayout(name);
  refresh();
}

function runAgentDemo(): void {
  simulateAgentDebugLayout();
  onClose();
  goToWorkspace();
}

function onImportFile(event: Event): void {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;
  file
    .text()
    .then(text => {
      importLayoutFromJson(text);
      onClose();
      goToWorkspace();
    })
    .catch((err: unknown) => console.error('Failed to import layout', err));
  input.value = '';
}

function tabCount(layout: NamedLayout): number {
  return Object.keys(layout.layout.tabs).length;
}

function formatSavedAt(iso: string): string {
  return new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
}
</script>

<Modal name="Manage Layouts" onclose={onClose}>
  <div class="flex flex-col w-full max-h-[80vh]">
    <div class="flex items-center justify-between pl-5 pr-3 py-3 border-b border-[var(--pd-content-divider)]">
      <h1 class="text-lg font-bold text-[var(--pd-modal-header-text)]">Manage Layouts</h1>
      <CloseButton onclick={onClose} />
    </div>

    <div class="flex flex-col gap-4 px-5 py-4 overflow-y-auto">
      <SummaryCard title="Saved Layouts" icon="fas fa-folder-open">
        {#snippet trailing()}
          {namedLayouts.length} saved
        {/snippet}
        {#if namedLayouts.length === 0}
          <div class="px-4 pb-3 text-sm text-[var(--pd-content-text)] opacity-60">
            No saved layouts yet - open some tabs, then use "Save Layout As…" from the gear menu.
          </div>
        {:else}
          <div class="divide-y divide-[var(--pd-content-divider)]">
            {#each namedLayouts as layout (layout.name)}
              <div class="group/layout-row flex items-center gap-1 hover:bg-[var(--pd-dropdown-item-hover-bg)]">
                <button
                  type="button"
                  class="flex-1 min-w-0 flex items-center gap-3 px-4 py-2.5 text-left"
                  onclick={(): void => apply(layout.name)}>
                  <Icon icon={faFolderOpen} class="w-4 shrink-0 opacity-70" />
                  <div class="flex flex-col min-w-0 gap-0.5">
                    <span class="text-sm text-[var(--pd-content-header)] truncate">{layout.name}</span>
                    <span class="text-xs text-[var(--pd-content-text)] opacity-60">
                      {tabCount(layout)} tab{tabCount(layout) === 1 ? '' : 's'} · saved {formatSavedAt(
                        layout.savedAt,
                      )}
                    </span>
                  </div>
                </button>
                <button
                  type="button"
                  aria-label="Delete layout {layout.name}"
                  class="mr-3 shrink-0 opacity-0 group-hover/layout-row:opacity-60 hover:opacity-100 p-1.5 rounded-sm hover:bg-[var(--pd-action-button-details-bg)]"
                  onclick={(): void => remove(layout.name)}>
                  <Icon icon={faXmark} class="w-3" />
                </button>
              </div>
            {/each}
          </div>
        {/if}
      </SummaryCard>

      <SummaryCard title="Import & Export" icon="fas fa-file-export">
        <div class="divide-y divide-[var(--pd-content-divider)]">
          <button
            type="button"
            class="w-full flex items-center gap-3 px-4 py-2.5 text-left hover:bg-[var(--pd-dropdown-item-hover-bg)]"
            onclick={downloadLayoutExport}>
            <Icon icon={faFileExport} class="w-4 shrink-0 opacity-70" />
            <div class="flex flex-col min-w-0 gap-0.5">
              <span class="text-sm text-[var(--pd-content-header)]">Export Layout</span>
              <span class="text-xs text-[var(--pd-content-text)] opacity-60">Download the current layout as JSON</span>
            </div>
          </button>
          <button
            type="button"
            class="w-full flex items-center gap-3 px-4 py-2.5 text-left hover:bg-[var(--pd-dropdown-item-hover-bg)]"
            onclick={(): void => fileInput?.click()}>
            <Icon icon={faFileImport} class="w-4 shrink-0 opacity-70" />
            <div class="flex flex-col min-w-0 gap-0.5">
              <span class="text-sm text-[var(--pd-content-header)]">Import Layout…</span>
              <span class="text-xs text-[var(--pd-content-text)] opacity-60">Load a previously exported JSON file</span>
            </div>
          </button>
        </div>
      </SummaryCard>

      <SummaryCard title="Demo" icon="fas fa-robot">
        <button
          type="button"
          class="w-full flex items-center gap-3 px-4 py-2.5 text-left hover:bg-[var(--pd-dropdown-item-hover-bg)]"
          onclick={runAgentDemo}>
          <Icon icon={faRobot} class="w-4 shrink-0 text-[var(--pd-status-running)]" />
          <div class="flex flex-col min-w-0 gap-0.5">
            <span class="text-sm text-[var(--pd-content-header)]">Simulate Agent (Demo)</span>
            <span class="text-xs text-[var(--pd-content-text)] opacity-60">
              Preview what an agent-prepared layout looks like
            </span>
          </div>
        </button>
      </SummaryCard>
    </div>

    <div class="flex justify-end px-5 py-3 border-t border-[var(--pd-content-divider)]">
      <Button type="link" on:click={onClose}>Close</Button>
    </div>

    <input bind:this={fileInput} type="file" accept="application/json" class="hidden" onchange={onImportFile} />
  </div>
</Modal>
