<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Manifest summary inside a workspace tab (matches ManifestDetails leaf content).
import type { ViewInfoUI } from '@podman-desktop/core-api';

import { ImageUtils } from '/@/lib/image/image-utils';
import {
  IMAGE_DETAILS_VIEW_BADGES,
  IMAGE_DETAILS_VIEW_ICONS,
  IMAGE_VIEW_BADGES,
  IMAGE_VIEW_ICONS,
} from '/@/lib/view/views';
import { containersInfos } from '/@/stores/containers';
import { context } from '/@/stores/context';
import { imagesInfos } from '/@/stores/images';
import { markTabStale } from '/@/stores/layout/layout-store.svelte';
import type { ManifestSubView } from '/@/stores/layout/layout-types';
import { viewsContributions } from '/@/stores/views';

import ImageSummaryTabContent from './ImageSummaryTabContent.svelte';
import StaleTabPlaceholder from './StaleTabPlaceholder.svelte';

interface Props {
  tabId: string;
  imageId: string;
  engineId: string;
  base64RepoTag: string;
  subView?: ManifestSubView;
}

let { tabId, imageId, engineId, base64RepoTag, subView = 'summary' }: Props = $props();

const imageUtils = new ImageUtils();

let viewContributions: ViewInfoUI[] = $derived(
  $viewsContributions.filter(
    view =>
      view.viewId === IMAGE_DETAILS_VIEW_ICONS ||
      view.viewId === IMAGE_VIEW_ICONS ||
      view.viewId === IMAGE_VIEW_BADGES ||
      view.viewId === IMAGE_DETAILS_VIEW_BADGES,
  ),
);

let imageInfo = $derived($imagesInfos.find(c => c.Id === imageId && c.engineId === engineId));
let image = $derived.by(() =>
  imageInfo
    ? imageUtils.getImageInfoUI(imageInfo, base64RepoTag, $containersInfos, $context, viewContributions)
    : undefined,
);

$effect(() => {
  markTabStale(tabId, !image);
});
</script>

{#if image}
  <div class="flex flex-col h-full min-h-0">
    <div class="grow min-h-0 overflow-auto">
      {#if subView === 'summary'}
        <ImageSummaryTabContent {tabId} image={image} />
      {/if}
    </div>
  </div>
{:else}
  <StaleTabPlaceholder resourceLabel="Manifest" tabId={tabId} />
{/if}
