<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Maximizing a panel (Panel.svelte's expand/compress button) makes every other section vanish
// from the screen entirely - WorkspaceLayout only renders the maximized leaf, so a side-by-side
// comparison the user set up can end up completely hidden with nothing on screen to say it's
// still there. This names what's behind the maximized panel and offers a one-click way back,
// so maximizing to focus on one tab doesn't read as if the other tabs were closed.
import { getHiddenWhileMaximized, layoutState, toggleMaximize } from '/@/stores/layout/layout-store.svelte';

const hidden = $derived(getHiddenWhileMaximized());

// Naming every hidden tab could run on forever with enough open tabs - three names plus a count
// keeps the banner to one line while still being concrete about what's behind it.
const MAX_NAMED_TABS = 3;

function tabLabel(tab: { title: string }): string {
  return tab.title.split(' · ')[0];
}

const namedTabs = $derived(hidden?.otherTabs.slice(0, MAX_NAMED_TABS).map(tabLabel).join('", "') ?? '');
const extraCount = $derived(Math.max(0, (hidden?.otherTabs.length ?? 0) - MAX_NAMED_TABS));

function restore(): void {
  if (layoutState.maximizedPanelId) toggleMaximize(layoutState.maximizedPanelId);
}
</script>

{#if hidden}
  <div
    class="flex items-center gap-3 px-3 py-2 bg-[var(--pd-content-bg)] border-b border-[var(--pd-content-divider)] text-sm">
    <i class="fas fa-layer-group text-[var(--pd-content-text)] opacity-70" aria-hidden="true"></i>
    <span class="grow">
      This panel is maximized - {hidden.otherTabs.length} tab{hidden.otherTabs.length === 1 ? '' : 's'} hidden in {hidden.otherPanelCount}
      other section{hidden.otherPanelCount === 1 ? '' : 's'}: "{namedTabs}"{#if extraCount > 0}, +{extraCount} more{/if}
    </span>
    <button
      type="button"
      class="shrink-0 px-2 py-1 rounded-sm hover:bg-[var(--pd-action-button-details-bg)] text-[var(--pd-link)]"
      onclick={restore}>
      Restore
    </button>
  </div>
{/if}
