<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Compact "+N" chip for tabs hidden while a section is maximized. Mounted in the
// global TabBar after the last tab / before "+" — not a full-width content banner.
import { faLayerGroup } from '@fortawesome/free-solid-svg-icons';
import { Tooltip } from '@podman-desktop/ui-svelte';
import { Icon } from '@podman-desktop/ui-svelte/icons';

import { getHiddenWhileMaximized, layoutState, toggleMaximize } from '/@/stores/layout/layout-store.svelte';

const hidden = $derived(getHiddenWhileMaximized());

function tabLabel(tab: { title: string }): string {
  return tab.title.split(' · ')[0];
}

const namedTabs = $derived(hidden?.otherTabs.map(tabLabel).join('", "') ?? '');

const tooltipText = $derived.by((): string => {
  if (!hidden) return '';
  const tabWord = hidden.otherTabs.length === 1 ? 'tab' : 'tabs';
  const sectionWord = hidden.otherPanelCount === 1 ? 'section' : 'sections';
  return `${hidden.otherTabs.length} ${tabWord} hidden in ${hidden.otherPanelCount} other ${sectionWord}: "${namedTabs}" - click to restore`;
});

function restore(): void {
  if (layoutState.maximizedPanelId) toggleMaximize(layoutState.maximizedPanelId);
}
</script>

{#if hidden}
  <div class="flex items-center shrink-0 self-stretch px-1">
    <Tooltip tip={tooltipText} top>
      <button
        type="button"
        aria-label="Restore {hidden.otherTabs.length} hidden tab{hidden.otherTabs.length === 1 ? '' : 's'}"
        class="flex items-center gap-1.5 pl-1.5 pr-2 py-0.5 rounded-full border border-[var(--pd-content-divider)] hover:bg-[var(--pd-action-button-details-bg)] text-[var(--pd-content-text)] text-xs whitespace-nowrap"
        onclick={restore}>
        <Icon class="w-2.5 text-[10px] opacity-70" icon={faLayerGroup} />
        <span class="font-semibold">+{hidden.otherTabs.length}</span>
      </button>
    </Tooltip>
  </div>
{/if}
