<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/-->
<script lang="ts">
// Generated by Cursor
// Purely illustrative "live stats" for the Tabs & Flexible Layout prototype (section 4.9 of
// the vision doc: an agent opens pods/images side by side "to compare"). There's no real
// telemetry or vulnerability scanner wired up here, so real pod/image Summary data alone is
// just static metadata (name, ID, ports...) - two of those side by side don't actually look
// like a "comparison". These numbers come from mock-resource-metrics.ts, deterministically
// derived from the resource's own id, so the same resource always shows the same numbers
// (stable across re-renders and reloads) while two different resources visibly differ -
// enough to demo what a real compare view would feel like once real metrics/scanning exist.
import { formatVulnBreakdown, getImageMockMetrics, getPodMockMetrics } from '/@/stores/layout/mock-resource-metrics';

interface Props {
  resourceId: string;
  kind: 'pod' | 'image';
  /** Repository name (e.g. "quay.io/org/repo") and digest ("sha256:...") of the image, used
   * only to link the vulnerabilities alert below to a *real* scan report on Quay.io when the
   * image actually is quay-hosted - Podman Desktop has no scanner of its own to link to. */
  imageName?: string;
  imageDigest?: string;
}

let { resourceId, kind, imageName, imageDigest }: Props = $props();

type Status = 'good' | 'warn' | 'bad';

interface Stat {
  label: string;
  value: string;
  status: Status;
}

const STATUS_LABEL: Record<Status, string> = { good: 'Good', warn: 'Warning', bad: 'Critical' };
const STATUS_TEXT_CLASS: Record<Status, string> = {
  good: 'text-[var(--pd-status-running)]',
  warn: 'text-[var(--pd-status-degraded)]',
  bad: 'text-[var(--pd-state-error)]',
};

const imageMetrics = $derived(kind === 'image' ? getImageMockMetrics(resourceId) : undefined);

const stats = $derived.by((): Stat[] => {
  if (kind === 'pod') {
    const { cpuPercent, memoryMb, restarts, rxMb } = getPodMockMetrics(resourceId);
    return [
      {
        label: 'CPU usage',
        value: `${cpuPercent}%`,
        status: cpuPercent > 75 ? 'bad' : cpuPercent > 45 ? 'warn' : 'good',
      },
      { label: 'Memory', value: `${memoryMb} MB`, status: memoryMb > 400 ? 'bad' : memoryMb > 300 ? 'warn' : 'good' },
      { label: 'Restarts', value: `${restarts}`, status: restarts > 1 ? 'bad' : restarts === 1 ? 'warn' : 'good' },
      {
        label: 'Network I/O',
        value: `${rxMb.toFixed(1)} MB/s`,
        status: rxMb > 25 ? 'bad' : rxMb > 10 ? 'warn' : 'good',
      },
    ];
  }
  const { critical, high, medium, pulls, layers, daysSinceScan } = imageMetrics ?? {
    critical: 0,
    high: 0,
    medium: 0,
    pulls: 0,
    layers: 0,
    daysSinceScan: 0,
  };
  return [
    {
      label: 'Vulnerabilities',
      value: formatVulnBreakdown({ critical, high, medium }),
      status: critical > 0 ? 'bad' : high > 0 ? 'warn' : 'good',
    },
    { label: 'Layers', value: `${layers}`, status: layers > 9 ? 'bad' : layers > 6 ? 'warn' : 'good' },
    { label: 'Pulls', value: pulls.toLocaleString(), status: pulls < 500 ? 'warn' : 'good' },
    {
      label: 'Last scanned',
      value: `${daysSinceScan}d ago`,
      status: daysSinceScan >= 5 ? 'bad' : daysSinceScan >= 3 ? 'warn' : 'good',
    },
  ];
});

const hasVulnerabilities = $derived(!!imageMetrics && (imageMetrics.critical > 0 || imageMetrics.high > 0));

/** Quay.io actually runs real (Clair-based) vulnerability scans on the images it hosts, so
 * when the image is quay-hosted we can link to a genuine report instead of a fake one -
 * Podman Desktop itself has no scanner or report page of its own to send users to. */
const quayScanUrl = $derived.by((): string | undefined => {
  if (!imageName || !imageDigest || !imageName.startsWith('quay.io/')) return undefined;
  const repoPath = imageName.slice('quay.io/'.length);
  return `https://quay.io/repository/${repoPath}/manifest/${imageDigest}`;
});
</script>

<div class="mx-5 mt-4 mb-1 rounded-md border border-[var(--pd-content-divider)] bg-[var(--pd-content-card-bg)]">
  <div class="flex items-center gap-2 px-4 pt-3 text-xs font-semibold uppercase tracking-wide text-[var(--pd-content-header)] opacity-70">
    <i class="fas fa-chart-simple" aria-hidden="true"></i>
    <span>Live stats</span>
  </div>
  <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 px-4 py-3">
    {#each stats as stat (stat.label)}
      <div class="flex flex-col gap-0.5">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">{stat.label}</span>
        <span class="text-base font-semibold text-[var(--pd-content-header)]">{stat.value}</span>
        <span class="text-[11px] font-medium {STATUS_TEXT_CLASS[stat.status]}">{STATUS_LABEL[stat.status]}</span>
      </div>
    {/each}
  </div>
  {#if hasVulnerabilities}
    <div
      class="flex items-start gap-2 border-t border-[var(--pd-content-divider)] px-4 py-2.5 text-xs text-[var(--pd-content-text)]">
      <i class="fas fa-triangle-exclamation mt-0.5 text-[var(--pd-status-degraded)]" aria-hidden="true"></i>
      <div class="flex flex-col gap-0.5">
        <span>
          Vulnerabilities detected in this image.
          {#if quayScanUrl}
            View the full report on Quay.io:
          {:else}
            Check your registry's scan results for details.
          {/if}
        </span>
        {#if quayScanUrl}
          <!-- Native anchor keeps browser/electron context-menu options (e.g. copy link). -->
          <a
            href={quayScanUrl}
            class="w-fit cursor-pointer text-[var(--pd-link)] no-underline hover:underline"
            onclick={async (): Promise<void> => {
              await window.openExternal(quayScanUrl);
            }}>
            View scan results on Quay.io <i class="fas fa-arrow-up-right-from-square text-[10px]" aria-hidden="true"
            ></i>
          </a>
        {/if}
      </div>
    </div>
  {/if}
</div>
