<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/-->
<script lang="ts">
// Generated by Cursor
// Purely illustrative "live stats" for the Tabs & Flexible Layout prototype (section 4.9 of
// the vision doc: an agent opens pods/images side by side "to compare"). There's no real
// telemetry or vulnerability scanner wired up here, so real pod/image Summary data alone is
// just static metadata (name, ID, ports...) - two of those side by side don't actually look
// like a "comparison". These numbers are deterministically derived from the resource's own
// id, so the same resource always shows the same numbers (stable across re-renders and
// reloads) while two different resources visibly differ - enough to demo what a real
// compare view would feel like once real metrics/scanning exist.
interface Props {
  resourceId: string;
  kind: 'pod' | 'image';
}

let { resourceId, kind }: Props = $props();

function hash(input: string): number {
  let h = 0;
  for (let i = 0; i < input.length; i++) {
    h = (h * 31 + input.charCodeAt(i)) >>> 0;
  }
  return h;
}

const seed = $derived(hash(`${kind}:${resourceId}`));

type Status = 'good' | 'warn' | 'bad';

interface Stat {
  label: string;
  value: string;
  status: Status;
}

const STATUS_LABEL: Record<Status, string> = { good: 'Good', warn: 'Warning', bad: 'Critical' };
const STATUS_DOT: Record<Status, string> = {
  good: 'bg-[var(--pd-status-running)]',
  warn: 'bg-[var(--pd-status-degraded)]',
  bad: 'bg-[var(--pd-state-error)]',
};

const stats = $derived.by((): Stat[] => {
  // Unsigned shifts (>>>) throughout: h can exceed 0x7FFFFFFF, and a signed >> would sign-extend
  // that into a negative number, producing nonsense like "-184 MB" of memory.
  const h = seed;
  if (kind === 'pod') {
    const cpuPercent = (h % 55) + 3;
    const memoryMb = ((h >>> 3) % 420) + 48;
    const restarts = (h >>> 7) % 4;
    const rxMb = (((h >>> 11) % 480) + 5) / 10;
    return [
      {
        label: 'CPU usage',
        value: `${cpuPercent}%`,
        status: cpuPercent > 75 ? 'bad' : cpuPercent > 45 ? 'warn' : 'good',
      },
      { label: 'Memory', value: `${memoryMb} MB`, status: memoryMb > 400 ? 'bad' : memoryMb > 300 ? 'warn' : 'good' },
      { label: 'Restarts', value: `${restarts}`, status: restarts > 1 ? 'bad' : restarts === 1 ? 'warn' : 'good' },
      {
        label: 'Network I/O',
        value: `${rxMb.toFixed(1)} MB/s`,
        status: rxMb > 25 ? 'bad' : rxMb > 10 ? 'warn' : 'good',
      },
    ];
  }
  const critical = (h >>> 2) % 3;
  const high = (h >>> 5) % 6;
  const medium = (h >>> 9) % 14;
  const pulls = ((h >>> 13) % 9000) + 120;
  const layers = ((h >>> 17) % 11) + 3;
  const daysSinceScan = (h % 6) + 1;
  return [
    {
      label: 'Vulnerabilities',
      value: critical > 0 ? `${critical} critical, ${high} high` : `${high} high, ${medium} medium`,
      status: critical > 0 ? 'bad' : high > 2 ? 'warn' : 'good',
    },
    { label: 'Layers', value: `${layers}`, status: layers > 9 ? 'bad' : layers > 6 ? 'warn' : 'good' },
    { label: 'Pulls', value: pulls.toLocaleString(), status: pulls < 500 ? 'warn' : 'good' },
    {
      label: 'Last scanned',
      value: `${daysSinceScan}d ago`,
      status: daysSinceScan >= 5 ? 'bad' : daysSinceScan >= 3 ? 'warn' : 'good',
    },
  ];
});
</script>

<div class="mx-5 mt-4 mb-1 rounded-md border border-[var(--pd-content-divider)] bg-[var(--pd-content-card-bg)]">
  <div class="flex items-center gap-2 px-4 pt-3 text-xs font-semibold uppercase tracking-wide text-[var(--pd-content-header)] opacity-70">
    <i class="fas fa-chart-simple" aria-hidden="true"></i>
    <span>Live stats</span>
  </div>
  <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 px-4 py-3">
    {#each stats as stat (stat.label)}
      <div class="flex flex-col gap-0.5">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">{stat.label}</span>
        <span class="text-base font-semibold text-[var(--pd-content-header)]">{stat.value}</span>
        <span class="flex items-center gap-1.5 text-[11px] text-[var(--pd-content-text)] opacity-70">
          <span class="w-1.5 h-1.5 rounded-full shrink-0 {STATUS_DOT[stat.status]}" aria-hidden="true"></span>
          {STATUS_LABEL[stat.status]}
        </span>
      </div>
    {/each}
  </div>
</div>
