<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/-->
<script lang="ts">
// Generated by Cursor
// Purely illustrative "live stats" for the Tabs & Flexible Layout prototype (section 4.9 of
// the vision doc: an agent opens pods/images side by side "to compare"). There's no real
// telemetry or vulnerability scanner wired up here, so real pod/image Summary data alone is
// just static metadata (name, ID, ports...) - two of those side by side don't actually look
// like a "comparison". These numbers are deterministically derived from the resource's own
// id, so the same resource always shows the same numbers (stable across re-renders and
// reloads) while two different resources visibly differ - enough to demo what a real
// compare view would feel like once real metrics/scanning exist.
interface Props {
  resourceId: string;
  kind: 'pod' | 'image';
}

let { resourceId, kind }: Props = $props();

function hash(input: string): number {
  let h = 0;
  for (let i = 0; i < input.length; i++) {
    h = (h * 31 + input.charCodeAt(i)) >>> 0;
  }
  return h;
}

const seed = $derived(hash(`${kind}:${resourceId}`));

interface Stat {
  label: string;
  value: string;
  tone?: 'warn' | 'bad';
}

const stats = $derived.by((): Stat[] => {
  // Unsigned shifts (>>>) throughout: h can exceed 0x7FFFFFFF, and a signed >> would sign-extend
  // that into a negative number, producing nonsense like "-184 MB" of memory.
  const h = seed;
  if (kind === 'pod') {
    const cpuPercent = (h % 55) + 3;
    const memoryMb = ((h >>> 3) % 420) + 48;
    const restarts = (h >>> 7) % 4;
    const rxMb = (((h >>> 11) % 480) + 5) / 10;
    return [
      { label: 'CPU usage', value: `${cpuPercent}%`, tone: cpuPercent > 45 ? 'warn' : undefined },
      { label: 'Memory', value: `${memoryMb} MB` },
      { label: 'Restarts', value: `${restarts}`, tone: restarts > 1 ? 'warn' : undefined },
      { label: 'Network I/O', value: `${rxMb.toFixed(1)} MB/s` },
    ];
  }
  const critical = (h >>> 2) % 3;
  const high = (h >>> 5) % 6;
  const medium = (h >>> 9) % 14;
  const pulls = ((h >>> 13) % 9000) + 120;
  const layers = ((h >>> 17) % 11) + 3;
  return [
    {
      label: 'Vulnerabilities',
      value: critical > 0 ? `${critical} critical, ${high} high` : `${high} high, ${medium} medium`,
      tone: critical > 0 ? 'bad' : high > 2 ? 'warn' : undefined,
    },
    { label: 'Layers', value: `${layers}` },
    { label: 'Pulls', value: pulls.toLocaleString() },
    { label: 'Last scanned', value: `${(h % 6) + 1}d ago` },
  ];
});
</script>

<div class="mx-5 mt-4 mb-1 rounded-md border border-[var(--pd-content-divider)] bg-[var(--pd-content-card-bg)]">
  <div class="flex items-center gap-2 px-4 pt-3 text-xs font-semibold uppercase tracking-wide text-[var(--pd-content-header)] opacity-70">
    <i class="fas fa-chart-simple" aria-hidden="true"></i>
    <span>Live stats</span>
    <span
      class="ml-auto normal-case font-normal opacity-80"
      title="Illustrative numbers for this prototype - not real telemetry.">
      Mock data (prototype demo)
    </span>
  </div>
  <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 px-4 py-3">
    {#each stats as stat (stat.label)}
      <div class="flex flex-col">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">{stat.label}</span>
        <span
          class="text-base font-semibold"
          class:text-[var(--pd-status-degraded)]={stat.tone === 'warn'}
          class:text-[var(--pd-state-error)]={stat.tone === 'bad'}
          class:text-[var(--pd-content-header)]={!stat.tone}>
          {stat.value}
        </span>
      </div>
    {/each}
  </div>
</div>
