<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Redesigned Network Summary tab — same carded layout as container/image summaries.
import { Link } from '@podman-desktop/ui-svelte';

import { openContainerInWorkspace } from '/@/lib/layout/resource-open-actions';
import NetworkDetailsInspect from '/@/lib/network/NetworkDetailsInspect.svelte';
import type { NetworkInfoUI } from '/@/lib/network/NetworkInfoUI';
import { networkKey } from '/@/stores/layout/layout-types';

import EnvironmentField from './summary/EnvironmentField.svelte';
import InspectCard from './summary/InspectCard.svelte';
import OverviewField from './summary/OverviewField.svelte';
import ResourceSummaryHeader from './summary/ResourceSummaryHeader.svelte';
import SummaryCard from './summary/SummaryCard.svelte';

interface Props {
  tabId: string;
  network: NetworkInfoUI;
}

let { tabId, network }: Props = $props();

const createdDate = $derived(network.created ? new Date(network.created) : undefined);

function openContainer(container: { id: string; name: string }): void {
  openContainerInWorkspace({ id: container.id, name: container.name }, 'newTab');
}
</script>

<div class="flex flex-col gap-4 px-5 py-4">
  <ResourceSummaryHeader
    name={network.name}
    status={network.status}
    statusLabel={network.status.toLowerCase()}
    icon="fas fa-network-wired"
    id={network.id}
    created={createdDate} />

  <!-- Same columns as the production Networks table (minus Actions). -->
  <SummaryCard title="Overview" icon="fas fa-table-list">
    <div class="grid grid-cols-2 sm:grid-cols-3 gap-3 px-4 pb-3">
      <OverviewField label="Id" value={network.shortId || network.id} title={network.id} />
      <EnvironmentField engineId={network.engineId} />
      <OverviewField label="Driver" value={network.driver} />
      <OverviewField label="IPv6" value={network.ipv6_enabled ? 'Enabled' : 'Disabled'} />
      <OverviewField label="Status" value={network.status.toLowerCase()} />
    </div>
  </SummaryCard>

  <SummaryCard title="Container usage">
    {#snippet trailing()}
      {network.containers.length} container{network.containers.length === 1 ? '' : 's'}
    {/snippet}
    {#if network.containers.length > 0}
      <div class="divide-y divide-[var(--pd-content-divider)]">
        {#each network.containers as container (container.id)}
          <div class="flex items-center justify-between gap-3 px-4 py-2 text-sm">
            <Link class="truncate min-w-0" on:click={(): void => openContainer(container)}>
              {container.name}
            </Link>
            <span class="text-xs font-mono text-[var(--pd-content-text)] opacity-60 shrink-0">
              {container.id.slice(0, 12)}
            </span>
          </div>
        {/each}
      </div>
    {:else}
      <div class="px-4 pb-3 text-sm text-[var(--pd-content-text)] opacity-60">
        No containers are currently attached to this network.
      </div>
    {/if}
  </SummaryCard>

  <InspectCard
    resourceType="network"
    resourceId={networkKey(network.name, network.engineId)}
    resourceTitle={network.name}
    {tabId}>
    <NetworkDetailsInspect {network} />
  </InspectCard>
</div>
