<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
import { NetworkUtils } from '/@/lib/network/network-utils';
import NetworkDetailsInspect from '/@/lib/network/NetworkDetailsInspect.svelte';
import { markTabStale } from '/@/stores/layout/layout-store.svelte';
import type { NetworkSubView } from '/@/stores/layout/layout-types';
import { networksListInfo } from '/@/stores/networks';

import NetworkSummaryTabContent from './NetworkSummaryTabContent.svelte';
import StaleTabPlaceholder from './StaleTabPlaceholder.svelte';

interface Props {
  tabId: string;
  networkName: string;
  engineId: string;
  subView?: NetworkSubView;
}

let { tabId, networkName, engineId, subView = 'summary' }: Props = $props();

const networkUtils = new NetworkUtils();

let network = $derived.by(() => {
  const matching = $networksListInfo.find(n => n.Name === networkName && n.engineId === engineId);
  return matching ? networkUtils.toNetworkInfoUI(matching) : undefined;
});

$effect(() => {
  markTabStale(tabId, !network);
});
</script>

{#if network}
  <div class="flex flex-col h-full min-h-0 overflow-auto">
    {#if subView === 'inspect'}
      <NetworkDetailsInspect {network} />
    {:else}
      <NetworkSummaryTabContent {tabId} {network} />
    {/if}
  </div>
{:else}
  <StaleTabPlaceholder resourceLabel="Network" tabId={tabId} />
{/if}
