<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Cursor/VS Code-style "new tab" command palette, opened from a panel's "+"
// button (see TabBar's onAddTab). Replaces the old plain dropdown of
// sub-views with a searchable list that also lets you jump straight to any
// pod/container/image, or hand a free-text request to the (mocked) agent -
// section 4.6/4.9 of the vision doc.
import { Modal } from '@podman-desktop/ui-svelte';
import { tick } from 'svelte';

import { ContainerUtils } from '/@/lib/container/container-utils';
import { ImageUtils } from '/@/lib/image/image-utils';
import { containersInfos } from '/@/stores/containers';
import { imagesInfos } from '/@/stores/images';
import { runAgentPrompt } from '/@/stores/layout/layout-agent-demo.svelte';
import { openTab } from '/@/stores/layout/layout-store.svelte';
import type { WorkspaceTab } from '/@/stores/layout/layout-types';
import { imageKey, podKey, subViewLabel, subViewsForResourceType } from '/@/stores/layout/layout-types';
import { podsInfos } from '/@/stores/pods';

interface Props {
  panelId: string;
  activeTab: WorkspaceTab | undefined;
  onClose: () => void;
}

let { panelId, activeTab, onClose }: Props = $props();

interface PaletteEntry {
  id: string;
  title: string;
  subtitle: string;
  iconClass: string;
  group: string;
  onSelect: () => void;
}

const containerUtils = new ContainerUtils();
const imageUtils = new ImageUtils();

let query = $state('');
let selectedIndex = $state(0);
let inputEl: HTMLInputElement | undefined = $state();

const subViewEntries = $derived.by((): PaletteEntry[] => {
  if (!activeTab) return [];
  const resourceName = activeTab.title.split(' · ')[0];
  return subViewsForResourceType(activeTab.resourceType)
    .filter(subView => subView !== activeTab.subView)
    .map(
      (subView): PaletteEntry => ({
        id: `subview-${subView}`,
        title: subViewLabel(subView),
        subtitle: `Another view of "${resourceName}"`,
        iconClass: 'fas fa-table-columns',
        group: 'This resource',
        onSelect: (): void => {
          openTab(
            {
              resourceType: activeTab.resourceType,
              resourceId: activeTab.resourceId,
              subView,
              title: `${resourceName} · ${subViewLabel(subView)}`,
            },
            'newTab',
            panelId,
          );
          onClose();
        },
      }),
    );
});

const podEntries = $derived(
  $podsInfos.map(
    (pod): PaletteEntry => ({
      id: `pod-${pod.id}`,
      title: pod.name,
      subtitle: 'Pod',
      iconClass: 'fas fa-cubes',
      group: 'Pods',
      onSelect: (): void => {
        openTab(
          {
            resourceType: 'pod',
            resourceId: podKey(pod.name, pod.engineId),
            subView: 'summary',
            title: `${pod.name} · Summary`,
          },
          'newTab',
          panelId,
        );
        onClose();
      },
    }),
  ),
);

const containerEntries = $derived(
  $containersInfos
    .map(c => containerUtils.getContainerInfoUI(c))
    .map(
      (container): PaletteEntry => ({
        id: `container-${container.id}`,
        title: container.name,
        subtitle: 'Container',
        iconClass: 'fas fa-cube',
        group: 'Containers',
        onSelect: (): void => {
          openTab(
            {
              resourceType: 'container',
              resourceId: container.id,
              subView: 'summary',
              title: `${container.name} · Summary`,
            },
            'newTab',
            panelId,
          );
          onClose();
        },
      }),
    ),
);

const imageEntries = $derived(
  $imagesInfos
    .flatMap(i => imageUtils.getImagesInfoUI(i, $containersInfos, undefined, [], $imagesInfos))
    .filter((i): i is NonNullable<typeof i> => !!i)
    .map(
      (image): PaletteEntry => ({
        id: `image-${image.id}-${image.base64RepoTag}`,
        title: `${image.name}:${image.tag}`,
        subtitle: 'Image',
        iconClass: 'fas fa-box',
        group: 'Images',
        onSelect: (): void => {
          openTab(
            {
              resourceType: 'image',
              resourceId: imageKey(image.id, image.engineId, image.base64RepoTag),
              subView: 'summary',
              title: `${image.name}:${image.tag} · Summary`,
            },
            'newTab',
            panelId,
          );
          onClose();
        },
      }),
    ),
);

const trimmedQuery = $derived(query.trim());

const agentEntry = $derived.by(
  (): PaletteEntry => ({
    id: 'agent',
    title: trimmedQuery ? `Ask agent: "${trimmedQuery}"` : 'Ask agent to prepare a layout for me',
    subtitle: 'AI agent',
    iconClass: 'fas fa-wand-magic-sparkles',
    group: 'Agent',
    onSelect: (): void => {
      runAgentPrompt(trimmedQuery);
      onClose();
    },
  }),
);

const filteredResourceEntries = $derived.by((): PaletteEntry[] => {
  const q = trimmedQuery.toLowerCase();
  const matches = (entry: PaletteEntry): boolean =>
    !q || entry.title.toLowerCase().includes(q) || entry.subtitle.toLowerCase().includes(q);
  return [...subViewEntries, ...podEntries, ...containerEntries, ...imageEntries].filter(matches);
});

const groupedEntries = $derived.by((): { name: string; entries: PaletteEntry[] }[] => {
  const groups: { name: string; entries: PaletteEntry[] }[] = [{ name: 'Agent', entries: [agentEntry] }];
  for (const entry of filteredResourceEntries) {
    let group = groups.find(g => g.name === entry.group);
    if (!group) {
      group = { name: entry.group, entries: [] };
      groups.push(group);
    }
    group.entries.push(entry);
  }
  return groups;
});

const allEntries = $derived(groupedEntries.flatMap(g => g.entries));

function onQueryInput(): void {
  selectedIndex = 0;
}

function onKeydown(event: KeyboardEvent): void {
  if (allEntries.length === 0) return;
  if (event.key === 'ArrowDown') {
    event.preventDefault();
    selectedIndex = (selectedIndex + 1) % allEntries.length;
  } else if (event.key === 'ArrowUp') {
    event.preventDefault();
    selectedIndex = (selectedIndex - 1 + allEntries.length) % allEntries.length;
  } else if (event.key === 'Enter') {
    event.preventDefault();
    allEntries[selectedIndex]?.onSelect();
  }
}

tick()
  .then(() => inputEl?.focus())
  .catch((error: unknown) => console.error('Unable to focus new-tab palette input', error));
</script>

<Modal name="Open a new tab" top onclose={onClose}>
  <!-- Modal's own card is capped at max-w-[32rem] (512px) and uses overflow-visible (so other
       modals can host overflowing dropdowns/tooltips). A fixed width here wider than that cap
       would spill outside the card, uncontained by that overflow-visible - looking like a
       detached, broken floating scrollbar. w-full (instead of a hardcoded px width) always
       matches whatever width the card actually resolves to, and overflow-hidden clips our own
       scrollable list to its rounded corners. -->
  <div class="flex flex-col w-full max-h-[70vh] rounded-xl overflow-hidden">
    <div class="p-2 border-b border-[var(--pd-content-divider)]">
      <input
        bind:this={inputEl}
        bind:value={query}
        oninput={onQueryInput}
        onkeydown={onKeydown}
        type="text"
        aria-label="Search pods, containers, images, or ask the agent"
        placeholder="Search pods, containers, images — or ask the agent…"
        class="w-full px-3 py-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)] border border-[var(--pd-input-field-focused-bg)] focus:outline-hidden" />
    </div>
    <div class="overflow-y-auto py-1">
      {#each groupedEntries as group (group.name)}
        {#if group.entries.length > 0}
          <div class="px-3 pt-2 pb-1 text-xs font-semibold uppercase tracking-wide text-[var(--pd-modal-dropdown-text)] opacity-70">
            {group.name}
          </div>
          {#each group.entries as entry (entry.id)}
            {@const idx = allEntries.indexOf(entry)}
            <button
              type="button"
              class="w-full flex items-center gap-3 px-3 py-2 text-left {idx === selectedIndex
                ? 'bg-[var(--pd-modal-dropdown-highlight)]'
                : 'hover:bg-[var(--pd-dropdown-bg)]'}"
              onmouseenter={(): void => {
                selectedIndex = idx;
              }}
              onclick={entry.onSelect}>
              <i class="{entry.iconClass} w-4 text-center text-[var(--pd-modal-dropdown-text)] shrink-0" aria-hidden="true"></i>
              <span class="grow overflow-hidden text-ellipsis whitespace-nowrap text-[var(--pd-modal-dropdown-text)]">
                {entry.title}
              </span>
              <span class="text-xs text-[var(--pd-modal-dropdown-text)] opacity-60 shrink-0">{entry.subtitle}</span>
            </button>
          {/each}
        {/if}
      {/each}
      {#if filteredResourceEntries.length === 0}
        <div class="px-3 py-6 text-center text-sm text-[var(--pd-modal-dropdown-text)] opacity-70">
          No matching resources — press Enter to ask the agent instead.
        </div>
      {/if}
    </div>
  </div>
</Modal>
