<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Cursor/VS Code-style "new tab" command palette, opened from a panel's "+"
// button (see TabBar's onAddTab). Replaces the old plain dropdown of
// sub-views with a searchable list that also lets you jump straight to any
// pod/container/image, or hand a free-text request to the (mocked) agent -
// section 4.6/4.9 of the vision doc.
import { Modal } from '@podman-desktop/ui-svelte';

import { ContainerUtils } from '/@/lib/container/container-utils';
import { ImageUtils } from '/@/lib/image/image-utils';
import { NetworkUtils } from '/@/lib/network/network-utils';
import { VolumeUtils } from '/@/lib/volume/volume-utils';
import { containersInfos } from '/@/stores/containers';
import { imagesInfos } from '/@/stores/images';
import { runAgentPrompt } from '/@/stores/layout/layout-agent-demo.svelte';
import { findProactiveInsights } from '/@/stores/layout/layout-proactive-insight';
import { openTab } from '/@/stores/layout/layout-store.svelte';
import type { WorkspaceTab } from '/@/stores/layout/layout-types';
import {
  imageKey,
  networkKey,
  podKey,
  secretKey,
  subViewLabel,
  subViewsForResourceType,
  volumeKey,
} from '/@/stores/layout/layout-types';
import { networksListInfo } from '/@/stores/networks';
import { podsInfos } from '/@/stores/pods';
import { secretsInfo } from '/@/stores/secrets';
import { volumeListInfos } from '/@/stores/volumes';

import { autofocus } from './autofocus';

interface Props {
  panelId: string;
  activeTab: WorkspaceTab | undefined;
  /** Called with `true` when the palette closes *because something was picked* (as opposed to
   * Escape/backdrop dismissal, which calls it with no argument) - callers opening this from
   * outside /workspace (see GlobalTabBar) use that distinction to navigate to /workspace only
   * once a tab actually exists to show there, not on every dismissal. */
  onClose: (opened?: boolean) => void;
}

let { panelId, activeTab, onClose }: Props = $props();

interface PaletteEntry {
  id: string;
  title: string;
  subtitle: string;
  iconClass: string;
  /** Every entry defaults to the palette's neutral icon color - only the agent entry overrides
   * this, so the one row that runs an autonomous action (instead of just opening the one tab you
   * clicked) reads as visually distinct at a glance, not identical to every resource row below it. */
  iconColorClass?: string;
  group: string;
  onSelect: () => void;
}

const containerUtils = new ContainerUtils();
const imageUtils = new ImageUtils();
const volumeUtils = new VolumeUtils();
const networkUtils = new NetworkUtils();

let query = $state('');
let selectedIndex = $state(0);

const subViewEntries = $derived.by((): PaletteEntry[] => {
  if (!activeTab) return [];
  const resourceName = activeTab.title.split(' · ')[0];
  return subViewsForResourceType(activeTab.resourceType)
    .filter(subView => subView !== activeTab.subView)
    .map(
      (subView): PaletteEntry => ({
        id: `subview-${subView}`,
        title: subViewLabel(subView),
        subtitle: `Another view of "${resourceName}"`,
        iconClass: 'fas fa-table-columns',
        group: 'This resource',
        onSelect: (): void => {
          openTab(
            {
              resourceType: activeTab.resourceType,
              resourceId: activeTab.resourceId,
              subView,
              title: `${resourceName} · ${subViewLabel(subView)}`,
            },
            'newTab',
            panelId,
          );
          onClose(true);
        },
      }),
    );
});

const podEntries = $derived(
  $podsInfos.map(
    (pod): PaletteEntry => ({
      id: `pod-${pod.id}`,
      title: pod.name,
      subtitle: 'Pod',
      iconClass: 'fas fa-cubes',
      group: 'Pods',
      onSelect: (): void => {
        openTab(
          {
            resourceType: 'pod',
            resourceId: podKey(pod.name, pod.engineId),
            subView: 'summary',
            title: `${pod.name} · Summary`,
          },
          'newTab',
          panelId,
        );
        onClose(true);
      },
    }),
  ),
);

const containerEntries = $derived(
  $containersInfos
    .map(c => containerUtils.getContainerInfoUI(c))
    .map(
      (container): PaletteEntry => ({
        id: `container-${container.id}`,
        title: container.name,
        subtitle: 'Container',
        iconClass: 'fas fa-cube',
        group: 'Containers',
        onSelect: (): void => {
          openTab(
            {
              resourceType: 'container',
              resourceId: container.id,
              subView: 'summary',
              title: `${container.name} · Summary`,
            },
            'newTab',
            panelId,
          );
          onClose(true);
        },
      }),
    ),
);

const imageUIList = $derived(
  $imagesInfos
    .flatMap(i => imageUtils.getImagesInfoUI(i, $containersInfos, undefined, [], $imagesInfos))
    .filter((i): i is NonNullable<typeof i> => !!i),
);

const imageEntries = $derived(
  imageUIList.map(
    (image): PaletteEntry => ({
      id: `image-${image.id}-${image.base64RepoTag}`,
      title: `${image.name}:${image.tag}`,
      subtitle: 'Image',
      iconClass: 'fas fa-box',
      group: 'Images',
      onSelect: (): void => {
        openTab(
          {
            resourceType: 'image',
            resourceId: imageKey(image.id, image.engineId, image.base64RepoTag),
            subView: 'summary',
            title: `${image.name}:${image.tag} · Summary`,
          },
          'newTab',
          panelId,
        );
        onClose(true);
      },
    }),
  ),
);

const volumeEntries = $derived(
  $volumeListInfos
    .flatMap(list => list.Volumes)
    .map(v => {
      try {
        return volumeUtils.toVolumeInfoUI(v);
      } catch {
        return undefined;
      }
    })
    .filter((v): v is NonNullable<typeof v> => !!v)
    .map(
      (volume): PaletteEntry => ({
        id: `volume-${volume.engineId}-${volume.name}`,
        title: volume.shortName,
        subtitle: 'Volume',
        iconClass: 'fas fa-database',
        group: 'Volumes',
        onSelect: (): void => {
          openTab(
            {
              resourceType: 'volume',
              resourceId: volumeKey(volume.name, volume.engineId),
              subView: 'summary',
              title: `${volume.shortName} · Summary`,
            },
            'newTab',
            panelId,
          );
          onClose(true);
        },
      }),
    ),
);

const networkEntries = $derived(
  $networksListInfo
    .map(n => networkUtils.toNetworkInfoUI(n))
    .map(
      (network): PaletteEntry => ({
        id: `network-${network.engineId}-${network.id}`,
        title: network.name,
        subtitle: 'Network',
        iconClass: 'fas fa-network-wired',
        group: 'Networks',
        onSelect: (): void => {
          openTab(
            {
              resourceType: 'network',
              resourceId: networkKey(network.name, network.engineId),
              subView: 'summary',
              title: `${network.name} · Summary`,
            },
            'newTab',
            panelId,
          );
          onClose(true);
        },
      }),
    ),
);

const secretEntries = $derived(
  $secretsInfo.map(
    (secret): PaletteEntry => ({
      id: `secret-${secret.engineId}-${secret.Id}`,
      title: secret.Name ?? '<none>',
      subtitle: 'Secret',
      iconClass: 'fas fa-key',
      group: 'Secrets',
      onSelect: (): void => {
        openTab(
          {
            resourceType: 'secret',
            resourceId: secretKey(secret.Id, secret.engineId),
            subView: 'summary',
            title: `${secret.Name ?? '<none>'} · Summary`,
          },
          'newTab',
          panelId,
        );
        onClose(true);
      },
    }),
  ),
);

const trimmedQuery = $derived(query.trim());

const AGENT_GROUP = 'Agent inspect';

// When the query's empty, lead with up to two agent findings (vuln / flaky / rebuilt).
// Typed query → single "Ask agent: …" row. Nothing found → generic prepare-layout prompt.
const proactiveInsights = $derived(findProactiveInsights(imageUIList, $podsInfos));

const agentEntries = $derived.by((): PaletteEntry[] => {
  if (trimmedQuery) {
    return [
      {
        id: 'agent',
        title: `Ask agent: "${trimmedQuery}"`,
        subtitle: 'Opens tabs automatically',
        iconClass: 'fas fa-wand-magic-sparkles',
        group: AGENT_GROUP,
        onSelect: (): void => {
          runAgentPrompt(trimmedQuery);
          onClose(true);
        },
      },
    ];
  }

  if (proactiveInsights.length > 0) {
    return proactiveInsights.map(
      (insight, index): PaletteEntry => ({
        id: `agent-insight-${index}-${insight.resourceId}`,
        title: insight.title,
        subtitle: insight.subtitle,
        iconClass: insight.iconClass,
        iconColorClass: insight.iconColorClass,
        group: AGENT_GROUP,
        onSelect: (): void => {
          openTab(
            {
              resourceType: insight.resourceType,
              resourceId: insight.resourceId,
              subView: 'summary',
              title: insight.tabTitle,
            },
            'newTab',
            panelId,
          );
          onClose(true);
        },
      }),
    );
  }

  return [
    {
      id: 'agent',
      title: 'Ask agent to prepare a layout for me',
      subtitle: 'Opens tabs automatically',
      iconClass: 'fas fa-wand-magic-sparkles',
      group: AGENT_GROUP,
      onSelect: (): void => {
        runAgentPrompt(trimmedQuery);
        onClose(true);
      },
    },
  ];
});

const filteredResourceEntries = $derived.by((): PaletteEntry[] => {
  const q = trimmedQuery.toLowerCase();
  const matches = (entry: PaletteEntry): boolean =>
    !q || entry.title.toLowerCase().includes(q) || entry.subtitle.toLowerCase().includes(q);
  return [
    ...subViewEntries,
    ...podEntries,
    ...containerEntries,
    ...imageEntries,
    ...volumeEntries,
    ...networkEntries,
    ...secretEntries,
  ].filter(matches);
});

const groupedEntries = $derived.by((): { name: string; entries: PaletteEntry[] }[] => {
  const groups: { name: string; entries: PaletteEntry[] }[] = [{ name: AGENT_GROUP, entries: agentEntries }];
  for (const entry of filteredResourceEntries) {
    let group = groups.find(g => g.name === entry.group);
    if (!group) {
      group = { name: entry.group, entries: [] };
      groups.push(group);
    }
    group.entries.push(entry);
  }
  return groups;
});

const allEntries = $derived(groupedEntries.flatMap(g => g.entries));

function onQueryInput(): void {
  selectedIndex = 0;
}

function onKeydown(event: KeyboardEvent): void {
  if (allEntries.length === 0) return;
  if (event.key === 'ArrowDown') {
    event.preventDefault();
    selectedIndex = (selectedIndex + 1) % allEntries.length;
  } else if (event.key === 'ArrowUp') {
    event.preventDefault();
    selectedIndex = (selectedIndex - 1 + allEntries.length) % allEntries.length;
  } else if (event.key === 'Enter') {
    event.preventDefault();
    allEntries[selectedIndex]?.onSelect();
  }
}

/** Every list backing this palette (pods/containers/images) comes straight from stores that
 * get a brand-new array - and brand-new entry objects - on every background poll, even when
 * nothing actually changed. Looking a row up by *object reference* (`allEntries.indexOf(entry)`)
 * would then silently return -1 the instant a poll lands between render and hover, which made
 * `selectedIndex` stick at -1 and, since every row's own index lookup failed the exact same
 * way, every row matched `-1 === -1` and lit up as "selected" at once. `id` strings are stable
 * across those refreshes, so look rows up by id instead of by identity. */
function indexOfEntry(entryId: string): number {
  return allEntries.findIndex(e => e.id === entryId);
}
</script>

<Modal name="Open a new tab" top onclose={onClose}>
  <!-- Modal's own card is capped at max-w-[32rem] (512px) and uses overflow-visible (so other
       modals can host overflowing dropdowns/tooltips). A fixed width here wider than that cap
       would spill outside the card, uncontained by that overflow-visible - looking like a
       detached, broken floating scrollbar. w-full (instead of a hardcoded px width) always
       matches whatever width the card actually resolves to, and overflow-hidden clips our own
       scrollable list to its rounded corners. -->
  <div class="flex flex-col w-full max-h-[70vh] rounded-xl overflow-hidden">
    <div class="p-2 border-b border-[var(--pd-content-divider)]">
      <input
        use:autofocus
        bind:value={query}
        oninput={onQueryInput}
        onkeydown={onKeydown}
        type="text"
        aria-label="Search pods, containers, images, volumes, networks, secrets, or ask the agent"
        placeholder="Search resources — or ask the agent…"
        class="w-full px-3 py-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)] border border-[var(--pd-input-field-focused-bg)] focus:outline-hidden" />
    </div>
    <div class="overflow-y-auto py-1">
      {#each groupedEntries as group (group.name)}
        {#if group.entries.length > 0}
          <div
            class="px-3 pt-2 pb-1 text-xs font-semibold tracking-wide text-[var(--pd-modal-dropdown-text)] opacity-70 flex items-center gap-1.5"
            class:uppercase={group.name !== AGENT_GROUP}>
            {#if group.name === AGENT_GROUP}
              <i class="fas fa-wand-magic-sparkles" aria-hidden="true"></i>
            {/if}
            {group.name}
          </div>
          {#each group.entries as entry (entry.id)}
            {@const idx = indexOfEntry(entry.id)}
            <button
              type="button"
              class="w-full flex items-center gap-3 px-3 py-2 text-left {idx === selectedIndex
                ? 'bg-[var(--pd-modal-dropdown-highlight)]'
                : 'hover:bg-[var(--pd-dropdown-bg)]'}"
              title={entry.subtitle ? `${entry.title} — ${entry.subtitle}` : entry.title}
              onmouseenter={(): void => {
                selectedIndex = idx;
              }}
              onclick={entry.onSelect}>
              <i
                class="{entry.iconClass} w-4 text-center shrink-0 {entry.iconColorClass ?? 'text-[var(--pd-modal-dropdown-text)]'}"
                aria-hidden="true"></i>
              <span class="grow overflow-hidden text-ellipsis whitespace-nowrap text-[var(--pd-modal-dropdown-text)]">
                {entry.title}
              </span>
              <span class="text-xs text-[var(--pd-modal-dropdown-text)] opacity-60 shrink-0">{entry.subtitle}</span>
            </button>
          {/each}
        {/if}
      {/each}
      {#if filteredResourceEntries.length === 0}
        <div class="px-3 py-6 text-center text-sm text-[var(--pd-modal-dropdown-text)] opacity-70">
          No matching resources — press Enter to ask the agent instead.
        </div>
      {/if}
    </div>
  </div>
</Modal>
