<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Redesigned Pod "Summary" tab content: the pre-existing PodmanPodDetailsSummary (still used
// by the legacy, non-tabbed Pod Details page - left untouched) is a single dense table with no
// visual hierarchy and nothing beyond the raw PodInfoUI fields. This pulls the same facts into
// a scannable header + cards, and cross-references the app's container store (PodInfoUI's own
// container list is just {Id, Names, Status} - no image/ports) to surface real info about what's
// actually running in the pod that the old view never showed at all.
import type { Port } from '@podman-desktop/api';
import { NavigationPage } from '@podman-desktop/core-api';
import { Link, StatusIcon } from '@podman-desktop/ui-svelte';

import PodIcon from '/@/lib/images/PodIcon.svelte';
import PodDetailsInspect from '/@/lib/pod/PodDetailsInspect.svelte';
import type { PodInfoContainerUI, PodInfoUI } from '/@/lib/pod/PodInfoUI';
import { handleNavigation } from '/@/navigation';
import { containersInfos } from '/@/stores/containers';
import { podKey } from '/@/stores/layout/layout-types';

import InspectCard from './summary/InspectCard.svelte';
import ResourceSummaryHeader from './summary/ResourceSummaryHeader.svelte';
import SummaryCard from './summary/SummaryCard.svelte';

interface Props {
  pod: PodInfoUI;
}

let { pod }: Props = $props();

const creationTime = $derived(new Date(pod.created));

interface EnrichedContainer extends PodInfoContainerUI {
  image?: string;
  ports: Port[];
}

// The pod API only tells us each container's id/name/status - the full container list (same
// store the Containers page uses) is where the actual image and published ports live.
const enrichedContainers = $derived.by((): EnrichedContainer[] =>
  pod.containers.map(c => {
    const full = $containersInfos.find(ci => ci.Id === c.Id);
    return { ...c, image: full?.Image, ports: full?.Ports ?? [] };
  }),
);

const runningCount = $derived(pod.containers.filter(c => c.Status.toLowerCase() === 'running').length);
const stoppedCount = $derived(pod.containers.length - runningCount);

const allPorts = $derived(enrichedContainers.flatMap(c => c.ports.map(port => ({ port, containerName: c.Names }))));

function navigateToLogs(container: PodInfoContainerUI): void {
  return handleNavigation({ page: NavigationPage.CONTAINER_LOGS, parameters: { id: container.Id } });
}

// Podman's own infra/pause container legitimately reports an empty Image (it has none to
// report) - a ternary (rather than `??`/`||`) is used deliberately so an empty string falls
// back too, instead of rendering a bare " · <id>" with nothing before it.
function imageLabel(image: string | undefined): string {
  if (!image) return 'No image';
  return image;
}
</script>

<div class="flex flex-col gap-4 px-5 py-4">
  <ResourceSummaryHeader
    name={pod.name}
    status={pod.status}
    statusLabel={pod.status.toLowerCase()}
    icon={PodIcon}
    id={pod.id}
    created={creationTime}
    age={pod.age} />

  <SummaryCard title="Containers" icon="fas fa-cubes">
    {#snippet trailing()}
      {runningCount} running · {stoppedCount} stopped
    {/snippet}
    {#if enrichedContainers.length > 0}
      <div class="divide-y divide-[var(--pd-content-divider)]">
        {#each enrichedContainers as container (container.Id)}
          <div class="flex items-center gap-3 px-4 py-2.5">
            <StatusIcon status={container.Status.toUpperCase()} size={14} />
            <div class="flex flex-col min-w-0 flex-1 gap-0.5">
              <Link on:click={(): void => navigateToLogs(container)}>{container.Names}</Link>
              <span class="text-xs text-[var(--pd-content-text)] opacity-60 truncate">
                {imageLabel(container.image)} · {container.Id.substring(0, 12)}
              </span>
            </div>
            <span class="text-xs text-[var(--pd-content-text)] opacity-70 lowercase shrink-0">{container.Status}</span>
          </div>
        {/each}
      </div>
    {:else}
      <div class="px-4 pb-3 text-sm text-[var(--pd-content-text)] opacity-60">No containers</div>
    {/if}
  </SummaryCard>

  {#if allPorts.length > 0}
    <SummaryCard title="Network" icon="fas fa-network-wired">
      <div class="divide-y divide-[var(--pd-content-divider)]">
        {#each allPorts as { port, containerName }, i (`${containerName}-${port.PrivatePort}-${port.Type}-${i}`)}
          <div class="flex items-center justify-between px-4 py-2 text-sm">
            <span class="text-[var(--pd-content-text)] opacity-80">{containerName}</span>
            <span class="font-mono text-xs text-[var(--pd-content-header)]">
              {port.IP || '0.0.0.0'}:{port.PublicPort} → {port.PrivatePort}/{port.Type}
            </span>
          </div>
        {/each}
      </div>
    </SummaryCard>
  {/if}

  <InspectCard resourceType="pod" resourceId={podKey(pod.name, pod.engineId)} resourceTitle={pod.name}>
    <PodDetailsInspect pod={pod} />
  </InspectCard>
</div>
