<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Renders one Podman pod sub-view (Summary/Logs/Inspect/Kube) inside a
// workspace tab, reusing the leaf components the pre-existing (non-tabbed)
// PodDetails.svelte uses.
import PodDetailsInspect from '/@/lib/pod/PodDetailsInspect.svelte';
import PodDetailsKube from '/@/lib/pod/PodDetailsKube.svelte';
import PodDetailsLogs from '/@/lib/pod/PodDetailsLogs.svelte';
import { markTabStale } from '/@/stores/layout/layout-store.svelte';
import type { PodSubView } from '/@/stores/layout/layout-types';
import { podKey } from '/@/stores/layout/layout-types';
import { podsInfos } from '/@/stores/pods';

import MockResourceStats from './MockResourceStats.svelte';
import PodSummaryTabContent from './PodSummaryTabContent.svelte';
import StaleTabPlaceholder from './StaleTabPlaceholder.svelte';

interface Props {
  tabId: string;
  podName: string;
  engineId: string;
  subView?: PodSubView;
}

let { tabId, podName, engineId, subView = 'summary' }: Props = $props();

let pod = $derived($podsInfos.find(p => p.name === podName && p.engineId === engineId));

$effect(() => {
  markTabStale(tabId, !pod);
});
</script>

{#if pod}
  <div class="flex flex-col h-full min-h-0">
    <div class="grow min-h-0 overflow-auto">
      {#if subView === 'inspect'}
        <PodDetailsInspect pod={pod} />
      {:else if subView === 'kube'}
        <PodDetailsKube pod={pod} />
      {:else if subView === 'logs'}
        <PodDetailsLogs pod={pod} />
      {:else}
        <MockResourceStats resourceId={podKey(pod.name, pod.engineId)} kind="pod" />
        <PodSummaryTabContent pod={pod} />
      {/if}
    </div>
  </div>
{:else}
  <StaleTabPlaceholder resourceLabel="Pod" tabId={tabId} />
{/if}
