<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Bridges the legacy `/pods/podman/:name/:engineId/*` deep link to the
// single, persistent tabbed workspace at `/workspace`. See
// ContainerWorkspaceEntry.svelte for the general pattern.
import { router } from 'tinro';

import { findAnyTabForResource, openTab } from '/@/stores/layout/layout-store.svelte';
import { podKey } from '/@/stores/layout/layout-types';
import { podsInfos } from '/@/stores/pods';

interface Props {
  podName: string;
  engineId: string;
}

let { podName, engineId }: Props = $props();

let pod = $derived($podsInfos.find(p => p.name === podName && p.engineId === engineId));

$effect(() => {
  if (!pod) return;
  const resourceId = podKey(pod.name, pod.engineId);
  if (!findAnyTabForResource('pod', resourceId)) {
    openTab({ resourceType: 'pod', resourceId, subView: 'summary', title: `${pod.name} · Summary` }, 'newTab');
  }
  router.goto('/workspace');
});
</script>

<div class="h-full flex items-center justify-center text-[var(--pd-content-text)]">
  <i class="fas fa-spinner fa-spin mr-2"></i>Opening in Workspace…
</div>
