<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Minimal resource pickers for the four built-in presets (section 4.8).
import { Button } from '@podman-desktop/ui-svelte';

import { ContainerUtils } from '/@/lib/container/container-utils';
import Dialog from '/@/lib/dialogs/Dialog.svelte';
import { ImageUtils } from '/@/lib/image/image-utils';
import { containersInfos } from '/@/stores/containers';
import { imagesInfos } from '/@/stores/images';
import {
  applyDebugDuoPreset,
  applyImageDiffPreset,
  applyLogsPlusTerminalPreset,
  applyPodInspectorPreset,
  type PresetId,
} from '/@/stores/layout/layout-presets';
import { gotoListShell } from '/@/stores/layout/page-tab.svelte';
import { podsInfos } from '/@/stores/pods';

import { autofocus } from './autofocus';

interface Props {
  presetId: PresetId;
  onClose: () => void;
}

let { presetId, onClose }: Props = $props();

const containerUtils = new ContainerUtils();
const imageUtils = new ImageUtils();

const containerOptions = $derived($containersInfos.map(c => containerUtils.getContainerInfoUI(c)));
const podOptions = $derived($podsInfos);
const imageOptions = $derived(
  $imagesInfos.flatMap(i => imageUtils.getImagesInfoUI(i, $containersInfos, undefined, [], $imagesInfos)),
);

let containerAId = $state('');
let containerBId = $state('');
let podResourceId = $state('');
let imageAId = $state('');
let imageBId = $state('');

// Second dropdown always excludes whatever's already picked in the first, so users can't apply a
// preset comparing a resource against itself. If the first dropdown is changed to match whatever
// was already picked in the second, clear the second - otherwise it'd keep a value that's no
// longer even offered as an option.
const containerBOptions = $derived(containerOptions.filter(c => c?.id !== containerAId));
const imageBOptions = $derived(imageOptions.filter(i => i?.id !== imageAId));

$effect(() => {
  if (containerBId && containerBId === containerAId) containerBId = '';
});
$effect(() => {
  if (imageBId && imageBId === imageAId) imageBId = '';
});

const canApply = $derived.by(() => {
  switch (presetId) {
    case 'debug-duo':
      return !!containerAId && !!containerBId && containerAId !== containerBId;
    case 'logs-terminal':
      return !!containerAId;
    case 'pod-inspector':
      return !!podResourceId;
    case 'image-diff':
      return !!imageAId && !!imageBId && imageAId !== imageBId;
    default:
      return false;
  }
});

function apply(): void {
  switch (presetId) {
    case 'debug-duo': {
      const a = containerOptions.find(c => c?.id === containerAId);
      const b = containerOptions.find(c => c?.id === containerBId);
      if (a && b) applyDebugDuoPreset(a, b);
      break;
    }
    case 'logs-terminal': {
      const a = containerOptions.find(c => c?.id === containerAId);
      if (a) applyLogsPlusTerminalPreset(a);
      break;
    }
    case 'pod-inspector': {
      const pod = podOptions.find(p => p.id === podResourceId);
      if (pod) {
        const firstContainer = pod.containers[0];
        applyPodInspectorPreset(
          pod,
          firstContainer ? { id: firstContainer.Id, name: firstContainer.Names } : undefined,
        );
      }
      break;
    }
    case 'image-diff': {
      const a = imageOptions.find(i => i?.id === imageAId);
      const b = imageOptions.find(i => i?.id === imageBId);
      if (a && b) applyImageDiffPreset(a, b);
      break;
    }
  }
  // The Layout menu is global chrome (see App.svelte), so applying a preset from any page
  // needs to jump to /workspace for the user to actually see the panels it created.
  gotoListShell();
  onClose();
}

const titles: Record<PresetId, string> = {
  'debug-duo': 'Debug Duo',
  'logs-terminal': 'Logs + Terminal',
  'pod-inspector': 'Pod Inspector',
  'image-diff': 'Image Diff',
};
</script>

<Dialog title={titles[presetId]} onclose={onClose}>
  {#snippet content()}
    <div class="w-full flex flex-col gap-3">
      {#if presetId === 'debug-duo' || presetId === 'logs-terminal'}
        <div>
          <label for="containerA" class="block my-1 text-sm font-bold text-[var(--pd-modal-text)]">
            {presetId === 'debug-duo' ? 'First container' : 'Container'}
          </label>
          <select
            id="containerA"
            use:autofocus
            class="w-full p-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)]"
            bind:value={containerAId}>
            <option value="">Select a container...</option>
            {#each containerOptions as c (c?.id)}
              {#if c}<option value={c.id}>{c.name}</option>{/if}
            {/each}
          </select>
        </div>
      {/if}
      {#if presetId === 'debug-duo'}
        <div>
          <label for="containerB" class="block my-1 text-sm font-bold text-[var(--pd-modal-text)]">Second container</label>
          <select
            id="containerB"
            class="w-full p-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)]"
            bind:value={containerBId}>
            <option value="">Select a container...</option>
            {#each containerBOptions as c (c?.id)}
              {#if c}<option value={c.id}>{c.name}</option>{/if}
            {/each}
          </select>
        </div>
      {/if}
      {#if presetId === 'pod-inspector'}
        <div>
          <label for="pod" class="block my-1 text-sm font-bold text-[var(--pd-modal-text)]">Pod</label>
          <select
            id="pod"
            use:autofocus
            class="w-full p-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)]"
            bind:value={podResourceId}>
            <option value="">Select a pod...</option>
            {#each podOptions as p (p.id)}
              <option value={p.id}>{p.name}</option>
            {/each}
          </select>
        </div>
      {/if}
      {#if presetId === 'image-diff'}
        <div>
          <label for="imageA" class="block my-1 text-sm font-bold text-[var(--pd-modal-text)]">First image</label>
          <select
            id="imageA"
            use:autofocus
            class="w-full p-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)]"
            bind:value={imageAId}>
            <option value="">Select an image...</option>
            {#each imageOptions as i (i?.id)}
              {#if i}<option value={i.id}>{i.name}:{i.tag}</option>{/if}
            {/each}
          </select>
        </div>
        <div>
          <label for="imageB" class="block my-1 text-sm font-bold text-[var(--pd-modal-text)]">Second image</label>
          <select
            id="imageB"
            class="w-full p-2 rounded-sm bg-[var(--pd-input-field-focused-bg)] text-[var(--pd-input-field-text)]"
            bind:value={imageBId}>
            <option value="">Select an image...</option>
            {#each imageBOptions as i (i?.id)}
              {#if i}<option value={i.id}>{i.name}:{i.tag}</option>{/if}
            {/each}
          </select>
        </div>
      {/if}
    </div>
  {/snippet}
  {#snippet buttons()}
    <Button type="link" on:click={onClose}>Cancel</Button>
    <Button type="primary" disabled={!canApply} on:click={apply}>Apply Preset</Button>
  {/snippet}
</Dialog>
