/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Shared "open this resource in the workspace" actions used by the
// Container/Pod/Image list row name columns, covering section 4.3 of the
// vision doc: Cmd/Ctrl+click opens in a new tab, right-click offers
// Open / Open in New Tab / Split Right / Split Down.
//
// All three helpers land on the single shared `/workspace` route (rather
// than a resource-specific detail route) so the persistent tab strip and its
// panels stay put no matter which resource type you opened the tab from -
// e.g. opening a Pod tab and then browsing to the Images list still leaves
// that Pod tab reachable from Workspace.
import type { ContextMenuAction, OpenMode } from '@podman-desktop/ui-svelte';
import { router } from 'tinro';

import { openTab } from '/@/stores/layout/layout-store.svelte';
import { imageKey, podKey } from '/@/stores/layout/layout-types';

function gotoWorkspace(): void {
  // openTab() has already updated the shared layout state; navigating to the
  // persistent /workspace route makes sure it's visible immediately.
  router.goto('/workspace');
}

export function openContainerInWorkspace(container: { id: string; name: string }, mode: OpenMode): void {
  openTab(
    { resourceType: 'container', resourceId: container.id, subView: 'summary', title: `${container.name} · Summary` },
    mode,
  );
  gotoWorkspace();
}

export function openPodInWorkspace(pod: { name: string; engineId: string }, mode: OpenMode): void {
  openTab(
    {
      resourceType: 'pod',
      resourceId: podKey(pod.name, pod.engineId),
      subView: 'summary',
      title: `${pod.name} · Summary`,
    },
    mode,
  );
  gotoWorkspace();
}

export function openImageInWorkspace(
  image: { id: string; engineId: string; name: string; tag: string; base64RepoTag: string },
  mode: OpenMode,
): void {
  openTab(
    {
      resourceType: 'image',
      resourceId: imageKey(image.id, image.engineId, image.base64RepoTag),
      subView: 'summary',
      title: `${image.name} · Summary`,
    },
    mode,
  );
  gotoWorkspace();
}

export function buildOpenContextMenuActions(open: (mode: OpenMode) => void): ContextMenuAction[] {
  return [
    { id: 'open', title: 'Open', iconClass: 'fas fa-arrow-right', onSelect: (): void => open('replace') },
    { id: 'open-new-tab', title: 'Open in New Tab', iconClass: 'fas fa-plus', onSelect: (): void => open('newTab') },
    {
      id: 'split-right',
      title: 'Open in Split Right',
      iconClass: 'fas fa-table-columns',
      separatorBefore: true,
      onSelect: (): void => open('splitRight'),
    },
    {
      id: 'split-down',
      title: 'Open in Split Down',
      iconClass: 'fas fa-table-columns',
      onSelect: (): void => open('splitDown'),
    },
  ];
}
