/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Shared "open this resource in the workspace" actions used by the
// Container/Pod/Image list row name columns, covering section 4.3 of the
// vision doc: Cmd/Ctrl+click opens in a new tab, right-click offers
// Open / Open in New Tab / Split Right / Split Down.
//
// All three helpers land on the single shared `/workspace` route (rather
// than a resource-specific detail route) so the persistent tab strip and its
// panels stay put no matter which resource type you opened the tab from -
// e.g. opening a Pod tab and then browsing to the Images list still leaves
// that Pod tab reachable from Workspace.
import type { ContextMenuAction, OpenMode } from '@podman-desktop/ui-svelte';

import { openTab, type OpenTabInput } from '/@/stores/layout/layout-store.svelte';
import type { ComposeSubView } from '/@/stores/layout/layout-types';
import {
  composeKey,
  imageKey,
  manifestKey,
  networkKey,
  podKey,
  secretKey,
  volumeKey,
} from '/@/stores/layout/layout-types';
import { gotoListShell } from '/@/stores/layout/page-tab.svelte';

function gotoWorkspace(): void {
  // Stay on the list route (Containers, …) so the permanent page tab + nav highlight
  // remain; resource content is shown in a section tab inside TabbedListShell.
  gotoListShell();
}

/**
 * Open each selected resource as its own section (splitRight chain) for side-by-side compare.
 * First fills an empty leaf (or splits if one already has tabs); each next item gets a new section.
 */
export function compareResourcesWithTabs(inputs: OpenTabInput[]): void {
  if (inputs.length === 0) return;
  for (const input of inputs) {
    openTab(input, 'splitRight');
  }
  gotoWorkspace();
}

export function openContainerInWorkspace(container: { id: string; name: string }, mode: OpenMode): void {
  openTab(
    { resourceType: 'container', resourceId: container.id, subView: 'summary', title: `${container.name} · Summary` },
    mode,
  );
  gotoWorkspace();
}

export function openContainerPreviewInWorkspace(
  container: { name: string; openingUrl: string },
  mode: OpenMode = 'newTab',
): void {
  openTab(
    {
      resourceType: 'app-preview',
      resourceId: container.openingUrl,
      title: `${container.name} · Preview`,
      subtitle: container.openingUrl,
      iconClass: 'fas fa-globe',
    },
    mode,
  );
  gotoWorkspace();
}

export function openPodInWorkspace(pod: { name: string; engineId: string }, mode: OpenMode): void {
  openTab(
    {
      resourceType: 'pod',
      resourceId: podKey(pod.name, pod.engineId),
      subView: 'summary',
      title: `${pod.name} · Summary`,
    },
    mode,
  );
  gotoWorkspace();
}

export function openImageInWorkspace(
  image: { id: string; engineId: string; name: string; tag: string; base64RepoTag: string },
  mode: OpenMode,
): void {
  openTab(
    {
      resourceType: 'image',
      resourceId: imageKey(image.id, image.engineId, image.base64RepoTag),
      subView: 'summary',
      title: `${image.name} · Summary`,
    },
    mode,
  );
  gotoWorkspace();
}

export function openVolumeInWorkspace(
  volume: { name: string; shortName: string; engineId: string },
  mode: OpenMode,
): void {
  openTab(
    {
      resourceType: 'volume',
      resourceId: volumeKey(volume.name, volume.engineId),
      subView: 'summary',
      title: `${volume.shortName} · Summary`,
    },
    mode,
  );
  gotoWorkspace();
}

export function openNetworkInWorkspace(network: { name: string; engineId: string }, mode: OpenMode): void {
  openTab(
    {
      resourceType: 'network',
      resourceId: networkKey(network.name, network.engineId),
      subView: 'summary',
      title: `${network.name} · Summary`,
    },
    mode,
  );
  gotoWorkspace();
}

export function openSecretInWorkspace(secret: { Id: string; Name: string; engineId: string }, mode: OpenMode): void {
  openTab(
    {
      resourceType: 'secret',
      resourceId: secretKey(secret.Id, secret.engineId),
      subView: 'summary',
      title: `${secret.Name} · Summary`,
    },
    mode,
  );
  gotoWorkspace();
}

export function openComposeInWorkspace(
  compose: { name: string; engineId: string },
  mode: OpenMode,
  subView: ComposeSubView = 'summary',
): void {
  const label = subView === 'summary' ? 'Summary' : subView.charAt(0).toUpperCase() + subView.slice(1);
  openTab(
    {
      resourceType: 'compose',
      resourceId: composeKey(compose.name, compose.engineId),
      subView,
      title: `${compose.name} · ${label}`,
    },
    mode,
  );
  gotoWorkspace();
}

export function openManifestInWorkspace(
  image: { id: string; engineId: string; name: string; base64RepoTag: string },
  mode: OpenMode,
): void {
  openTab(
    {
      resourceType: 'manifest',
      resourceId: manifestKey(image.id, image.engineId, image.base64RepoTag),
      subView: 'summary',
      title: `${image.name} · Summary`,
    },
    mode,
  );
  gotoWorkspace();
}

export function buildOpenContextMenuActions(open: (mode: OpenMode) => void): ContextMenuAction[] {
  return [
    { id: 'open', title: 'Open', iconClass: 'fas fa-arrow-right', onSelect: (): void => open('replace') },
    { id: 'open-new-tab', title: 'Open in New Tab', iconClass: 'fas fa-plus', onSelect: (): void => open('newTab') },
    {
      id: 'split-right',
      title: 'Open in Split Right',
      iconClass: 'fas fa-table-columns',
      separatorBefore: true,
      onSelect: (): void => open('splitRight'),
    },
    {
      id: 'split-down',
      title: 'Open in Split Down',
      iconClass: 'fas fa-table-columns',
      onSelect: (): void => open('splitDown'),
    },
  ];
}
