<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Redesigned Secret Summary tab — same carded layout as container/image summaries.
import type { SecretInfo } from '@podman-desktop/core-api';

import SecretDetailsInspect from '/@/lib/secrets/tabs/SecretDetailsInspect.svelte';
import { secretKey } from '/@/stores/layout/layout-types';

import InspectCard from './summary/InspectCard.svelte';
import ResourceSummaryHeader from './summary/ResourceSummaryHeader.svelte';
import SummaryCard from './summary/SummaryCard.svelte';

interface Props {
  tabId: string;
  secret: SecretInfo;
}

let { tabId, secret }: Props = $props();

const labelEntries = $derived(secret.Labels ? Object.entries(secret.Labels) : []);
const createdDate = $derived(secret.CreatedAt ? new Date(secret.CreatedAt) : undefined);
</script>

<div class="flex flex-col gap-4 px-5 py-4">
  <ResourceSummaryHeader
    name={secret.Name}
    icon="fas fa-key"
    id={secret.Id}
    created={createdDate} />

  <SummaryCard title="Details" icon="fas fa-circle-info">
    <div class="grid grid-cols-2 sm:grid-cols-3 gap-3 px-4 pb-3">
      <div class="flex flex-col min-w-0">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Secret ID</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)] font-mono truncate" title={secret.Id}>
          {secret.Id}
        </span>
      </div>
      <div class="flex flex-col">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Updated</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)]">
          {secret.UpdatedAt ? new Date(secret.UpdatedAt).toLocaleString() : 'N/A'}
        </span>
      </div>
      <div class="flex flex-col min-w-0">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Engine</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)] truncate" title={secret.engineName}>
          {secret.engineName}
        </span>
      </div>
      <div class="flex flex-col">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Engine type</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)]">{secret.engineType}</span>
      </div>
    </div>
  </SummaryCard>

  {#if labelEntries.length > 0}
    <SummaryCard title="Labels" icon="fas fa-tags">
      <div class="flex flex-wrap gap-1.5 px-4 pb-3">
        {#each labelEntries as [key, value] (key)}
          <span
            class="text-xs font-mono px-2 py-1 rounded-md bg-[var(--pd-content-bg)] border border-[var(--pd-content-divider)] text-[var(--pd-content-text)] break-all min-w-0 max-w-full">
            {key}={value}
          </span>
        {/each}
      </div>
    </SummaryCard>
  {:else}
    <SummaryCard title="Labels" icon="fas fa-tags">
      <div class="px-4 pb-3 text-sm text-[var(--pd-content-text)] opacity-60">No labels</div>
    </SummaryCard>
  {/if}

  <InspectCard
    resourceType="secret"
    resourceId={secretKey(secret.Id, secret.engineId)}
    resourceTitle={secret.Name}
    {tabId}>
    <SecretDetailsInspect {secret} />
  </InspectCard>
</div>
