<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
import SecretDetailsInspect from '/@/lib/secrets/tabs/SecretDetailsInspect.svelte';
import { markTabStale } from '/@/stores/layout/layout-store.svelte';
import type { SecretSubView } from '/@/stores/layout/layout-types';
import { secretsInfo } from '/@/stores/secrets';

import SecretSummaryTabContent from './SecretSummaryTabContent.svelte';
import StaleTabPlaceholder from './StaleTabPlaceholder.svelte';

interface Props {
  tabId: string;
  secretId: string;
  engineId: string;
  subView?: SecretSubView;
}

let { tabId, secretId, engineId, subView = 'summary' }: Props = $props();

let secret = $derived($secretsInfo.find(item => item.Id === secretId && item.engineId === engineId));

$effect(() => {
  markTabStale(tabId, !secret);
});
</script>

{#if secret}
  <div class="flex flex-col h-full min-h-0 overflow-auto">
    {#if subView === 'inspect'}
      <SecretDetailsInspect {secret} />
    {:else}
      <SecretSummaryTabContent {tabId} {secret} />
    {/if}
  </div>
{:else}
  <StaleTabPlaceholder resourceLabel="Secret" tabId={tabId} />
{/if}
