<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Surfaces the same kind of "here's what's different" insight as the agent demo banner, but for
// a plain two-way split the user made themselves (dragged/split a tab, not the "Ask agent" demo)
// - a side-by-side view of two pods or two images is the same comparison moment either way, and
// there's no reason the insight should only show up when an agent happened to be the one who
// opened it. Uses a lightbulb + neutral wording ("Comparing...") instead of the agent banner's
// robot icon/"An agent opened..." phrasing, since no agent action actually happened here, and
// there's nothing to "Undo" - the user's own split is left exactly as they made it.
import {
  agentBannerState,
  dismissSplitInsight,
  getSplitComparisonInsight,
} from '/@/stores/layout/layout-agent-demo.svelte';

let insight = $derived(getSplitComparisonInsight());
</script>

{#if !agentBannerState.visible && insight}
  <div
    class="flex items-center gap-3 px-3 py-2 bg-[var(--pd-content-bg)] border-b border-[var(--pd-content-divider)] text-sm">
    <i class="fas fa-lightbulb text-[var(--pd-status-running)]"></i>
    <span class="grow">{insight.message}</span>
    <button
      type="button"
      aria-label="Dismiss"
      class="px-2 py-1 rounded-sm hover:bg-[var(--pd-action-button-details-bg)]"
      onclick={dismissSplitInsight}>
      <i class="fas fa-xmark"></i>
    </button>
  </div>
{/if}
