<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Shown inside a tab when the resource it points to (a container, pod, image,
// or a resource referenced by a restored/named layout) no longer exists -
// per section 4.7 of the vision doc ("graceful stale handling").
import { faTriangleExclamation } from '@fortawesome/free-solid-svg-icons';
import { EmptyScreen } from '@podman-desktop/ui-svelte';

import { closeTabById } from '/@/stores/layout/layout-store.svelte';

interface Props {
  tabId: string;
  resourceLabel: string;
}

let { tabId, resourceLabel }: Props = $props();
</script>

<div class="h-full flex items-center justify-center">
  <EmptyScreen
    icon={faTriangleExclamation}
    title="{resourceLabel} not found"
    message="This {resourceLabel.toLowerCase()} no longer exists. It may have been removed or the layout referencing it is out of date.">
    <button
      type="button"
      class="mt-4 px-3 py-1.5 rounded-md bg-[var(--pd-button-primary-bg)] text-[var(--pd-button-primary-text)] hover:bg-[var(--pd-button-primary-hover-bg)]"
      onclick={(): void => closeTabById(tabId)}>
      Dismiss
    </button>
  </EmptyScreen>
</div>
