<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// List-page entry for the tabs prototype: syncs the permanent page tab to this
// route and shows the sectioned workspace (page tab + resource tabs).
import { activatePageTab, ensurePageTab, resourceTabCount } from '/@/stores/layout/layout-store.svelte';
import { rememberAppPage } from '/@/stores/layout/page-tab.svelte';

import WorkspaceLayout from './WorkspaceLayout.svelte';

interface Props {
  pageUrl: string;
  pageName: string;
}

let { pageUrl, pageName }: Props = $props();

let seenPageUrl: string | undefined = $state();

$effect(() => {
  rememberAppPage(pageUrl, pageName);
  ensurePageTab();

  const switchedList = seenPageUrl !== undefined && seenPageUrl !== pageUrl;
  seenPageUrl = pageUrl;

  // First visit with no resource tabs, or sidebar switch to another list → show page tab.
  // Do not steal focus when mounting after a deep-link/open that already selected a resource tab.
  if (switchedList || resourceTabCount() === 0) {
    activatePageTab();
  }
});
</script>

<WorkspaceLayout />
