<!--**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************-->
<script lang="ts">
// Generated by Cursor
// Redesigned Volume Summary tab — same carded layout as container/image summaries.
import { Link } from '@podman-desktop/ui-svelte';

import { openContainerInWorkspace } from '/@/lib/layout/resource-open-actions';
import VolumeDetailsInspect from '/@/lib/volume/VolumeDetailsInspect.svelte';
import type { VolumeInfoUI } from '/@/lib/volume/VolumeInfoUI';
import { volumeKey } from '/@/stores/layout/layout-types';

import InspectCard from './summary/InspectCard.svelte';
import ResourceSummaryHeader from './summary/ResourceSummaryHeader.svelte';
import SummaryCard from './summary/SummaryCard.svelte';

interface Props {
  tabId: string;
  volume: VolumeInfoUI;
}

let { tabId, volume }: Props = $props();

const STATUS_LABEL: Record<VolumeInfoUI['status'], string> = {
  USED: 'used',
  UNUSED: 'unused',
  DELETING: 'deleting',
};

const createdDate = $derived(new Date(volume.created));

function openContainer(container: { id: string; names: string[] }): void {
  const name = container.names.map(n => (n.startsWith('/') ? n.slice(1) : n)).join(' ') || container.id;
  openContainerInWorkspace({ id: container.id, name }, 'newTab');
}
</script>

<div class="flex flex-col gap-4 px-5 py-4">
  <ResourceSummaryHeader
    name={volume.name}
    status={volume.status}
    statusLabel={STATUS_LABEL[volume.status]}
    icon="fas fa-database"
    id={volume.name}
    created={createdDate}
    age={volume.age} />

  <SummaryCard title="Details" icon="fas fa-circle-info">
    <div class="grid grid-cols-2 sm:grid-cols-3 gap-3 px-4 pb-3">
      <div class="flex flex-col">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Size</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)]">{volume.humanSize}</span>
      </div>
      <div class="flex flex-col">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Driver</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)]">{volume.driver}</span>
      </div>
      <div class="flex flex-col">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Scope</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)]">{volume.scope}</span>
      </div>
      <div class="flex flex-col min-w-0 sm:col-span-2">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Mount point</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)] font-mono truncate" title={volume.mountPoint}>
          {volume.mountPoint}
        </span>
      </div>
      <div class="flex flex-col min-w-0">
        <span class="text-xs text-[var(--pd-content-text)] opacity-60">Engine</span>
        <span class="text-sm font-medium text-[var(--pd-content-header)] truncate" title={volume.engineName}>
          {volume.engineName}
        </span>
      </div>
    </div>
  </SummaryCard>

  <SummaryCard title="Container usage">
    {#snippet trailing()}
      {volume.containersUsage.length} container{volume.containersUsage.length === 1 ? '' : 's'}
    {/snippet}
    {#if volume.containersUsage.length > 0}
      <div class="divide-y divide-[var(--pd-content-divider)]">
        {#each volume.containersUsage as container (container.id)}
          <div class="flex items-center justify-between gap-3 px-4 py-2 text-sm">
            <Link class="truncate min-w-0" on:click={(): void => openContainer(container)}>
              {container.names.map(n => (n.startsWith('/') ? n.slice(1) : n)).join(' ')}
            </Link>
            <span class="text-xs font-mono text-[var(--pd-content-text)] opacity-60 shrink-0">
              {container.id.slice(0, 12)}
            </span>
          </div>
        {/each}
      </div>
    {:else}
      <div class="px-4 pb-3 text-sm text-[var(--pd-content-text)] opacity-60">
        No containers are currently using this volume.
      </div>
    {/if}
  </SummaryCard>

  <InspectCard
    resourceType="volume"
    resourceId={volumeKey(volume.name, volume.engineId)}
    resourceTitle={volume.shortName || volume.name}
    {tabId}>
    <VolumeDetailsInspect {volume} />
  </InspectCard>
</div>
