<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
import { VolumeUtils } from '/@/lib/volume/volume-utils';
import VolumeDetailsInspect from '/@/lib/volume/VolumeDetailsInspect.svelte';
import { markTabStale } from '/@/stores/layout/layout-store.svelte';
import type { VolumeSubView } from '/@/stores/layout/layout-types';
import { volumeListInfos } from '/@/stores/volumes';

import StaleTabPlaceholder from './StaleTabPlaceholder.svelte';
import VolumeSummaryTabContent from './VolumeSummaryTabContent.svelte';

interface Props {
  tabId: string;
  volumeName: string;
  engineId: string;
  subView?: VolumeSubView;
}

let { tabId, volumeName, engineId, subView = 'summary' }: Props = $props();

const volumeUtils = new VolumeUtils();

let volume = $derived.by(() => {
  const allVolumes = $volumeListInfos.map(volumeListInfo => volumeListInfo.Volumes).flat();
  const matching = allVolumes.find(v => v.Name === volumeName && v.engineId === engineId);
  if (!matching) return undefined;
  try {
    return volumeUtils.toVolumeInfoUI(matching);
  } catch (err: unknown) {
    console.error(`Error getting volume info ${volumeName} ${engineId}: ${err}`);
    return undefined;
  }
});

$effect(() => {
  markTabStale(tabId, !volume);
});
</script>

{#if volume}
  <div class="flex flex-col h-full min-h-0 overflow-auto">
    {#if subView === 'inspect'}
      <VolumeDetailsInspect {volume} />
    {:else}
      <VolumeSummaryTabContent {tabId} {volume} />
    {/if}
  </div>
{:else}
  <StaleTabPlaceholder resourceLabel="Volume" tabId={tabId} />
{/if}
