<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor

import { VolumeUtils } from '/@/lib/volume/volume-utils';
import { findAnyTabForResource, openTab } from '/@/stores/layout/layout-store.svelte';
import { volumeKey } from '/@/stores/layout/layout-types';
import { gotoListShell } from '/@/stores/layout/page-tab.svelte';
import { volumeListInfos } from '/@/stores/volumes';

interface Props {
  volumeName: string;
  engineId: string;
}

let { volumeName, engineId }: Props = $props();

const volumeUtils = new VolumeUtils();

let volume = $derived.by(() => {
  const allVolumes = $volumeListInfos.map(volumeListInfo => volumeListInfo.Volumes).flat();
  const matching = allVolumes.find(v => v.Name === volumeName && v.engineId === engineId);
  if (!matching) return undefined;
  try {
    return volumeUtils.toVolumeInfoUI(matching);
  } catch {
    return undefined;
  }
});

$effect(() => {
  if (!volume) return;
  const resourceId = volumeKey(volume.name, volume.engineId);
  if (!findAnyTabForResource('volume', resourceId)) {
    openTab(
      { resourceType: 'volume', resourceId, subView: 'summary', title: `${volume.shortName} · Summary` },
      'newTab',
    );
  }
  gotoListShell();
});
</script>

<div class="h-full flex items-center justify-center text-[var(--pd-content-text)]">
  <i class="fas fa-spinner fa-spin mr-2"></i>Opening in Workspace…
</div>
