<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Top-level tabbed workspace: renders the current panel tree from
// layout-store.svelte.ts, and resolves each tab's content by resourceType.
// Mounted from Container/Pod/Image "workspace entry" routes - see
// ContainerWorkspaceEntry.svelte etc. Backed entirely by module-level state,
// so remounting (e.g. navigating away and back) doesn't lose anything.
import type { TabDescriptor } from '@podman-desktop/ui-svelte';
import { EmptyScreen, PanelGroup } from '@podman-desktop/ui-svelte';

import {
  canMoveTabToNewSection,
  closeActiveTab,
  closeAllInPanel,
  closeOthers,
  closeTab,
  cycleActiveTab,
  ensurePageTab,
  findLeaf,
  focusPanel,
  getLastLeafId,
  getTabsForPanel,
  layoutState,
  moveTabFromOtherPanel,
  moveToNewPanel,
  pinToggle,
  reorderTab,
  resizeSplit,
  selectTab,
  splitDown,
  splitRight,
  toggleMaximize,
} from '/@/stores/layout/layout-store.svelte';
import type {
  ComposeSubView,
  ContainerSubView,
  ImageSubView,
  ManifestSubView,
  NetworkSubView,
  PodSubView,
  SecretSubView,
  VolumeSubView,
  WorkspaceTab,
} from '/@/stores/layout/layout-types';
import {
  parseComposeKey,
  parseImageKey,
  parseManifestKey,
  parseNetworkKey,
  parsePodKey,
  parseSecretKey,
  parseVolumeKey,
} from '/@/stores/layout/layout-types';
import { currentScreen } from '/@/stores/prototype';

import ActionTabContent from './ActionTabContent.svelte';
import AgentLayoutBanner from './AgentLayoutBanner.svelte';
import AppPageTabContent from './AppPageTabContent.svelte';
import CloseSectionButton from './CloseSectionButton.svelte';
import ComposeTabContent from './ComposeTabContent.svelte';
import ContainerTabContent from './ContainerTabContent.svelte';
import ImageTabContent from './ImageTabContent.svelte';
import LayoutToolbar from './LayoutToolbar.svelte';
import ManifestTabContent from './ManifestTabContent.svelte';
import MaximizedPanelBanner from './MaximizedPanelBanner.svelte';
import NetworkTabContent from './NetworkTabContent.svelte';
import NewTabPalette from './NewTabPalette.svelte';
import PodTabContent from './PodTabContent.svelte';
import SecretTabContent from './SecretTabContent.svelte';
import SplitInsightBanner from './SplitInsightBanner.svelte';
import VolumeTabContent from './VolumeTabContent.svelte';

$effect(() => {
  ensurePageTab();
});

const panelCount = $derived(countTabsPanels());

function countTabsPanels(): number {
  const stack = [layoutState.tree];
  let count = 0;
  while (stack.length) {
    const node = stack.pop();
    if (!node) continue;
    if (node.kind === 'leaf') count += 1;
    else stack.push(...node.children);
  }
  return count;
}

const displayedNode = $derived.by(() => {
  if (!layoutState.maximizedPanelId) return layoutState.tree;
  const maximized = findLeaf(layoutState.tree, layoutState.maximizedPanelId);
  return maximized ?? layoutState.tree;
});

function onWindowKeydown(event: KeyboardEvent): void {
  if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'w') {
    event.preventDefault();
    closeActiveTab();
    return;
  }
  // Ctrl+Tab / Ctrl+Shift+Tab cycle through tabs in the focused panel - deliberately plain
  // Ctrl even on macOS (not Cmd+Tab), matching Cursor/VS Code's own cross-platform keybinding,
  // since Cmd+Tab is reserved by macOS itself for app-switching and would never reach the app.
  if (event.ctrlKey && event.key === 'Tab') {
    event.preventDefault();
    cycleActiveTab(event.shiftKey ? -1 : 1);
  }
}

/** Powers each panel's tab-strip "+" button: opens the new-tab command palette (other
 * sub-views of the active resource, any pod/container/image, or a free-text ask-the-agent
 * entry) scoped to that panel - see NewTabPalette.svelte. */
let newTabPaletteFor: { panelId: string; activeTab: WorkspaceTab | undefined } | undefined = $state();

function openNewTabPalette(panelId: string, activeTab: TabDescriptor | undefined): void {
  newTabPaletteFor = { panelId, activeTab: activeTab as WorkspaceTab | undefined };
}
</script>

<svelte:window onkeydown={onWindowKeydown} />

<div class="flex flex-col h-full min-h-0 w-full">
  <!-- Each section has its own TabBar. Version 1 also keeps a permanent list/dashboard
       tab in the first section; Version 2 omits it (lists are in the compact sidebar). -->
  <AgentLayoutBanner />
  {#if !layoutState.maximizedPanelId}
    <SplitInsightBanner />
  {/if}
  <div class="grow min-h-0">
    <PanelGroup
      node={displayedNode}
      getTabs={getTabsForPanel}
      focusedPanelId={layoutState.focusedPanelId}
      maximizedPanelId={layoutState.maximizedPanelId}
      panelCount={panelCount}
      onFocusPanel={focusPanel}
      onSelectTab={selectTab}
      onCloseTab={closeTab}
      onCloseOthers={closeOthers}
      onCloseAllInPanel={closeAllInPanel}
      onPinToggle={pinToggle}
      onReorder={reorderTab}
      onMoveFromOtherPanel={moveTabFromOtherPanel}
      onSplitRight={splitRight}
      onSplitDown={splitDown}
      onMoveToNewPanel={moveToNewPanel}
      onToggleMaximize={toggleMaximize}
      onResizeSplit={resizeSplit}
      onAddTab={openNewTabPalette}
      canOpenInNewSection={canMoveTabToNewSection}>
      {#snippet trailing(panelId, tabs)}
        <CloseSectionButton panelId={panelId} {tabs} />
      {/snippet}
      {#snippet globalTrailing(panelId)}
        <!-- Global settings once: far right of last section (or maximized section). -->
        {#if panelId === (layoutState.maximizedPanelId ?? getLastLeafId())}
          <LayoutToolbar panelId={panelId} />
        {/if}
      {/snippet}
      {#snippet beforeAdd(panelId)}
        {#if layoutState.maximizedPanelId === panelId}
          <MaximizedPanelBanner />
        {/if}
      {/snippet}
      {#snippet tabContent(tabDescriptor)}
        {@const tab = tabDescriptor as WorkspaceTab}
        {#if tab.resourceType === 'app-page'}
          <AppPageTabContent />
        {:else if tab.resourceType === 'container'}
          <ContainerTabContent tabId={tab.id} containerId={tab.resourceId} subView={tab.subView as ContainerSubView} />
        {:else if tab.resourceType === 'pod'}
          {@const parsed = parsePodKey(tab.resourceId)}
          <PodTabContent
            tabId={tab.id}
            podName={parsed.name}
            engineId={parsed.engineId}
            subView={tab.subView as PodSubView} />
        {:else if tab.resourceType === 'image'}
          {@const parsed = parseImageKey(tab.resourceId)}
          <ImageTabContent
            tabId={tab.id}
            imageId={parsed.imageId}
            engineId={parsed.engineId}
            base64RepoTag={parsed.base64RepoTag}
            subView={tab.subView as ImageSubView} />
        {:else if tab.resourceType === 'volume'}
          {@const parsed = parseVolumeKey(tab.resourceId)}
          <VolumeTabContent
            tabId={tab.id}
            volumeName={parsed.name}
            engineId={parsed.engineId}
            subView={tab.subView as VolumeSubView} />
        {:else if tab.resourceType === 'network'}
          {@const parsed = parseNetworkKey(tab.resourceId)}
          <NetworkTabContent
            tabId={tab.id}
            networkName={parsed.name}
            engineId={parsed.engineId}
            subView={tab.subView as NetworkSubView} />
        {:else if tab.resourceType === 'secret'}
          {@const parsed = parseSecretKey(tab.resourceId)}
          <SecretTabContent
            tabId={tab.id}
            secretId={parsed.secretId}
            engineId={parsed.engineId}
            subView={tab.subView as SecretSubView} />
        {:else if tab.resourceType === 'compose'}
          {@const parsed = parseComposeKey(tab.resourceId)}
          <ComposeTabContent
            tabId={tab.id}
            composeName={parsed.name}
            engineId={parsed.engineId}
            subView={tab.subView as ComposeSubView} />
        {:else if tab.resourceType === 'manifest'}
          {@const parsed = parseManifestKey(tab.resourceId)}
          <ManifestTabContent
            tabId={tab.id}
            imageId={parsed.imageId}
            engineId={parsed.engineId}
            base64RepoTag={parsed.base64RepoTag}
            subView={tab.subView as ManifestSubView} />
        {:else if tab.resourceType === 'action'}
          <ActionTabContent actionId={tab.resourceId} />
        {/if}
      {/snippet}
      {#snippet emptyState()}
        <div class="h-full flex items-center justify-center">
          {#if $currentScreen === 'compact-nav'}
            <EmptyScreen
              icon="fas fa-table-columns"
              title="Open a resource from the sidebar"
              message="Containers, pods, images, volumes, networks, and secrets are listed next to the activity bar. Click one to open it as a tab here — or use a section’s ⋮ menu for Load, Pull, Create, and similar actions." />
          {:else}
            <EmptyScreen
              icon="fas fa-table-cells"
              title="No tabs open"
              message="Open a container, pod, image, volume, network, or secret from its list to get started." />
          {/if}
        </div>
      {/snippet}
    </PanelGroup>
  </div>
</div>

{#if newTabPaletteFor}
  <NewTabPalette
    panelId={newTabPaletteFor.panelId}
    activeTab={newTabPaletteFor.activeTab}
    onClose={(): void => {
      newTabPaletteFor = undefined;
    }} />
{/if}
