<script lang="ts">
/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

// Generated by Cursor
// Top-level tabbed workspace: renders the current panel tree from
// layout-store.svelte.ts, and resolves each tab's content by resourceType.
// Mounted from Container/Pod/Image "workspace entry" routes - see
// ContainerWorkspaceEntry.svelte etc. Backed entirely by module-level state,
// so remounting (e.g. navigating away and back) doesn't lose anything.
import type { TabDescriptor } from '@podman-desktop/ui-svelte';
import { EmptyScreen, PanelGroup } from '@podman-desktop/ui-svelte';

import {
  closeActiveTab,
  closeAllInPanel,
  closeOthers,
  closeTab,
  findLeaf,
  focusPanel,
  getTabsForPanel,
  layoutState,
  moveTabFromOtherPanel,
  moveToNewPanel,
  pinToggle,
  reorderTab,
  resizeSplit,
  selectTab,
  splitDown,
  splitRight,
  toggleMaximize,
} from '/@/stores/layout/layout-store.svelte';
import type { ContainerSubView, ImageSubView, PodSubView, WorkspaceTab } from '/@/stores/layout/layout-types';
import { parseImageKey, parsePodKey } from '/@/stores/layout/layout-types';

import AgentLayoutBanner from './AgentLayoutBanner.svelte';
import ContainerTabContent from './ContainerTabContent.svelte';
import ImageTabContent from './ImageTabContent.svelte';
import NewTabPalette from './NewTabPalette.svelte';
import PodTabContent from './PodTabContent.svelte';

const panelCount = $derived(countTabsPanels());

function countTabsPanels(): number {
  const stack = [layoutState.tree];
  let count = 0;
  while (stack.length) {
    const node = stack.pop();
    if (!node) continue;
    if (node.kind === 'leaf') count += 1;
    else stack.push(...node.children);
  }
  return count;
}

const displayedNode = $derived.by(() => {
  if (!layoutState.maximizedPanelId) return layoutState.tree;
  const maximized = findLeaf(layoutState.tree, layoutState.maximizedPanelId);
  return maximized ?? layoutState.tree;
});

function onWindowKeydown(event: KeyboardEvent): void {
  if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'w') {
    event.preventDefault();
    closeActiveTab();
  }
}

/** Powers each panel's tab-strip "+" button: opens the new-tab command palette (other
 * sub-views of the active resource, any pod/container/image, or a free-text ask-the-agent
 * entry) scoped to that panel - see NewTabPalette.svelte. */
let newTabPaletteFor: { panelId: string; activeTab: WorkspaceTab | undefined } | undefined = $state();

function openNewTabPalette(panelId: string, activeTab: TabDescriptor | undefined): void {
  newTabPaletteFor = { panelId, activeTab: activeTab as WorkspaceTab | undefined };
}
</script>

<svelte:window onkeydown={onWindowKeydown} />

<div class="flex flex-col h-full min-h-0 w-full">
  <!-- The Layout menu and the flat "all open tabs" bar are mounted once, globally, in
       App.svelte, so they stay visible on every page - not just here. This route only owns the
       actual panel/split content. -->
  <AgentLayoutBanner />
  <div class="grow min-h-0">
    <PanelGroup
      node={displayedNode}
      getTabs={getTabsForPanel}
      focusedPanelId={layoutState.focusedPanelId}
      panelCount={panelCount}
      onFocusPanel={focusPanel}
      onSelectTab={selectTab}
      onCloseTab={closeTab}
      onCloseOthers={closeOthers}
      onCloseAllInPanel={closeAllInPanel}
      onPinToggle={pinToggle}
      onReorder={reorderTab}
      onMoveFromOtherPanel={moveTabFromOtherPanel}
      onSplitRight={splitRight}
      onSplitDown={splitDown}
      onMoveToNewPanel={moveToNewPanel}
      onToggleMaximize={toggleMaximize}
      onResizeSplit={resizeSplit}
      onAddTab={openNewTabPalette}>
      {#snippet tabContent(tabDescriptor)}
        {@const tab = tabDescriptor as WorkspaceTab}
        {#if tab.resourceType === 'container'}
          <ContainerTabContent tabId={tab.id} containerId={tab.resourceId} subView={tab.subView as ContainerSubView} />
        {:else if tab.resourceType === 'pod'}
          {@const parsed = parsePodKey(tab.resourceId)}
          <PodTabContent
            tabId={tab.id}
            podName={parsed.name}
            engineId={parsed.engineId}
            subView={tab.subView as PodSubView} />
        {:else if tab.resourceType === 'image'}
          {@const parsed = parseImageKey(tab.resourceId)}
          <ImageTabContent
            tabId={tab.id}
            imageId={parsed.imageId}
            engineId={parsed.engineId}
            base64RepoTag={parsed.base64RepoTag}
            subView={tab.subView as ImageSubView} />
        {/if}
      {/snippet}
      {#snippet emptyState()}
        <div class="h-full flex items-center justify-center">
          <EmptyScreen
            icon="fas fa-table-cells"
            title="No tabs open"
            message="Open a container, pod, or image from its list to get started." />
        </div>
      {/snippet}
    </PanelGroup>
  </div>
</div>

{#if newTabPaletteFor}
  <NewTabPalette
    panelId={newTabPaletteFor.panelId}
    activeTab={newTabPaletteFor.activeTab}
    onClose={(): void => {
      newTabPaletteFor = undefined;
    }} />
{/if}
